### ISSUE TITLE
Feature request: add interactive REPL window, ala PowerShell ISE

### ISSUE THREAD

**Issue by codemonkeychris** [PowerShell/vscode-powershell#10]

**Comment by rkeithhill** [comment]
FYI, while you are *debugging* you can execute arbitrary commands in the Debug console.  My understanding is that a generic REPL feature is something the VS Code team needs to support first.  @daviwil - correct me if I'm wrong this count.

**Comment by daviwil** [comment]
Keith is exactly right.  Let's start bugging them with feedback about having a persistent REPL which doesn't require the debugger!

**Comment by singhkay** [comment]
+1 on this!

**Comment by dcrreynolds** [comment]
This would be great to have!

**Comment by dotps1** [comment]
+1

**Comment by ducke** [comment]
:+1:

**Comment by daviwil** [comment]
Just got one step closer to this: the new update (0.2.0) includes a "Run selection" command bound to F8 which allows you to run a script selection and see the output.  Not exactly "interactive" but does allow you to run arbitrary PowerShell code and see the output.  I'll keep this bug open until full interactive console support is completed.

**Comment by pstephens** [comment]
+1

**Comment by hairylime** [comment]
yes, please - close the book on ISE completely with this feature

**Comment by daviwil** [comment]
The new integrated terminal in VS Code has opened up some interesting possibilities, I'm looking into how I can use that to our advantage :)

**Comment by JustinGrote** [comment]
That would be great! For now I use the integrated terminal and dot source the scripts I need as a sort of poor man's REPL, but having it more seamless would be great.

**Comment by daviwil** [comment]
I'm going to experiment a little bit and see if I can make something happen here for the 0.8.0 release of the extension.

**Comment by dotps1** [comment]
do it @daviwil!  DO IT!

**Comment by JustinGrote** [comment]
I'd say it's not the highest of high priorities, but it is basically the only reason why I use ISE anymore, I'll flip back there if I need to "experiment" with a script because it's just way too cumbersome to start, debug, can't F9/paste some code into that same debug session easily to try it over and over in a particular context (e.g. middle of a foreach loop), etc., and then lose all my state if I want to tweak something in the code and re-run it.

How I would ideally like to see this is a config setting or something that says "make the debug session persistent", so that every time I run, it keeps in the same powershell environment and doesn't recycle it. Then the debug console effectively becomes REPL, although I'd prefer the debug console to behave more like the new Integrated Terminal feature, that's a lot to ask for the initial implementation I think.

Having the debug console effectively "be" the new Integrated Terminal would be the most ideal and ISE-like, especially if you can connect to a remote session. I really like how ISE handles this and basically if I can get ISE style ad-hoc REPL debugging in a persistent session.

If I got that with the awesome variable watching of VSCode, I would probably relegate ISE to the same level that I would use "notepad" on a server, when I don't have the better tool available.

Thanks for your consideration, you have been busting your butt on this extension and it shows, and I'm sure you see from the downloads and likes on it that it is much used and much appreciated and your efforts are far from in vain :)

**Comment by daviwil** [comment]
@JustinGrote actually your suggestion isn't very far off from what I've got in mind.  In the next release of VS Code the debugger will be able to launch a console app directly into the integrated terminal.  They've also provided an API where the extension code can launch a debug session on its own.

Putting those two features together, I'll basically be able to auto-launch a persistent debug session with powershell.exe running in the integrated terminal.  If I can bootstrap the language/debug services from within that, we'll basically have an ISE-like console experience with full script debugging for whatever you do in the session.  There are many ways in which this could go horribly wrong, but it seems compelling enough that I've got to try it :)

Thanks a lot for the kind words!

**Comment by JustinGrote** [comment]
I agree seems worth a shot. We'll see how it goes, thanks again.

**Comment by daviwil** [comment]
I just released v0.10.0 which contains an ISE-like integrated console experience.  Please give it a try and let me know what you think!

**Comment by cnavarro86** [comment]
Running 0.10.0 I was, unfortunately, not having variables persist after a debug. So, if I set $a = 1, entering $a into the terminal would not return anything. Now, the variables persist in both the terminal, and the editor. Top work!

**Comment by ahubbard** [comment]
Excellent!
