### ISSUE TITLE
Function not honoring theme 

### ISSUE THREAD

**Issue by agressiv** [PowerShell/vscode-powershell#1015]
### System Details

- Windows 10 Build 1703

Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

```
code -v
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959
```

```
$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0
```

```
code --list-extensions --show-versions
luggage66.VBScript@0.0.2
ms-mssql.mssql@1.1.0
ms-vscode.csharp@1.12.1
ms-vscode.PowerShell@1.4.1
robertohuertasm.vscode-icons@7.12.0
```

```
Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
### Issue Description

I'm trying to mimic SAPIEN's PowershellStudio Theme, which is slightly different than the ISE theme that ships with the plugin.  It doesn't appear that the Powershell plugin handles functions consistently in regards to the theme.

**entity.name.function** is defined as the color teal - #008080.  

- If I create the function, the color teal is respected.
- If I call the function, and the function uses an approved verb, it actually uses the color from **support.function** instead, which is also used by cmdlets such as _Write-Host_
- If I call the function, and the function does not use an approved verb, it defaults to the foreground color of the theme.  There's no way to override it.

![capture](https://user-images.githubusercontent.com/22016969/29898083-8fd4759c-8da9-11e7-9c86-80e69af31e86.JPG)

**Comment by gravejester** [comment]
The reason for this behavior is in how the syntax highlighting happens. It's based on a set of regex rules. The only reason we are able to assign a particular scope to the name of the function at declaration time is because the rule knows that if you start with the word _function_ then the name follows (very simplified), and we can assign a scope to it. 

It's unfortunately impossible to write a regex that knows that **Test-Function** is a function when you use it, since there are nothing we can use to reliably identify that these characters represents a custom function.

The closest solution if you want consistency is to colorize the _entity.name.function_ scope the same as _support.function_.
