### ISSUE TITLE
Language-Specific editor.* Settings Ignored When Formatting Document

### ISSUE THREAD

**Issue by NathanielArnoldR2** [PowerShell/vscode-powershell#1019]
### System Details

- Operating system name and version: Windows 10 1703 (15063)
- VS Code version: 1.15.1
- PowerShell extension version 1.4.1:
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
- Output from `code -v`:
```
1.15.1
41abd21afdf7424c89319ee7cb0445cc6f376959
```
- Output from `$psEditor.EditorServicesVersion`:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
1      4      1      0
```
- Output from `code --list-extensions --show-versions`:
```
ms-vscode.PowerShell
```

### Issue Description

[PSDocumentFormattingEditProvider.getEditorSettings](https://github.com/PowerShell/vscode-powershell/blob/c84b614b84a93502d3c16ea353cabd408bfff135/src/features/DocumentFormatter.ts#L250) does not currently consume language-specific editor settings, if defined.

I have fixed this on a local copy of the extension by replacing `"editor"` with `"powershell"` in the call to `vscode.workspace.getConfiguration`, but I am not familiar enough with the language and environment to determine if this is a proper solution.

Full replication steps with description of practical impact are in [this (rightfully) closed VSCode issue](https://github.com/Microsoft/vscode/issues/33763).

**Comment by jimp02** [comment]
I have this problem also.

In the user settings file I have: 
    "editor.insertSpaces": false,

Then a powershell configuration override with:
    "[powershell]": {
        "editor.insertSpaces": true
    },

When I select "Format Document" in the context menu, the file it formats with tabs.
The powershell configuration override setting is ignored.

**Comment by tillig** [comment]
I don't know if it ties in here, but if you have `.editorconfig` defined and [the VS Code extension for `EditorConfig` installed](https://github.com/editorconfig/editorconfig-vscode) you'll see the VS Code editor correctly figures out tab type/size but the formatter here doesn't.

**Comment by tylerl0706** [comment]
Thanks for the info!
 
To @NathanielArnoldR2, I think you're almost right with that change from `"editor"` to `"powershell"`. If you did something like this, we could better handle situation where a user has it set for their `editor` but not `PowerShell` AND the situation where a user has it set for `PowerShell` but not `editor`:

> If we don't get a value for this field in the "powershell" editor config, lets check in "editor" editor config for the value and use that

It should be relatively trivial to implement if you'd like to take a crack at it, @NathanielArnoldR2!

**Comment by Ash258** [comment]
Anyone got quick fix to bypass it temporary, until official fix?

**Comment by tillig** [comment]
I've just started learning about VS Code extension writing and I think the solution here will be:

- In `sendDocumentFormatRequest` [the `vscode.TextEditor` for the document is already retrieved](https://github.com/PowerShell/vscode-powershell/blob/4ecaf57f0b581fecb5f9dbf08aa15db9e0560176/src/features/DocumentFormatter.ts#L219)
- Pass that editor [when the `getEditorSettings` is called](https://github.com/PowerShell/vscode-powershell/blob/4ecaf57f0b581fecb5f9dbf08aa15db9e0560176/src/features/DocumentFormatter.ts#L249)
- [In `getEditorSettings`](https://github.com/PowerShell/vscode-powershell/blob/4ecaf57f0b581fecb5f9dbf08aa15db9e0560176/src/features/DocumentFormatter.ts#L312) use `textEditor.options.insertSpaces` and `textEditor.options.tabSize` to obey the current editor window's settings instead of getting the global settings directly. This should allow language-specific overrides and EditorConfig stuff to function.

I'll see if I can come up with a PR for this.

**Comment by tillig** [comment]
Submitted a PR. Tested locally, I can get EditorConfig and on-the-fly settings overrides per editor window to take effect. Pretty simple fix.

**Comment by SydneyhSmith** [comment]
Closing as the PR has been merged..thanks for the fix @tillig!!
