### ISSUE TITLE
Import-Module SQLPS throws exception related to PowerShell Editor Services version

### ISSUE THREAD

**Issue by toddbrownmcis** [PowerShell/vscode-powershell#109]
Import-Module : The current Windows PowerShell host is: 'PowerShell Editor Services' (version 0.4.2.264). The module 'C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\SQLASCMDLETS\SQLASCMDLETS.psd1' requires a minimum Windows PowerShell host version of '1.0' to run.At C:\Program Files (x86)\Microsoft SQL 
Server\120\Tools\PowerShell\Modules\SQLPS\SqlPsPostScript.ps1:8 char:20

**Comment by rkeithhill** [comment]
Hmm, seems like the SQLPS module is misbehaving by relying upon the $Host.Version instead of $PSVersionTable.PSVersion.  That said, seems like we should just bump our host version up to 1.0 to avoid this issue.

**Comment by ctrlbold** [comment]
I added a SQLPS Connect Item for this issue. Kirk Munro provided a very simple solution. Please upvote on Connect.

https://connect.microsoft.com/SQLServer/feedback/details/2444595

**Comment by daviwil** [comment]
Since this is an issue with their module I'll go ahead and close this.  I'd prefer not to bump our host version to 1.0 just to suit their module :)  Let me know if it seems their issue won't be fixed since I definitely don't want you to be blocked from using this module.

**Comment by ctrlbold** [comment]
To my knowledge, the SQL Server team hasn't updated the SQLPS module in years, so we're [pushing to get it open sourced](http://bit.ly/ossqlps). This is an incredibly easy fix (one line in one .ps1 file) so if it does go OS, it will be one of the first things we address.

**Comment by KirkMunro** [comment]
@daviwil: This issue should be used as leverage to get the SQL team to fix this in their 2016 release. There is no risk in the change because it's just a bug in the metadata they have in a module manifest.  If they comment out one manifest attribute that they shouldn't have added in the first place and that doesn't buy them anything whatsoever, the bug will be fixed.  If you could reach out to someone in their group to point out how this impacts other Microsoft products to see if it can be fixed, that would be great.  I could have fixed and closed this issue in less time than it took me to write this comment. :)

**Comment by KirkMunro** [comment]
@daviwil: I suppose it is worth mentioning that the fix for this could be done post RTM, via a simple, manual edit to the appropriate psd1 file.  Even though that manifest is signed, since code signatures are ignored on manifests (core PowerShell issue), the change can be made by individuals looking to use SQLPS without risk (which is good to know anyway since this is what would have to be done to existing versions of SQLPS).  I wouldn't bump your version whether the SQL team fixes this in 2016 or not, deferring to a workaround that could be easily scripted (an extension for VS code could even auto-detect and correct it automatically) and pestering the SQL team to get their bug fixed at the same time.
