### ISSUE TITLE
PSScriptAnalyser PSUseDeclaredVarsMoreThanAssignments check for wildcards

### ISSUE THREAD

**Issue by damusic2me** [PowerShell/vscode-powershell#1133]
### System Details

- Operating system name and version: Win 10
- VS Code version:1.19.0
- PowerShell extension version:5.1
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
1.19.0
816be6780ca8bd0ab80314e11478c48c70d09383
x64
$pseditor.EditorServicesVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
1      5      1      0
code --list-extensions --show-versions
ms-vscode.PowerShell@1.5.1
$PSVersionTable
``PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1`

### Issue Description
*PS Script Analyzer
When Debugging, i get the following reproducible warnings:  
[PSScriptAnalyzer] The Variable 'Hotfix1'is assigned but never used. (PSUseDeclaredVarsMoreThanAssignments) (50, 1)

This is incorrect:  
The variable is this:  
$Hotfix1=[PSCustomObject]@{
	"ID" = "KB2919442";
	"URL" = "https://download.microsoft.com/download/D/6/0/D60ED3E0-93A5-4505-8F6A-8D0A5DA16C8A/Windows8.1-KB2919442-x64.msu";
	"TYPE" = "PreReq"
	}

And the assignment is here:  
$hotfixtemp=get-variable -include hotfix*

Apparently PSUseDeclaredVarsMoreThanAssignments specifically checks for variable name, and doesn't take in account wildcards. 
Not a show stopper, but my professional autism dislikes Yellow warnings, and i.m.o. this is a correct way of dynamically combining arrays in Powershell
For the rest of the plugin i must thank You all for all the time and effort put in to this, it feels rather solid and mature to work with.


I am experiencing a problem with...

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by SydneyhSmith** [comment]
@damusic2me I am going through some older issues and am wondering if you are still running into this issue with the latest update, thanks!

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.

**Comment by rjmholt** [comment]
Looking over this, this is definitely a [PSScriptAnalyzer issue](https://github.com/PowerShell/PSScriptAnalyzer/issues/new/choose).

However, this is expecting PSScriptAnalyzer to be able to work out an assignment using `Get-Variable`. `Get-Variable` is not statically analysable at all (you could do `Get-Variable ((& ./myscript.ps1) + "Banan$a" + $env:HELLO)` and there would essentially be no way whatsoever to determine the output of that without running it).

Even PowerShell itself throws its hands up in the air when you use `Get-Variable` -- all kinds of optimisations have to be thrown out because there's no way to statically determine it in general. (Read this as: you should avoid `Get-Variable` whenever possible).

So despite us not owning this, I would suspect it's a by-design/wontfix. The solution is either to use the variable syntactically by name (`$Hotfix1`) or turn off variable analysis with a settings file.
