### ISSUE TITLE
when pressing Tab on PowerShell Terminal it shows irrelevant & unknown  file names where as CMD works correctly 

### ISSUE THREAD

**Issue by vishalmamidi** [PowerShell/vscode-powershell#1143]
### System Details

- Operating system name and version: Windows 10 build 15063.786
- VS Code version: 1.20.0 insider
- PowerShell extension version: 
- Output from `$PSVersionTable`:

```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

I am experiencing a problem with...

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by rkeithhill** [comment]
We're going to need a bit more info to try to repro this.  In VSCode there is the regular `PowerShell` integrated terminal that is provided by VSCode.  This extension, also provides a `PowerShell Integrated Console`.  

![image](https://user-images.githubusercontent.com/5177512/34496319-4e17563c-efb6-11e7-9bdd-12bb8cbf32ac.png)

In which of these two are you experiencing a tab-completion issue? Also, can you provide an example of what doesn't tab-complete?  For example, I'm in dir `C:\Windows` and type `Syst<tab>` and I get these options as I cycled through the tab list (instead of the expected System, System32, system.ini, etc).

**Comment by vishalmamidi** [comment]
i was using 1st one,  for example i press tab some times instead of getting Example.java, some times i got /.Example.java  some times it got strange names those named files were not there in my folder,
i wondered that those files from from System32 may be

**Comment by SydneyhSmith** [comment]
Closing as this is the PowerShell terminal and not the integrated Console so this issue is in VSCode and not the PowerShell extension
