### ISSUE TITLE
Off annoying beep sound

### ISSUE THREAD

**Issue by munrocket** [PowerShell/vscode-powershell#1207]
When I using the VS Code with "terminal.integrated.shell.windows" set to powershell.exe and deleting characters with backspace there is a high-pitched, old-school sound warning when there are no more characters to delete back. It would be wonderful if there is a setting to disable that sound by default. Because it's very annoying and difficult to off.

You can lisen this [sound](https://dl.dropboxusercontent.com/u/10976481/vscode-sound.wav) 

VSCode Version: Code 1.20.1 (f9d0c68, 2017-02-09T00:26:45.394Z)
Shell version: Shell 1.7.9
OS Version: Microsoft Windows [Version 10.0.16299.248]

My solution after 15 minutes of googling:
1) run `cmd.exe` as administrator
2) `echo Set-PSReadlineOption -BellStyle None >> C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.Powershell_profile.ps1`
2)  `powershell Set-ExecutionPolicy RemoteSigned`

**Comment by rkeithhill** [comment]
As you've found this is a feature of the GitHub.com/lzybkr/psreadline project.  I suggest you file an issue on that project.  In fact, the "terminal.integrated.shell.windows" works (and will behave the way you describe) without the PowerShell extension installed.  I'm closing this since there is nothing that the PowerShell extension does to contribute to this issue.  If you feel this is incorrect, feel free to re-open this issue.
