### ISSUE TITLE
Variables incorrectly marked as not used

### ISSUE THREAD

**Issue by si1ic0ngh0st** [PowerShell/vscode-powershell#1367]
Issue Type: <b>Bug</b>

When a variable is declared/set, but then used within single quotes, it gets marked as unused.  While this is normally correct, some PSProviders (Active Directory) require variables to be used within single quotes.  In this case, the variable is expanded/used, but VSCode markes it as unused.

example script:
$userName = "JSmith"
$adUser = Get-ADUser -filter 'SamAccountName -eq $userName'

Extension version: 1.7.0
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (9.77GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rjmholt** [comment]
@si1ic0ngh0st Thanks for opening an issue!

That looks like an implementation detail of the `Get-ADUser` cmdlet, where it uses PowerShell's dynamic scoping to expand variables manually based on template strings (which seems like a strange feature, but I imagine there's a reason for it).

*PowerShell* itself isn't expanding that variable - which is what PSScriptAnalyzer is complaining about. `Get-ADUser` is manually doing that string templating by using PowerShell's dynamic scope rules, I suspect by picking apart the AST of the filter argument, meaning it's impossible to statically analyse to determine not to fire this rule (PSScriptAnalyzer has the impossible job of trying to statically analyse a very dynamic language, but it does its best).

So the bottom line is that there's no way in general for PSScriptAnalyzer to solve a problem like this in general, since it won't know until runtime that a variable is used in a lower dynamic scope. But the AD cmdlets may be a common enough scenario that PSScriptAnalyzer should give them special treatment.

I'm going to close this issue, because we don't actually handle PSScriptAnalyzer in this repo. Please open a new issue in the [PSScriptAnalyzer repo](https://github.com/PowerShell/PSScriptAnalyzer/issues/new/choose).
