### ISSUE TITLE
Can't redirect PowerShell Itegrated to PowerShell(customized version)

### ISSUE THREAD

**Issue by SilverknightMel** [PowerShell/vscode-powershell#1377]
### System Details
    Operating system name and version: Windows 2016
    VS Code version: 1.24.1
    PowerShell extension version: 1.7.0
    Output from $PSVersionTable:

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Copy / paste the following commands into the PowerShell Integrated Console, and paste the output here:

code -v
$pseditor.EditorServicesVersion
code --list-extensions --show-versions
$PSVersionTable
```

### Issue Description

I am experiencing a problem with Terminal. Due to obvious difference (quite bit!!) between ISE and vscode on how to judge empty read-host input and few other issues, we really would like to use default ConsoleHost to replace PowerShell Integrated Console which comes with PowerShell extension. 
Regardless how many times I customize User settings to like below

 "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "git.autofetch": true,
    "window.zoomLevel": 0,
    "powershell.powerShellExePath": "C:\\WINDOWS\\sysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe",
    "powershell.powerShellDefaultVersion": "C:\\WINDOWS\\sysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\sysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe"

how how many times I overwrite JSON configuration for Powershell to 
![image](https://user-images.githubusercontent.com/21030199/41688944-8d88aeb4-7531-11e8-8004-14dec1039781.png)

in fact, I do get two terminal 
PowerShell and PowerShell integrated Console. However, as long as I press F5 to execute a PS1 file, system always switch to PowerShell integrated as terminal. We are not able to run any scripts from vscode without risking different result. 

This is pretty big for me as we not sure whether we have to debug again on ISE after we finish vscode. 
Any advice? 

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by tylerl0706** [comment]
Hi @SilverknightMel. Sorry for your frustration. In this case, it's the PowerShell Integrated Console that gives the debugging and language editing features to VSCode.

In other words, you cannot use the regular PowerShell console with the VSCode debugger because the regular PowerShell.exe (or pwsh.exe) ConsoleHost does not have the proper hook ins needed that are present in the PowerShell Integrated Console.

I'm going to close this considering it's not possible but I would really appreciate it if you could open all the issues for any differences in behavior between the ISE and the PowerShell Integrated Console. We really want to close the gap between those two...

Keep in mine, the PSIC is due for an overhaul with this issue: #535 which will enable `PSReadLine` in the console! That should close the gap quite a bit 😄
