### ISSUE TITLE
Missing intellisense

### ISSUE THREAD

**Issue by ghost** [PowerShell/vscode-powershell#139]
Actual behavior vs expected behavior

![webmethod](https://cloud.githubusercontent.com/assets/5916875/14467022/3853b46c-008e-11e6-9745-901181fb54d5.png)

Method here is missing intellisense. Just a minor inconvenience, but it would be nice to see what types method supports here.

More troubling is this

![console](https://cloud.githubusercontent.com/assets/5916875/14467064/6eaa0390-008e-11e6-9949-b57c63d78653.png)

No intellisense support for .NET? Likewise, WriteLine() doesn't seem to output console.

**Comment by rkeithhill** [comment]
Hmm, I see completion items for the `-Method` parameter but they are mixed in with a bunch of other unrelated completion items:

![vscode_paramvaluecompletion](https://cloud.githubusercontent.com/assets/5177512/14478721/948ddeb4-00d5-11e6-8bcf-c0c7b43f0d2f.png)

So that could be improved.  

RE .NET, there is Intellisense for non-static members. Try `"".<Ctrl+Space>`.  What we are missing is Intellisense for static members.  That will be fixed in the next release of this extension.

**Comment by ToddBowles** [comment]
I'm using 0.11.0 and I seem to be missing Intellisense of Static Methods too.

I've had them working before, on a different machine.

The version of vscode that its not working in is 1.10.2, running in portable mode (so downloaded via the zip) out of my OneDrive.

Specifically, if I type in [System.IO.DirectoryInfo]:: I get the following intellisense:

![image](https://cloud.githubusercontent.com/assets/6036235/24319130/7b00ca70-115e-11e7-8b42-ddc9d51aeabe.png)

**Comment by tylerl0706** [comment]
What's interesting about what @ToddBowles is seeing is that the results are the same in VSCode and powershell.exe.

It's only in the ISE where the results are different

**Comment by rjmholt** [comment]
I'm currently getting pretty good completions for the initial example when I press <kbd>Ctrl</kbd>+<kbd>Space</kbd> in 1.9.0. Is this still an issue for people?

The .NET completions are now tracked in https://github.com/PowerShell/vscode-powershell/issues/1356.
