### ISSUE TITLE
install-vscode

### ISSUE THREAD

**Issue by jkavanagh58** [PowerShell/vscode-powershell#1478]
Will there be a new install-vbscript version in PSGallery for this new "recommended" version. Not to mention why are you recommending it? 
I just finished a script for a complete install of VSCode with extensions and modules... install-vscode allowed the argurments for version, architecture and installing extensions all in one...

**Comment by joeyaiello** [comment]
Could you provide a little more context on your question? E.g. what do you mean by `install-vbscript`? Or the "recommended" version? Is there something you're seeing on the VS Code Marketplace?

**Comment by rjmholt** [comment]
@tomlarse You've reminded me that I should add to the release notes given my recent changes to the `master` script.

The project URI field should be updated to `master` as well.

The script hasn't been republished since it hasn't really been a priority and it requires some time investment to get it signed properly. For the script can be obtained from https://raw.githubusercontent.com/PowerShell/vscode-powershell/master/scripts/Install-VSCode.ps1.

**Comment by SydneyhSmith** [comment]
Closing as this has been solved https://www.powershellgallery.com/packages/Install-VSCode/1.3
