### ISSUE TITLE
.NET types doesn't work in many cases.

### ISSUE THREAD

**Issue by savpek** [PowerShell/vscode-powershell#148]
Heres example how  intellisense fails to support .net types.

First working version and then modified failing one.

![pshell-bug](https://cloud.githubusercontent.com/assets/481896/14587786/ee622f22-04c1-11e6-9be9-af680597e6aa.gif)

vscode: 1.0
extension: 0.5.0

**Comment by daviwil** [comment]
Hmm, will investigate this, thanks for reporting!

**Comment by rkeithhill** [comment]
As a workaround for the NewGuid case,  try this: type`[System.Guid]` and then press <kbd>Ctrl</kbd>+<kbd>Space</kbd>.  You should see this:

![vscode_staticmembercompletion](https://cloud.githubusercontent.com/assets/5177512/14588535/f84a3fa4-0488-11e6-9ac4-d4b97e2e2f30.png)

This will work a little better in 0.6.0 however @daviwil we currently do not provide parameter/arg Intellisense for .NET methods like we do for PowerShell commands AFAICT e.g.:

![vscode_commandparameters](https://cloud.githubusercontent.com/assets/5177512/14588556/8e83e286-0489-11e6-8e96-d0aad65fe1a8.png)

That would be really nice to have for .NET methods where you show various method overloads e.g. 1/6 instead of command parameter sets.

**Comment by daviwil** [comment]
That's true, we don't yet provide parameter hints for .NET methods.  I was looking for the signature string in the IntelliSense but it seems you just need to get to it a different way, as shown by your screenshot.

One thing that surprised me was that `[System.` doesn't get a completion list.

**Comment by daviwil** [comment]
Looks like the completion problems you were having are fixed in 0.6.0 which is releasing soon.  I'll close this bug as soon as that is released.

We're tracking the lack of .NET method signature help here: https://github.com/PowerShell/PowerShellEditorServices/issues/13.  I'm going to start working on that in the next couple of releases since it will be a great productivity boost.

**Comment by daviwil** [comment]
0.6.0 is now released!  Let me know if you run into any further trouble.
