### ISSUE TITLE
Error in enter-pssession with windows 7 in ISE console

### ISSUE THREAD

**Issue by chrisduda** [PowerShell/vscode-powershell#1618]
Am having an issue when trying to enter a pssession to a windows 7 computer.  Works fine in windows 10 as well as a powershell console in VSC but not in the powershell integrated console.  When using a powershell command prompt or powershell ISE, I can remote in with those as well.  When I try to use the powershell integrated console in VSC, I get this error:

```
Enter-PSSession : Cannot bind parameter 'ErrorAction'. Cannot convert value "Ignore" to type "System.Management.Automation.ActionPreference" due to invalid enumeration values. Specify one of the following enumeration values and try again. The possible
enumeration values are "SilentlyContinue, Stop, Continue, Inquire".
At line:1 char:1
+ Enter-PSSession -ComputerName ihe-ws1423
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-Module], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.ImportModuleCommand
```

I've tried using an `enter-pssession` and specifying an error action but the same thing comes up.  It only happens on the VSC integrated console.  This is happening on two computers in the same way.  Again, the odd thing is that if I just have a powershell console in VSC, it works fine, just the integrated console doesn't allow it.  I'm using the following:

```
Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Better comments 2.0.3
Dracula official 2.15.0
Powershell 1.9.0
vscode-icons 7.28.0
```

Thanks.

**Comment by rjmholt** [comment]
Hi @chrisduda, thanks for opening an issue.

Can you please supply your PowerShell version information. You can find information on how to do this [here](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) or in the text when opening a new [bug report](https://github.com/PowerShell/vscode-powershell/issues/new?template=Bug_report.md).

I can't find anywhere in the codebase where we would be doing anything with `New-PSSession` that would preclude `-ErrorAction Ignore` and that value was introduced in PowerShell v3, which is the lowest PowerShell version we support.

**Comment by rjmholt** [comment]
Sorry, it actually looks like the problem is coming from [here](https://github.com/PowerShell/PowerShellEditorServices/blob/80920c60cf1bdcbd488e1e22066a83e3dc7b0723/src/PowerShellEditorServices/Session/Capabilities/DscBreakpointCapability.cs#L95-L99).

However, the would only occur when trying to remote into a PowerShell v2 process, which we don't support and is [deprecated](https://blogs.msdn.microsoft.com/powershell/2017/08/24/windows-powershell-2-0-deprecation/).

**Comment by chrisduda** [comment]
Thanks for the response.  Here's my version info:

PS C:\scripts> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.407
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.407
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

I'm running windows 10 enterprise 1803.  I'm running powershell 5.1, however the end-user computer most likely is on 2.0.  Most of our windows 7 systems haven't had any need for a powershell update.  As I stated, it's only giving me an issue in the integrated console, it works in the console terminal session that opens along with the integrated console as well as running it in the native powershell command window and powershell ISE.

**Comment by rjmholt** [comment]
The Integrated Console is the only context managed or touched by the PowerShell extension. The native PowerShell terminal and the ISE are separate projects. The Integrated Console is quite different to both because we reimplement a lot of the functionality to allow a shared context between the editor and the console below.

Because the remote session becomes the source of all our core features (intellisense, script analysis, code lenses), our compatibility promise extends to the remote session. So the problem here is that we go to detect DSC capabilities in the remote session and `-ErrorAction Ignore` fails since it's not supported in v2. While we could fix that issue, it would risk regressions elsewhere and would imply an ongoing support for PowerShell v2 that we just can't provide.

Since PowerShell v2 is deprecated and we don't have the resources to support it, I think the best course of action is either to upgrade to a newer PowerShell version (as suggested in the deprecation notice) or to use the ISE for scenarios that involve PowerShell v2.
