### ISSUE TITLE
Catch autocomplete error

### ISSUE THREAD

**Issue by Denver80211** [PowerShell/vscode-powershell#1654]
### Issue Description

"catch" triggers undesired autocomplete

#### Expected Behaviour

type catch, it STAYS catch

#### Actual Behaviour

In a try catch block, when I type "catch", [hit return or space] the IDE replaces catch with Copy-Patch -not desired

**Comment by rjmholt** [comment]
Thanks for opening an issue @Denver80211, do you think you could attach a gif or similar of the issue you're experiencing?

**Comment by Denver80211** [comment]
New to github here.. hopefully this works?  I press entter at the end of
typing catch and it's replaced with copy-patch

[image: image.gif]

**Comment by Denver80211** [comment]
``

**Comment by rjmholt** [comment]
That works!

We get completions from PowerShell itself currently, see https://github.com/PowerShell/vscode-powershell/issues/703.

While VSCode is what provides the actual completion UI, we might find a way to improve your settings so the suggested completion doesn't clobber what you're trying to type.

**Comment by Denver80211** [comment]
OK thanks.  it's odd.. the interface clearly understands the keyword (it
colors the text correctly) but then clobbers it all the same, as you say

**Comment by rjmholt** [comment]
The highlighting is provided in the client by [the EditorSyntax project](https://github.com/PowerShell/EditorSyntax). The completions are provided by the backend running a PowerShell process.

Highlighting is essentially a bunch of scoped regexes, but completions are much more involved because they are influenced by machine state. You'll get highlighting even if you uninstall the PowerShell extension.

Traditionally, PowerShell won't offer completions on keywords, just like completers for other languages tend not to. Either way, we don't currently have any mechanism other than PowerShell itself to add completions in -- the best recommendation is to add it in PowerShell and us get it downstream.
