### ISSUE TITLE
French characters are not displayed correctly when debugging

### ISSUE THREAD

**Issue by neothoms** [PowerShell/vscode-powershell#1680]
System Details Output
```
- Operating system name and version : Windows 10 Version 10.0.17763 Numéro 17763
- VS Code version  : 1.30.1
- PowerShell extension version : 1.10.2
- Output from `$PSVersionTable`
### VSCode version: 1.30.1 dea8705087adb1b5e5ae1d9123278e178656186a x64

### VSCode extensions:
hbenl.vscode-firefox-debug@1.7.3
heaths.vscode-guid@1.4.0
MS-CEINTL.vscode-language-pack-fr@1.30.2
ms-vscode.csharp@1.17.1
ms-vscode.PowerShell@1.10.2
msjsdiag.debugger-for-chrome@4.11.1
robertohuertasm.vscode-icons@8.0.0


### PSES version: 1.10.2.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1



<!-- PowerShell output from above goes here -->


```

### Issue Description

I am experiencing a problem with French characters wich are not correctly reproduced on VS Integrated  console but it may also apears with any special characters from any language.

#### Expected Behaviour

When I type the following command directly in the console everything is displayed correctly.
write-host "---- These are french characters : âà ç éèë ïï and they are not correctly displayed ----"

![image](https://user-images.githubusercontent.com/11428292/50698969-ce83a580-1046-11e9-8255-6271a1029d87.png)

#### Actual Behaviour

But if I use the powershell extension and type the same command in a .ps1 file encoded in UTF8 I have this incorrect result : 

![image](https://user-images.githubusercontent.com/11428292/50699110-2c17f200-1047-11e9-87c1-b6c5f3392345.png)

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by SydneyhSmith** [comment]
@neothoms thanks for reporting this! The command you are running is provided by VSCode and it just pastes the path of the open file into the active terminal followed by an "enter" key, so it is likely that the issue is on the VSCode side: looks related to this issue https://github.com/Microsoft/vscode/issues/31366

**Comment by ubidev** [comment]
Seems to be affecting variables definition too...
1- In vscode I get this error:
![01](https://user-images.githubusercontent.com/14218601/50987588-06239f00-14d8-11e9-972d-b906f74de8e9.jpg)

2- When I open the same fine in ISE, I get this:
![02](https://user-images.githubusercontent.com/14218601/50987625-25bac780-14d8-11e9-85a0-5a4b7879c459.jpg)

3- I then correct/save/run the same file in ISE with this result:
![03](https://user-images.githubusercontent.com/14218601/50987653-3e2ae200-14d8-11e9-811e-e4a8dcf4f7ba.jpg)

4- Finally, back in vscode,it displays like this, but runs ok !!!
![04](https://user-images.githubusercontent.com/14218601/50987677-53a00c00-14d8-11e9-85fb-c0ac63d558ef.jpg)

Hope this helps

**Comment by rjmholt** [comment]
This is an encoding problem that occurs with file handling between VSCode and the ISE. Please see https://github.com/PowerShell/vscode-powershell/issues/1351 and https://github.com/PowerShell/vscode-powershell/issues/1306#issuecomment-403231035.

There's not much we can do from the extension's perspective -- the solution lies in ensuring you have VSCode, the ISE and PowerShell all configured to use UTF-8. The encoding problems you're seeing are (for example) due to the é being encoded in UTF-8 as `0xC3 0xA9` and then being interpreted as CP-1252/ISO-8859-1/latin-1 by PowerShell as the characters Ã© ([handy reference](https://www.i18nqa.com/debug/utf8-debug.html)).

You need to set PowerShell's encoding to UTF-8, or VSCode's to ISO-8859-1, and make sure the ISE is also configured to do the same.

Because PowerShell defaults to CP-1252 for things like this, but VSCode defaults to UTF-8, you will need to make a conscious choice as to how you encode your scripts in source control and how you configure the encoding in your editors and PowerShell. If they get out of sync, they may all try to re-encode files and cause problems again.

**Comment by ubidev** [comment]
I understand your points. 
I was always impressed since ISE v3 being able to handle french and spanish strings out to console output without a hitch. even localized variable names is not a problem.
Do you know how to configure then vscode to default to the same character support as ISE then? (UTF-8 with BOM) when creating new powershell files?

Thanks in advance

**Comment by rjmholt** [comment]
> ISE v3 being able to handle french and spanish strings out to console output without a hitch. even localized variable names is not a problem

That's probably because [all the required characters lie within the CP-1252 codepage](https://en.wikipedia.org/wiki/Windows-1252). The problem now is that the upper half of CP-1252 characters are incompatible with UTF-8.

It looks like you *are* creating the PowerShell files as UTF-8, but PowerShell is trying to read them as CP-1252. So you need to change the encoding in the integrated terminal. This is probably best done in your profile.

For setting editor encodings, see https://github.com/PowerShell/vscode-powershell/issues/1308#issuecomment-386197479.

**Comment by rjmholt** [comment]
It sounds like it might be helpful for us to summarise this in a document.

**Comment by ubidev** [comment]
coz usually if I follow the following workflow the french characters are always displayed ok at every step, even in source control
- Creation: ISE or Notepad++ (set to UTF-8 with BOM)
- Edits: VSCODE
-Publish: GITLAB then VSTS

thanks for the very appreciated enlightenment and have a great day

**Comment by ubidev** [comment]
I totally agree :)

**Comment by ubidev** [comment]
Unfortunately, I can't do that. If I use UTF8 in ISE/VSCODE/NPP for example, all hell breaks loose at execution: variables contaning accented characters break, display strings too. 

The only way it works flawlessy at each step of the way on my computers/vms set to Windows english plus french lang pack is if I create the powershell scripts in "UTF8 with BOM" (default behavior in ISE, manual config in NPP)
Then execution, console outputs, gui popups, git/vsts repo contents displays perfectly

**Comment by rjmholt** [comment]
> Unfortunately, I can't do that. If I use UTF8 in ISE/VSCODE/NPP for example, all hell breaks loose at execution: variables contaning accented characters break, display strings too.

That's because without the BOM PowerShell defaults to CP-1252. If you set PowerShell to use UTF-8, this shouldn't happen:

```powershell
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```

In PowerShell 6+, it should default to UTF-8 anyway and you won't hit any of these problems out of the box.

**Comment by ubidev** [comment]
I'll give this a try. If I end up not having to ask the customers to change their default powershell behavior, that would be great...
Thanks a zillllion ;-)

**Comment by SydneyhSmith** [comment]
Add this to your VSCode settings `"files.encoding": "utf8bom"`
With this set it will encode your files as UTF-8 with BOM and Windows PowerShell should "just work"

**Comment by ubidev** [comment]
Thanks alot Sydney, will try this asap. :)

Now, I'd also like to try the solution provided by @rjmholt but can't seem to make it work: I pated the line in a test script created in vscode in UTF-8, but I get the same errors and display gibberish :(

**Comment by rjmholt** [comment]
> where should I put this line? in my script, in the powershell profile?

The best place is probably in your profile. Otherwise, just execute it in your integrated terminal session. Let use know if that doesn't work though.

**Comment by ubidev** [comment]
Hi !
Here is what I'm getting as a result of copy/pasting verbatim that line in each application specific ps profile. It won't even run in ISE.
![vscodeconsole](https://user-images.githubusercontent.com/14218601/51075273-57a66800-1657-11e9-8e5b-8ebd5dc7b2ab.jpg)
![psconsole](https://user-images.githubusercontent.com/14218601/51075275-5ecd7600-1657-11e9-827d-b312070f99dd.jpg)
![iseconsole](https://user-images.githubusercontent.com/14218601/51075276-62f99380-1657-11e9-9c9a-6d3e08e6aaac.jpg)
