### ISSUE TITLE
Single quotes inside Pester test names prevent tests from running

### ISSUE THREAD

**Issue by sobjornstad** [PowerShell/vscode-powershell#1725]
## Issue Description ##

The "Run Tests" or "Debug Tests" option appearing above Pester Describe blocks does not work when the string contains a single quote. vscode-powershell appears to be neglecting to escape them when issuing a shell command to run the tests.

```
Describe "This test works" {
    It "follows the basic principles of logic" {
        $true | should be $true
    }
}

Describe "This test's broken" {
    It "follows the basic principles of logic" {
        $true | should be $true
    }
}
```

Working test yields:

```
Describing This test works
 [+] follows the basic principles of logic 56ms
Tests completed in 56ms
Passed: 1 Failed: 0 Skipped: 0 Pending: 0 Inconclusive: 0
```

And broken test:

```
The string is missing the terminator: '.
At line:0 char:0
```

I'm still using version 3.4.0 of Pester, if that matters. The tests run fine when I call `Invoke-Pester` in the console.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.15063 |
| VSCode | 1.30.2|
| PowerShell Extension Version | 1.10.2 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.15063.1563|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.15063.1563|
|BuildVersion|10.0.15063.1563|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|1.10.2|

(All other extensions manually disabled to confirm no interference)

**Comment by TylerLeonhardt** [comment]
We're probably not escaping the string in the Describe block properly. Thanks for opening this!

**Comment by rkeithhill** [comment]
Yup.  Using line numbers to run/debug individual tests is looking better and better. :-)

**Comment by bergmeister** [comment]
PR #1713 will enable this scenario when the new Pester version 4.6.0 is installed but I submitted PR #1729 to fix it for older versions as well.

**Comment by AlexanderSehr** [comment]
One comment from my side: It's still possible to resolve this error if your test looks somewhat like this 

`It '[<moduleFolderName>] The template file should contain required elements: `schema`, `contentVersion`, `resources`' -TestCases $deploymentFolderTestCases {`

After some trial and error it turned out the issue is the <code>`'</code> at the end of the test name.

If I add an artificatial space in the end it works:

`It '[<moduleFolderName>] The template file should contain required elements: `schema`, `contentVersion`, `resources` ' -TestCases $deploymentFolderTestCases {`

Fyi ;)
