### ISSUE TITLE
Session crashes too often

### ISSUE THREAD

**Issue by potatoqualitee** [PowerShell/vscode-powershell#1780]
Issue Type: <b>Bug</b>

when editing dbatools commands my session crashes like every 5 minutes.

Extension version: 1.11.0
VS Code version: Code - Insiders 1.32.0-insider (507312a3e3b34b084b467dfd983263bc7c9d87e0, 2019-03-06T10:06:48.833Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (4 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|10.00GB (4.47GB free)|
|Process Argv|--folder-uri file:///c%3A/github/dbatools|
|Screen Reader|no|
|VM|100%|

</details>

**Comment by potatoqualitee** [comment]
will have stream where it crashes linked after the livestream is done

**Comment by TylerLeonhardt** [comment]
Thanks for the info! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by potatoqualitee** [comment]
aww i thought it did :( @wsmelton what happened D:

**Comment by corbob** [comment]
@potatoqualitee you submitted this through the help menu right? I think the one for the logs is provided by the extension and best to search the command palette for "Bug Report":

![Search Bug Report in Command Palette](https://user-images.githubusercontent.com/30301021/54049600-c6a0c880-4191-11e9-9aa3-621b42266c6b.png)

That being said, in my experience this will likely grab the wrong logs if the extension crashed and you relaunched it (because you're not in a new session)

**Comment by potatoqualitee** [comment]
i did @corbob. I saw the way to do logging, got overwhelmed then decided i'd turn off my other extensions and powershell has been good for an hour 👍
