### ISSUE TITLE
More frequent PowerShell Preview releases?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#1792]
**Summary of the new feature**

When you've announced PowerShell Preview being available I thought you will treat it with the more frequent release schedule. Is it possible to treat it as such? I know there is Insiders version but you have to do it manually and it's more or less tricky to be on Insiders versioning. With Preview you would get sooner verification of features and people can easily switch between main and preview release.

**Comment by TylerLeonhardt** [comment]
We would have had a sooner release but there were a few things we wanted to get in.

Then we heard PSScriptAnalyzer was going to ship soon and now we are waiting for that.

**Comment by PrzemyslawKlys** [comment]
I understand that. But I don't mean current release, but overall the process for Preview? Are we expecting it to get updates every week/month or at the same intervals as the main release? 

Just to be clear. This is a purely informational issue. I don't want to enforce anything. I would like to just know what are the plans for Preview extension.

**Comment by TylerLeonhardt** [comment]
Like stable releases, Preview will be ad hoc. Preview and stable will likely occur together in the beginning. This is because Preview has PSReadLine support which is not ready for Stable yet.

Once PSReadLine makes it into Stable, then Preview will take on more of what you're suggesting - a Preview that releases before Stable to ensure it's... well... stable.
