### ISSUE TITLE
Deleting Terminal Session Causes Error

### ISSUE THREAD

**Issue by HJLBX** [PowerShell/vscode-powershell#1796]
Issue Type: <b>Bug</b>

Deleting the PowerShell terminal session generates a message that the terminal has closed in error:

https://imgur.com/a/Z7II1Pu

Extension version: 1.11.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.92GB (6.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by TylerLeonhardt** [comment]
The PowerShell Integrated Console process is used for all editor features (hence "integrated" 😊) if you delete it, you're basically killing the PowerShell extension with it.

If you really don't want to see the terminal, hit the `x` button, not the trash can button. This will keep the terminal (and the PowerShell extension) running in the background.

**Comment by HJLBX** [comment]
So why doesn't the terminal crash when I delete a cmd.exe or non-integrated powershell (powershell.exe) terminal using the delete button ?

It only happens when using the "intergrated" powershell.

**Comment by rkeithhill** [comment]
Because cmd.exe or the non-integrated PowerShell terminals are in no way intergrated with the PowerShell extension for VSCode.  Basically, the PowerShell language service (which provides intellisense, code analysis, code lens, help comment completion, etc) and the PowerShell debug service both run **in** the PowerShell Integrated Console process.  Ideally, we'd find a way to indicate to VSCode that this particular terminal window should not be closed, just hidden.
