### ISSUE TITLE
Profile loading should be enabled by default

### ISSUE THREAD

**Issue by dfinke** [PowerShell/vscode-powershell#180]
Using 0.6.0. I created a test.ps1, typed in `notepad $profile` hit `F8` and added `ipmo mymodule` that is in `C:\Program Files\WindowsPowerShell\Modules`. That module is set up to add a ps cmd to the editor.

I run vs code, open a ps1, navigate to the PowerShell cmds in the palette, it is not there.

Do an `F8` on `ipmo mymodule` in the open ps1, navigate and the cmd shows up.

Here is my log.

![image](https://cloud.githubusercontent.com/assets/67258/15268505/f7e9ed08-19ae-11e6-9f78-24b4e5c75154.png)

**Comment by daviwil** [comment]
Can you put this setting in your user settings and reload VS Code?  I need to see the verbose logs to tell what's going on there:

`"powershell.developer.editorServicesLogLevel": "Verbose"`

After that you should be able to see in the logs where your profile script is being executed.  If you can paste that bit and any errors that come after it we might be able to figure it out.

**Comment by daviwil** [comment]
In case anyone else runs into this issue, it turns out that this is due to profile loading not being enabled by default in this release of the extension.  I had done this on purpose to ensure that there were no widespread issues when everyone updated.  To enable profile loading, add this setting to your User Settings file in VS Code:

```
"powershell.enableProfileLoading": true
```

I'll keep this bug open to remind myself to set the default to true for the next update.
