### ISSUE TITLE
Variables not detected as used if only used for splatting

### ISSUE THREAD

**Issue by JeremyTBradshaw** [PowerShell/vscode-powershell#1820]
Issue Type: <b>Bug</b>

If I define this variable:

```
$MyParameters = @{
   Path = .\Desktop
   Recurse = $true
}
```
...and then if I only ever use it like this:

`Get-ChildItem @MyParameters`

I'm given the warning for variable is declared more than used.

Extension version: 1.11.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.38GB (1.67GB free)|
|Process Argv|C:\Users\jerem\OneDrive\Desktop\ImportingCSVsIntoSQLv1-Import.ps1|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by JeremyTBradshaw** [comment]
While I'm here, is there a way to make the PSScriptAnalyzer rule selections (and deselections) last after closing/reopening VS Code?

**Comment by rkeithhill** [comment]
I recommend using a PSSA settings file.  Call it something like `PSScriptAnalyzerSettings.psd1` and in your workspace settings, add this entry:
```
    "powershell.scriptAnalysis.settingsPath": "./PSScriptAnalyzerSettings.psd1",
```
This is really the way VSCode wants you to do workspace-specific settings like this IMO.

Please submit this bug to the PSSA project at https://github.com/powershell/scriptanalyzer since that project provides this feature in the extension.  And if you haven't updated to version 1.18.0 of PSSA, give that a try.  The bug "might" be fixed in that version.

**Comment by JeremyTBradshaw** [comment]
Thanks, I will do that (the settings file)
