### ISSUE TITLE
PowerShell (stable) gone from VS Code marketplace

### ISSUE THREAD

**Issue by RafaelKoch** [PowerShell/vscode-powershell#1874]
### Issue Description

I can no longer find PowerShell extension on VS Code marketplace. Only PowerShell Preview can be found.
I am using a vs code workspace in which PowerShell is one of the recommended extensions. As of today I am warned that the extension can no longer be found on the marketplace, which appears to be true. 

My last installed Version is 1.12.0. In this repo the last stable appears to be 1.12.1. So I assume something went wrong publishing. 

#### Expected Behaviour

Stable Extension can still be found on marketplace.

**Comment by rkeithhill** [comment]
> I assume something went wrong publishing.

Unfortunately, it did.  Hopefully it will be fixed in the next few days.

**Comment by bergmeister** [comment]
https://twitter.com/TylerLeonhardt/status/1116842475966963712?s=19

**Comment by TylerLeonhardt** [comment]
Thanks @bergmeister + @rkeithhill. Here's my official text from the tweet:

"
Unfortunately, due to user error with publishing, I've had to temporarily unpublish the #PowerShell stable extension from the @code marketplace until I can reach the team to help mitigate the issue.

Thank you for your patience. I will get to the bottom of this.

In the meantime, you can fetch the 1.12.1 release off of GitHub here:
https://github.com/PowerShell/vscode-powershell/releases/tag/v1.12.1 …

Or grab the PowerShell Preview extension from the marketplace.

Thanks again.
"

I've found the right team, I'm almost certain. Just awaiting a response. I will keep you all updated.

**Comment by chuanjiao10** [comment]
1         download   https://github.com/PowerShell/vscode-powershell/releases/download/v1.12.1/PowerShell-1.12.1.vsix

2 close vscode.
3 open powershell.exe
4 code --install-extension e:\your_download_folder\PowerShell-1.12.1.vsix

**Comment by rjmholt** [comment]
This was resolved this weekend. The latest stable PowerShell extension in the marketplace is 1.12.1.
If your stable (non-preview) extension version is higher than this, you should uninstall and reinstall.
