### ISSUE TITLE
Powershell Integrated Console - loops (preview 2.0.2)

### ISSUE THREAD

**Issue by AlexBillon07** [PowerShell/vscode-powershell#1879]
Issue Type: <b>Bug</b>

The Powershell Integrated Console can't be used.

It loops (cf gif)
 ![Integrated Powershell Console loops](https://cjoint.net/?1y8fubfkulblodxx8hv7)

Extension version: 2.0.2
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (9.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
vscode-edifact|DAX|0.5.1
xml|Dot|2.4.0
gitlens|eam|9.6.0
reg|ion|0.0.2
powershell-preview|ms-|2.0.2
vscode-hexdump|sle|1.7.2
poor-mans-t-sql-formatter-vscode|Tao|1.6.10
vscode-icons|vsc|8.5.0
vsc-jsonsnippets|wmo|0.1.4

</details>

**Comment by rjmholt** [comment]
Hi @AlexBillon07, this is likely a known issue in PSReadLine 2.0.0-beta.3 occurring with non-US keyboards (https://github.com/lzybkr/PSReadLine/issues/854#issuecomment-477851836). We're waiting on the next PSReadLine release for a fix.

It's likely you're experiencing this behaviour now because 2.0.0-preview.3 has PSReadLine turned on by default.

To turn it off, you should be able to set:

```json
"powershell.developer.featureFlags": []
```

Alternatively you can install PSReadLine 2.0.0-beta.4 from [here](https://github.com/PowerShell/vscode-powershell/issues/1570#issuecomment-475730802) and try that out.

Deduplicating this issue to https://github.com/PowerShell/vscode-powershell/issues/1570.
