### ISSUE TITLE
Not alerted when using an incorrect sign to separate typed array elements

### ISSUE THREAD

**Issue by larssb** [PowerShell/vscode-powershell#188]
Hi....

I'm an avid user of Visual Studio Code. Today I had an issue where getting an element at a certain index in a typed array failed. As I was troubleshooting this issue I found that it was simply because I had used a '.' (dot) instead of a ',' (comma) to separate the elements when I defined the typed array variable.
Okay, that is a clear mistake on my part, as I thought about it I would have loved to be alerted by the vscode-powershell extension in Visual Studio Code. Could this be something that is added in an upcoming version?
- I have the latest version of VS Code (v1.1.1).
- My version of vscode-powershell is: v0.60 --> updated today and the issue is still there.

TO REPRODUCE:
1. open vscode
2. create ps1 file
3. 
   `
   $array = "hej", "hej2", "hej3". "Hej4"
   $array
   --> prints = hej & hej2
   `

EXTRA NOTES:
- Also happens in Ps Shell. With PowerShell v5 Build 10586
- If I do '$array = 1, 2. 4' --> I get an '...unexpexted token '4' in expression or statement.....'. So it seems to be an issue with [Strings]

Looking forward to hear from you. Thank you in advance.

**Comment by daviwil** [comment]
Hi @larssb, thanks for the report.  It seems that for whatever reason, the PowerShell engine considers this to be valid syntax because it does not report any parser errors when it encounters this line.  For the PowerShell extension in VS Code to show an error there, the PowerShell engine would need to report it upon parsing the code.

The only other way we might be able to show an error in this case is by creating a PSScriptAnalyzer rule but I think this sort of low-level syntax issue is best left to the PowerShell parser.

I'd recommend filing a UserVoice issue to ask for some type of syntax error in this case since it affects users of PowerShell in any context, not just in editors.  You can find our UserVoice site here:

https://windowsserver.uservoice.com/forums/301869-powershell/category/148044-powershell-engine

**Comment by larssb** [comment]
Shared the idea on UserVoice. For reference here is a link: [https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/20579914-catch-illegal-syntax-in-array-definition](url)

**Comment by tylerl0706** [comment]
I'm going to close this now since it's an issue with the PowerShell parser itself and we can use the uservoice to track the issue. Thanks!
