### ISSUE TITLE
Feature Request: Azure Functions Debug - Split Terminal Option

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/vscode-powershell#1941]
**Summary of the new feature**

When debugging with Azure Functions Powershell, you have to toggle back and forth on the terminal window between the Azure Function Host task window and the integrated terminal.

**Proposed technical implementation details**

VSCode has API calls for splitting the terminal. If an option is set (e.g. powershell.SplitTerminalOnAzureFunctionDebug), then it should split the function host start and the integrated console so the result looks like below:

![image](https://user-images.githubusercontent.com/15258962/57101559-5c5e5d00-6cd6-11e9-9147-9aff712dea8e.png)

**Comment by TylerLeonhardt** [comment]
Thanks @JustinGrote!
@EricJizbaMSFT this is an interesting ask - I feel like this is pretty generic to all languages in the sense that we could have a config option in the Azure Functions extension to use split-view instead of adding a new terminal window?

**Comment by EricJizbaMSFT** [comment]
Hmm the hard part is that `func host start` is specified as a `preLaunchTask` in your `.vscode/launch.json` (or a dependnecy of the `preLaunchTask`). After we create the project, we don't control when or how `func host start` is run - it's just using VS Code's default debug/task system.

The only way we could affect this is if there's some VS Code setting we could write to new projects - are you aware of one? For example, we write down `"debug.internalConsoleOptions": "neverOpen",` to show the terminal by default instead of the debug console.

@JustinGrote could you describe what you use the terminal for and why you switch back and forth? I'm wondering if there are other ways we could solve this problem. For example, if you only use the terminal to copy function urls, you might be able to use a tree view of the local project that we're currently working on. It'll look something like this:
![Screen Shot 2019-05-03 at 10 19 02 AM](https://user-images.githubusercontent.com/11282622/57154139-fed91780-6d8c-11e9-8f72-ad1b9e258e8c.png)

The idea is that you could copy http urls or execute timer triggers the same way it's possible for remote Azure functions today.

**Comment by TylerLeonhardt** [comment]
@EricJizbaMSFT for PowerShell, we don't use the "Debug Console" - we just use the regular terminal since PowerShell handles debug prompts in the console already:

![image](https://user-images.githubusercontent.com/2644648/57157507-bc680880-6d95-11e9-9d97-5a258d7374d2.png)

**Comment by JustinGrote** [comment]
@EricJizbaMSFT it's primarily when working with the local function core tools runtime, when I run/debug a function I want to see the "streaming logs" next to my interactive debug console that is attached.

There is the "group" option in the tasks.json to automatically group things side by side, so if the func start task can be "grouped" with the interactive console (maybe by pre-specifying the interactive console group in the extension code, of which I have no idea if that is possible), then that solves the issue. Then it can be a feature flag whether that group attribute gets added to the console or not, for user personal preference.

**Comment by EricJizbaMSFT** [comment]
@TylerLeonhardt I gave you permission to the vscode-azurefunctions repo - can you transfer this issue over to that repo?

**Comment by SydneyhSmith** [comment]
@EricJizbaMSFT looks like we cant transfer this issue cross-org, have you opened an issue to track this on the Azure Functions side?

**Comment by EricJizbaMSFT** [comment]
https://github.com/microsoft/vscode-azurefunctions/issues/1311

**Comment by rjmholt** [comment]
Thanks!
