### ISSUE TITLE
Improve syntax coloring definition to meet the standards of PowerShell ISE, Visual Studio

### ISSUE THREAD

**Issue by v-pavanp** [PowerShell/vscode-powershell#199]
I compare VSCode coloring with Visual studio with different themes and observed that the cmdlet, parameter name and values are not following correct pattern.
Actual: 
1. With Light (Visual Studio) and Dark+ (Default Dark) themes the PS comdlet , parameter and parameter value are displaying in the same color.

![vslighttheme](https://cloud.githubusercontent.com/assets/17735796/15461182/8ec3af4c-206d-11e6-908a-989b2bf363f8.png)

2. When multiple parameters are provide with the command then they are displaying in the different color.
Exp: In the below screenshot you can see -class and -computer is displaying in different color and Win32_OperatingSystem and localhost are displaying in different color.
![image](https://cloud.githubusercontent.com/assets/17735796/15461045/0fdc8eb6-206c-11e6-89aa-bd88d2d189bf.png)
Expected: Cmdlet, parameter and value should be display in three different colors and should be consistent in the script file same like visual studio.
![image](https://cloud.githubusercontent.com/assets/17735796/15461179/87087c92-206d-11e6-8241-2b960c924324.png)

**Comment by daviwil** [comment]
Hey Pavan, the problems you see with VS Code's syntax highlighting for PowerShell come from the TextMate syntax definition we borrowed from Sublime Text which is based purely on regular expressions.  We won't be able to keep 100% consistency with Visual Studio and the PowerShell ISE because VS Code does not allow us to implement a custom classifier based on the PowerShell parser.

That said, we need to improve the syntax definition to be more consistent with what users expect.  We've got a plan to take over maintenance of the TextMate syntax definition that we use so that we can improve the quality of its colorization, it just may take a little while before we get to it.

**Comment by gravejester** [comment]
I'd love to help out with this one @daviwil.

**Comment by daviwil** [comment]
That'd be fantastic!  Would love some help on that.  I need to create a GitHub repo for the common syntax coloring definition used across VS Code, Sublime Text and Atom.  I'll get that started today.

**Comment by gravejester** [comment]
Nice, let me know when you have it set up and I'll start taking a look at it. :)

**Comment by vors** [comment]
Excellent, lets do it!
For sublime side of things see https://github.com/SublimeText/PowerShell/issues/148
