### ISSUE TITLE
PowerShell External Window runs x86 and not x64

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/vscode-powershell#205]
I added this to my settings.json file
 "externalTerminal.windowsExec": "powershell"

it works and I get a PowerShell session. But I am running a 64 bit system and I think I'm getting a 32bit PowerShell session. I disabled my profiles and opened a new PowerShell session outside of code. Looking at the current PowerShell process path shows this:
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

But when I do the same thing in VSCode, the PowerShell process path looks like this:
C:\WINDOWS\SysWOW64\WindowsPowerShell\v1.0\powershell.exe

That's a 32bit process. Task manager also shows a 32bit version of PowerShell.

**Comment by daviwil** [comment]
Hey Jeffery, I must have misunderstood what you meant earlier, now I see what you mean.  If you're launching the external console it's definitely going to launch the 32-bit version since VS Code is running as a 32-bit process.  I don't think there's much you or the VS Code team can do about this because it's Windows that decides to launch the 32-bit powershell.exe when it's spawned from a 32-bit process.

The alternative is to not use the `externalTerminal` feature but to use the PowerShell console integration from the PowerShell extension by either using F8 (the Run Selection command) or by running your script in the debugger.  With the F8 option you can't actually type commands into a console, you'd have to type something into the editor and use F8 to run it.  This is pretty unfortunate but currently necessary because VS Code doesn't give us the ability to provide a persistent console experience.

That's changing pretty soon though, the 1.2.0 release of VS Code will make it easier for us to provide a fully integrated console experience.  I expect this experience to improve a lot over the next few months.

**Comment by jdhitsolutions** [comment]
This makes more sense now. I assumed VSCode was a 32bit app which is why I get a 32bit PowerShell console. Of course, what I really want, like many others, is that integrated console experience like the ISE. I use the ISE daily because of all of the customizations I've made. But I can see where VSCode offers an attractive alternative.

**Comment by daviwil** [comment]
Yep, I'm constantly bugging the VS Code team to give me what I need to make an ISE-equivalent console experience possible.  It's a really high priority.  Definitely keep checking back in on the extension over time to see where we're at on that.  Once I get sufficient documentation going it'll be easier to tell what level of interactive console experience we have at any given point.

**Comment by gerane** [comment]
You could easily make this into an editor command. I deal with this when
deploying software with kace. You could just detect if running in a 32 bit
process and launch powershell via sysantive. I'm not able to show you an
example atm.

This should be an issue for vs code really. By default, I feel it should be
using 64 bit terminals if on a 64 bit machine.

That brings up another question. Will the internal terminal be a 32 bit
process as well?

**Comment by daviwil** [comment]
Actually, yeah, I may have misspoke.  Invoking powershell.exe from the sysnative path would work, we use that right now for the "Open in PowerShell ISE" command:

`c:\Windows\Sysnative\WindowsPowerShell\v1.0\powershell.exe`

This overrides Windows' SysWOW64 path selection in 32-bit processes.

@gerane: Which internal terminal, the one provided by PSES?  That defaults to 64-bit and you have to change a setting to make it use 32-bit.

**Comment by gerane** [comment]
I typed this on my phone, so you might want to double check everything.

https://gist.github.com/gerane/dde06b9de33c4a86a770b292a385b502

**Comment by gerane** [comment]
Could easily make it open to current project dir with $context added in.

**Comment by tylerl0706** [comment]
I wonder if this issue changes at all since the addition on the Integrated Console.

**Comment by rkeithhill** [comment]
The original issue:
```
"externalTerminal.windowsExec": "powershell"
```
launching 32-bit PowerShell from 32-bit VSCode is really a VSCode issue.  Anyway, how do you even get VSCode to launch an "external" terminal these days?  And with PSIC you can pick your bitness. I say close it.

**Comment by tylerl0706** [comment]
Sounds good!
