### ISSUE TITLE
Stop loading of powershell.exe terminal and only have integrated terminal

### ISSUE THREAD

**Issue by iyoumans** [PowerShell/vscode-powershell#2093]
I would like a setting that prevents the "powershell.exe" terminal from opening and only opens the "PowerShell Integrated Console" terminal. Having the two consoles trying to start at the same time causes some issues for me due to profile settings. All the settings.json settings seem to be for controlling the integrated terminal only.

**Comment by corbob** [comment]
🤔 I don't think it's possible to stop the integrated terminal from loading, but a few things that might help could be setting `terminal.integrated.shell.windows` to something else (like `cmd.exe` 😬 ), or set `terminal.integrated.shellArgs.windows` to include `-NoProfile` so that PowerShell doesn't load any profiles.

**Comment by rjmholt** [comment]
Related to https://github.com/PowerShell/vscode-powershell/issues/1968

**Comment by SydneyhSmith** [comment]
@corbob is correct, vscode opens the powershell.exe, and it would be dangerous for us to trash the terminal since we do not have the full context of what could be running in that terminal (for example a user could have a long-running script), so I am going to go ahead and close this issue. @iyoumans let us know if the above provided workarounds do not help address your issue.
