### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by PSVortex** [PowerShell/vscode-powershell#2170]
PowerShell VSCode extension has 'v2019.5.0' as version. It should have semantic version 2.x.x or so.

I'm seeing this merge: https://github.com/PowerShell/vscode-powershell/pull/1979 but it looks like it doesn't work as intended.

**Comment by SydneyhSmith** [comment]
@PSVortex thanks for opening this issue, we made the decision to switch date versioning for a number of reasons-- see the original issue here: #1880

Unfortunately, the previous version scheme was a huge pain point that burned us due to limitations imposed by vscode and so the current versioning scheme is in affect for this reason. Let me know if this helps clarify, or if you are running into another issue related to this versioning choice, thanks!

**Comment by PSVortex** [comment]
@SydneyhSmith Understod, good resons.
