### ISSUE TITLE
Watch window shows incorrect attribute value for an XmlElement node with attribute "name"

### ISSUE THREAD

**Issue by Line40** [PowerShell/vscode-powershell#2203]
Issue Description
=====

If an XmlElement node has an attribute by the name of ```name```, the Watch window does not show the attribute value, but the node name instead.

To reproduce, run the attached script, and add ```$node.name``` to your watch window while doing so. The Write-Host commands in the script should provide insight.

[Check-Issue.zip](https://github.com/PowerShell/vscode-powershell/files/3641285/Check-Issue.zip)

![grafik](https://user-images.githubusercontent.com/5467899/65413154-0e670480-ddf1-11e9-86ad-550b00046371.png)

 Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.38.0|
| PowerShell Extension Version | 2019.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.145|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.145|
|BuildVersion|10.0.18362.145|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.6|
|cpptools|ms-vscode|0.25.1|
|gradle-language|naco-siren|0.2.3|
|openhab|openhab|0.5.1|
|powershell|ms-vscode|2019.5.0|
|python|ms-python|2019.9.34474|
|python-extended-snippets|tushortz|0.0.1|
|remote-wsl|ms-vscode-remote|0.39.2|
|vscode-language-pack-de|MS-CEINTL|1.37.5|
|vscode-markdown-paste-image|telesoho|0.12.2|
|xml|DotJoshJohnson|2.5.0|

**Comment by TylerLeonhardt** [comment]
@Line40 Does it also repro if you do: `$node.Name` (notice the capitalization)

**Comment by Line40** [comment]
@TylerLeonhardt Yes, it's the same with ```.Name```. I should have added this info, sorry. 

Funny side note: The Powershell console itself does the exact opposite. In the console, I get the xml attribute value wether I use $node.name or $node.Name, so Powershell effectively hides the ```Name``` property of the ```XmlElement``` class.

**Comment by rjmholt** [comment]
> Funny side note: The Powershell console itself does the exact opposite.

I wonder if it's the opposite, or just undefined behaviour in PowerShell not specifying which you get.

Similar to:

```powershell
Add-Type @'
public class Duck
{
    public string Quack { get; } = "Quack";

    public string QUACK { get; } = "QUACK";
}
'@

$x = [Duck]::new()
$x.Quack
```

In this case, it's not defined which property PowerShell accesses.

Or similarly

```powershell
$x = @{
    A = 'Hi'
    B = 'Bye'
    Keys = 'Ha!'
}
$x.Keys
$x.get_Keys()
```

In the console I actually get `$xml.SelectNodes('/images/image').Name` giving me `Name is NOT image`.

You can differentiate the two by calling the proper API for each:

```powershell
$node = $xml.SelectNodes('/images/image')

$node.get_Name() # 'image'
$node.GetAttribute('image') # 'Name is NOT image'
```

Because this is a collision in the PowerShell property names, this is essentially undefined behaviour in PowerShell, and something I don't think we can fix.

Please let us know if the suggested solution doesn't work.

**Comment by Line40** [comment]
I think a basic requirement of any Watch window in a debugger should always be to show the exact same evaluation result as if I ran the evaluated expression in the program code (in this case the powershell console or a powershell script). 

So I don't really think the solution is not satisfactory.

PS: I mean, come on, really? I assume anyone who reads these bugs works with one or the other IDE... How would you like it if your debugger shows different values for variables than your program via debug output?

**Comment by rjmholt** [comment]
So I did a bit more investigation here in case we're doing anything strange. Internally, we [just invoke the expression given in the watch window](https://github.com/PowerShell/PowerShellEditorServices/blob/85d53303f6bc5119d85c412c5d2d4000dcb49a5c/src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs#L958-L962). So we're not doing anything special.

I tried this out in the stable and preview extensions with both PowerShell 5.1 and PowerShell 7.0 and got the same result in all cases, where the watch window agreed with the invoked PowerShell:

![node](https://user-images.githubusercontent.com/7009879/65788513-120bcb80-e110-11e9-8f34-6c7666b7fe6c.JPG)

So it might be worth updating your extension version to 2019.9.0 and maybe try the preview version if the issue continues.

Ultimately though, this occurs because `XmlElement` defines both an `Item[String]` property and a `Name` property, and `$node.Name` could mean either in PowerShell. If you want your script to work without ambiguity, you should write either `$node.get_Name()` or `$node.get_Item('name')`.
