### ISSUE TITLE
Provide F8 Action button on the menu in VS Code, just like the F8 in the PowerShell ISE Menu bar.

### ISSUE THREAD

**Issue by kprpg** [PowerShell/vscode-powershell#2215]
**Feedback Request:** Like in the PowerShell ISE, can you please provide a “Run Selection (F8)” button, right in the menu in VS code also (see below picture)? This will ease the transition of the workflow one uses in ISE, and enable more easy switch from ISE to Code. 
 
 
![F8-Code](https://user-images.githubusercontent.com/11221387/65838508-8342ae80-e2c9-11e9-866f-faeb958adc98.png)

Thanks,
Girish.

**Comment by SydneyhSmith** [comment]
@kprpg thanks for opening this issue, today in VSCode we have F8 run selection capability directly from the key board, available via a "right click" or available via the command palette "Ctrl+Shift+P"--just to clarify is your feature requests for a button directly in the UI?

**Comment by TylerLeonhardt** [comment]
@SydneyhSmith I had @kprpg open this issue - my bad for not clarifying that. 

Yes they are asking for an actual button.

Also, it's possible 😄 using a feature called ["menus" in VS Code's extension API](https://code.visualstudio.com/api/references/contribution-points#menu-example).

I _think_ we just need to add one of these to the package.json for F8 and then we should be good to go.

Since it's not too critical (because of other work having higher priority), let's go ahead and mark this up-for-grabs.

**Comment by SydneyhSmith** [comment]
@TylerLeonhardt thanks-- I will update the labels!

**Comment by rjmholt** [comment]
> Also, it's possible

😮
