### ISSUE TITLE
"VSCode Insiders" should auto-optin to "vscode-powershell-insiders"

### ISSUE THREAD

**Issue by PSVortex** [PowerShell/vscode-powershell#2236]
**Summary of the new feature**

When someone is using "VSCode Insiders", he should should auto-optin to "vscode-powershell-insiders" version of the extension.

**Comment by rjmholt** [comment]
This would have to be handled by VSCode rather than in the extension, but I suspect it might not be possible:

- No PowerShell extension is installed by default in VSCode
- Because of the way VSCode handles things, the preview extension is a different extension all together
- VSCode's closest logic for opting in to an extension is probably the filetype recommendations
- I'm not sure how those work, but I suspect it's a static file (like JSON) which doesn't have any infrastructure to change it conditionally from VSCode Insiders to VSCode (one's just downstream from the other)
- To make this achievable from the extension itself, we'd need to radically change our client architecture

However, this is just conjecture based on experience with the code bases and their structure. I'll mark this as up-for-grabs in case anyone wants to have a proper look into this.

**Comment by TylerLeonhardt** [comment]
Here's the discussion on the VS Code side about this:
https://github.com/microsoft/vscode/issues/80178

**Comment by TylerLeonhardt** [comment]
I think we should really close this and point folks to that issue as we, the PowerShell extension, can't really do anything.

**Comment by SydneyhSmith** [comment]
Thanks Tyler, will close this request as being tracked by microsoft/vscode#80178

**Comment by rjmholt** [comment]
[Looks like this is possible on VSCode's side](https://github.com/microsoft/vscode/issues/80178#issuecomment-541235509)
