### ISSUE TITLE
Invoke-Sqlcmd works from PS command prompt. not from VSCode

### ISSUE THREAD

**Issue by gbritton1** [PowerShell/vscode-powershell#232]
Running VSCode 1.4 with PowerShell Extension 6.1,  When I try Invoke-Sqlcmd in the debugger I get:

> Invoke-Sqlcmd : Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 
> 4.0 runtime without additional configuration information.
> At D:\PS\Get_UAT_Results.ps1:39 char:1
> + Invoke-Sqlcmd -ServerInstance "crsddvcp04tbv,3341" -Database testetl  ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Invoke-Sqlcmd], FileLoadException
>     + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
> 

When I run the same command in the Powershell command line or ISE, it works just fine.

What am I missing?

**Comment by daviwil** [comment]
Hey @gbritton1, check out @rkeithhill's comment on this issue:

https://github.com/PowerShell/vscode-powershell/issues/189#issuecomment-220065601

This should resolve the issue for you.  Since #189 already tracks the issue I'll go ahead and close this one.  If it turns out that this fix doesn't work for you, let me know and I'll try to investigate.  Thanks!

**Comment by gbritton1** [comment]
Thanks!  That fixed it!!

**Comment by daviwil** [comment]
Just released an update to the extension and I included the necessary files so you shouldn't have to do this fix again :)
