### ISSUE TITLE
Your .NET version is too low. Upgrade to net452 or higher to run the PowerShell extension.

### ISSUE THREAD

**Issue by Firmbyte** [PowerShell/vscode-powershell#2349]
I've installed same version of Code on each Node of a 2 Node cluster, on one Node it's fine, on 2nd I get this error: "Your .NET version is too low. Upgrade to net452 or higher to run the PowerShell extension."
I've uninstalled Code and reinstalled, verified .Net 4.5 is installed.

```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.34014
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\firmbyte> (Get-ItemProperty -Path 'HKLM:\Software\Microsoft\NET Framework Setup\NDP\v4\Full' -ErrorActi
on SilentlyContinue).Version -like '4.5*'
True
```

**Comment by rjmholt** [comment]
Hi @Firmbyte, thanks for opening an issue. Are you running the preview extension or the normal one?

If it's the normal/stable extension, it may be that your .NET installation, while .NET 4.5, is not .NET 4.5.2 or higher. The stable PowerShell extension only supports .NET 4.5.2 or higher, since [lower versions of .NET 4.5 are EOL](https://devblogs.microsoft.com/dotnet/support-ending-for-the-net-framework-4-4-5-and-4-5-1/).

You can check which particular .NET 4.5 version you have installed with `Get-ItemPropertyValue 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full' Release` and comparing the value to [the table here](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#minimum-version).

With the coming move to a netstandard library in January, the PowerShell extension will have a new .NET Framework minimum version of 4.6.1 (due to constraints imposed by the netstandard implementation), so it's recommended you ensure you have at least .NET 4.6.1 installed.

**Comment by Firmbyte** [comment]
Thank you very much for the fast response and yep, you're right, old version:  4.5.51641
Other Node in the Cluster has 4.8.03761
