### ISSUE TITLE
CosmosDB module does not load in integrated console

### ISSUE THREAD

**Issue by eosfor** [PowerShell/vscode-powershell#2362]
Error message

![image](https://user-images.githubusercontent.com/9363027/70764478-8ff17300-1d0c-11ea-9b58-c39dc99c6e2b.png)

versions

![image](https://user-images.githubusercontent.com/9363027/70764392-56206c80-1d0c-11ea-9dce-2762222418a0.png)

**Comment by eosfor** [comment]
However, in regular pwsh it works with no problems

**Comment by rjmholt** [comment]
Can you drill into the error to find out what assembly is causing issues? Something like `$error[0] | fl * -force`. In PS 7 you should be able to use `Get-Error`.

We hit a similar issue in https://github.com/PowerShell/vscode-powershell/issues/2292 and this will be fixed in the next preview, which we're planning to release on Monday. You should be able to pick up a build from CI [here](https://dev.azure.com/powershell/vscode-powershell/_build/results?buildId=41180&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3) if you want to test it now.

**Comment by eosfor** [comment]
it does not show much, unfortunately

![image](https://user-images.githubusercontent.com/9363027/70824795-da6c0180-1d97-11ea-97de-5f16454ceb80.png)

**Comment by eosfor** [comment]
![image](https://user-images.githubusercontent.com/9363027/70824923-2028ca00-1d98-11ea-801c-f0bfc61a74db.png)

**Comment by eosfor** [comment]
looks like the update you pointed me out to works. I will be looking at it throughout the day. Thank you

**Comment by rjmholt** [comment]
How about `$error[0].Exception | fl * -force`?  Anyway, the important part is that this should be solved.

**Comment by SydneyhSmith** [comment]
Marking as resolved since we have fixed this issue in the latest version of the preview extension, but will re-open if this issue persists. Thanks!
