### ISSUE TITLE
Rogue closing square brackets not detected as a problem.

### ISSUE THREAD

**Issue by JeremyTBradshaw** [PowerShell/vscode-powershell#2365]
Issue Type: <b>Bug</b>

Example:

Sort-Object -Unique ObjectId]

Notice the ] above?  That won't flag any errors/warnings/squiggly lines to let us know it shouldn't be there.

Extension version: 2019.11.0
VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

**Comment by rjmholt** [comment]
`]` is a legitimate bareword string character, since it's a wildcard character. So since it's not a parse error to do `Get-ChildItem C:\Techdocs\[a-l]*.txt`, it's not a parse error to do `Sort-Object -Unique ObjectId]`.

It sounds like [you want a new PSScriptAnalyzer rule](https://github.com/PowerShell/PSScriptAnalyzer/issues/new?template=Feature_request.md). However, depending on how clever this rule tried to be it would be either simplistic to the point of not being very helpful, or require a lot of runtime type inference information and therefore not be of much use in script analysis scenarios.

Basically you'd have a rule like `PSUseValidPropertyNamesOnCmdlets` or something and it would find instances of `Sort-Object`, `Where-Object`, `ForEach-Object`, `Select-Object`, etc. where property names are passed and:

1. Just use a regex on the property names to ensure they are just alphanumeric strings (not terribly useful since it's a pretty constrained category of error that prevents)
2. Attempt some type inference and try to raise an error when a property not on the object passed in is referenced. This is hard because type information is easily lost in PowerShell and is usually dependent on runtime state. So while it's useful for completions (since there's a short distance from your current state to the type information you're pulling out), it's much less likely to work for script analysis (since most of the time after one or two lines we're not going to be able to predict the type of object very well, so we'll just need to allow everything and the rule becomes useless).

I should also note that in some cases wildcards make sense for cmdlets like this: `gci | select -Property Last*`.

So there's one last possibility that lies on a different tangent, which would be `PSUseWildcardsCorrectly` or something, which checks for wildcard syntax and tries to correct it. That would be relatively straightforward to write, you'd just need a wildcard parser and a laundry list of which parameters on which cmdlets accept wildcards and then look for those in the rule.

**Comment by rjmholt** [comment]
Anyway, point is that `Object]` is a legitimate value there:

```
 > [pscustomobject]@{ 'ObjectId]' = 123 },[pscustomobject]@{ 'ObjectId]' = 42 } | sort-object objectid]

ObjectId]
---------
       42
      123
```

But that doesn't mean it's not worth a feature request in PSScriptAnalyzer.

**Comment by JeremyTBradshaw** [comment]
@rjmholt Hi there and thanks for taking the time.  I see what you're saying and agree it's not a true issue so closing now.  I am not too concerned about it, so may not get to the tips you provided, but I do appreciate it, and will at least make sure to get them understood so your time spent on this won't be for nothing
