### ISSUE TITLE
Clear-Host causes cursor position state issues with PSReadLine

### ISSUE THREAD

**Issue by arcotek-ltd** [PowerShell/vscode-powershell#2408]
### System Details

System Details Output
```
### VSCode version: 1.41.1 26076a4de974ead31f97692a0d32f90d735645c0 x64

### VSCode extensions:
ms-vscode.powershell-preview@2019.12.0


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.771
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.771
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

Trying to get the directory of the current script using `Split-Path -Path $PSScriptRoot -Parent`.

#### Expected Behaviour
![image](https://user-images.githubusercontent.com/26305145/72173874-65104280-33d0-11ea-981b-ee4c7508c659.png)
Running the same script in ISE gives the expected result.

#### Actual Behaviour
![image](https://user-images.githubusercontent.com/26305145/72174111-de0f9a00-33d0-11ea-947e-942c52ea0170.png)

As you can see, in VSCode, the result is not the parent. It's returned the whole file.

I have tried other variations such as 
```
$RootPath = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$RootPath

# or

(Get-ChildItem -Path $PSScriptRoot).Parent
```
It always returns the full path.

### Attached Logs

Follow the instructions in the [troubleshooting docs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#logs)
about capturing and sending logs.

**Comment by TylerLeonhardt** [comment]
Ok so this is a very interesting issue. For starters:

*Your script is running properly and the `Split-Path` cmdlet is working fine*

The problem here is purely visual output and is related to the PSReadLine support in the PS Integrated Console.

To prove it to you, you can do the following things:
* hit ENTER until you start to scroll, then run the script again...
* Restart the current session...
* Enable the setting `"powershell.integratedConsole.useLegacyReadLine": true` and run it again

The bug shows up after you run `Clear-Host` so there's some state that PSReadLine & the PowerShell extension share that is not being updated properly.

**Comment by arcotek-ltd** [comment]
Thanks for the reply @TylerLeonhardt.

I'm just trying your hypothesis, however, possibly related to this and #2407, pressing `f5` has changed the prompt to:
![image](https://user-images.githubusercontent.com/26305145/72194200-aae6fe00-3404-11ea-8fb0-4c83d7e397db.png)

Anyway, as you suggested, setting `"powershell.integratedConsole.useLegacyReadLine": true` resolved the issue, however, doskey (command history) doesn't work in debug mode, yet, IntelliSense does.

**Comment by TylerLeonhardt** [comment]
Yeah the prompt change is something I've noticed when doing console debugging in PowerShell as well so that's likely an issue there.

Did you try the first suggestion? Hitting enter until it scrolls? Curious if that works for you.
