### ISSUE TITLE
Remove PSIC string in favor of 'PSCIC C:\'

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/vscode-powershell#2425]
### Issue description
Would it be possible to remove the long string in the console:
![image](https://user-images.githubusercontent.com/10828570/72709586-9245b900-3b65-11ea-870e-b29c1ea0306e.png)

and replace this:
![image](https://user-images.githubusercontent.com/10828570/72709641-a5588900-3b65-11ea-8311-babfb6c17c25.png)

with a string like `PSIC T:\Test\Brecht>`?

It would save a lot more screen space on startup and make it clear all the time what terminal users are using, even after executing some code.

### System Details

```
Version: 1.42.0-insider (system setup)
Commit: d72b2d372f5024a9193b37a3830bbbc459c0ef1b
Date: 2020-01-20T05:33:26.563Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393
```

PowerShell Preview version `2020.1.0`

**Comment by rkeithhill** [comment]
The problem with that is a lot of folks override the prompt function.  Maybe it would be better to not use the indents and extra chars.  Ah, I see the latest version of the extension has done this:

![image](https://user-images.githubusercontent.com/5177512/72750225-7e0bb700-3b79-11ea-9f6b-604b82f193e3.png)

I think it is reasonable for a host to display the host's name, particularly in this case because of the difference between normal pwsh terminals and this one.

**Comment by TylerLeonhardt** [comment]
So the prompt in the PSIC just calls the `prompt` function so I personally don't think we should have custom behavior for that.

@rjmholt changed the "logo" in an effort to call attention to the fact that you're in the Integrated Console because folks wouldn't realize that they were... And also to give it a little bit of flare.

If you want to get rid of the logo at startup, you can suppress it using this setting:

```
powershell.integratedConsole.suppressStartupBanner
```

**Comment by DarkLite1** [comment]
I like the fact that it's already smaller in the new version and that it can be suppressed. Closing this one. Thanks guys.

**Comment by rjmholt** [comment]
Yeah after toying with some possibilities, basically if you want to get rid of the banner you can use the setting @TylerLeonhardt. If you want a new banner, you should be able to just put a `Write-Host` in your `$profile` and it will show up when the PSIC starts.

**Comment by rjmholt** [comment]
Random thought to throw out as up-for-grabs: maybe there should be a way to suppress the startup banner from PowerShell too so that you can do it all in the `$profile`?
