### ISSUE TITLE
Ctrl-C and other Alt- and Ctrl- keys are ignored or wrongly interpreted

### ISSUE THREAD

**Issue by jrydval** [PowerShell/vscode-powershell#2452]
Issue Type: <b>Bug</b>

The PowerShell Integrated Console ignores some keypresses (like "Crtl-C") and some others (like "Atl-Arrows" and "Cmd-Arrows") are wrongly interpreted and shows some letters instead of doing a cursor movements on MacOS.

How to reproduce:

Type a text into PowerShell Integrated Console on MacOS and press Crtl-C. Nothing happens. Expected is termination of the input and jump to a prompt on a new line.

Type a text into PowerShell Integrated Console on MacOS and press Alt-[<-]. "b" is displayed. Expected behaviour: Move cursor to a word on the left.

Extension version: 2020.1.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (4.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjmholt** [comment]
It sounds like you're using the legacy readline, which is currently what's used in the stable extension.

The behaviours you're after come from a PowerShell module called PSReadLine, which will be brought into stable when PowerShell 7 is released next month. You'll need to use PowerShell 7 with it, since PowerShell 6 has a bug in it that compromises the PSReadLine experience. If you'd like to try this out now, you can install PowerShell 7.0.0-rc.2 and the `powershell-preview` extension (uninstalling the `powershell` extension at the same time).

I'll deduplicate this to https://github.com/PowerShell/vscode-powershell/issues/535. Please let me know if this doesn't sound accurate and we can reopen.

**Comment by TylerLeonhardt** [comment]
Theres's more to this. Maybe @Tyriar knows how to help... the default behavior on macOS when you hold Alt and hit any other key is to display special characters. I had to disable this in iTerm2... the same thing probably has to happen in VS Code but I'm not sure how off the top of my head.

**Comment by jrydval** [comment]
Thank you.

PowerShell-Preview works fine!
