### ISSUE TITLE
Start-EditorServices.ps1: [System.Random]::new() errors in Windows  with Powershell 4

### ISSUE THREAD

**Issue by geoffian** [PowerShell/vscode-powershell#248]
Running on Windows 8 (Powershell v3) & Windows 2012r2 (Powershell 4) from logs:

powershell.exe started --
    pid: 8304
    exe: C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
    bundledModulesPath: C:\Users\BB45210\.vscode\extensions\ms-vscode.PowerShell-0.7.0\modules
    args: C:\Users\BB45210\.vscode\extensions\ms-vscode.PowerShell-0.7.0\scripts\Start-EditorServices.ps1 -EditorServicesVersion "0.7.0" -HostName "Visual Studio Code Host" -HostProfileId "Microsoft.VSCode" -HostVersion "0.7.0" -BundledModulesPath "C:\Users\BB45210\.vscode\extensions\ms-vscode.PowerShell-0.7.0\modules" -LogLevel "Verbose" -LogPath "C:\Users\BB45210\.vscode\extensions\ms-vscode.PowerShell-0.7.0\logs\1471588439-EditorServices.log" 

ERROR: Method invocation failed because [System.Version] doesn't contain a method 
ERROR: named 'new'.

**Comment by crchad** [comment]
I'm seeing the same issue since updating to 0.7 this morning. Win 8.1 & PS 4, e.g. 
ERROR: Method invocation failed because [System.Random] does not contain a method 
ERROR: named 'new'.
At C:\Users\USERNAME\.vscode\extensions\ms-vscode.PowerShell-0.7.0\scripts\Star
t-EditorServices.ps1:103 char:1
+ $rand = [System.Random]::new() 

Also includes several others e.g.:
ERROR: Method invocation failed because [System.Random] does not contain a method 
ERROR: named 'new'.
ERROR: Method invocation failed because [System.Version] does not contain a method 
ERROR: named 'new'.
ERROR: Method invocation failed because [System.Net.Sockets.TcpListener] does not 
ERROR: contain a method named 'new'.

**Comment by philkloose** [comment]
I'll just add that I'm seeing the same issue on Win7x64 (PowerShell v3).

**Comment by daviwil** [comment]
Hi guys, thanks for the report!  There's definitely an issue on older Windows systems, I'll try to ship an update early next week to address this.

In the meantime you can remove the installed PowerShell extension and download one of the older releases from our [releases page](https://github.com/PowerShell/vscode-powershell/releases).  Just extract the previous release package into `$HOME\.vscode\extensions` and restart VS Code.

**Comment by daviwil** [comment]
Just shipped a new release with a fix for this issue!  Let me know if it resolves everything for you.
