### ISSUE TITLE
PSScriptAnalyzer not running when no settings file present

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/vscode-powershell#2489]
From https://github.com/PowerShell/vscode-powershell/pull/2484.

Currently under investigation

**Comment by rjmholt** [comment]
Looking into this, I've tried to reproduce the issue but I get the default experience.

In the logs I have the following entry:

```
2020-02-24 11:35:05.143 -08:00 [INF] PSScriptAnalyzer settings file not found. Falling back to default rules
```

@bergmeister would you be able to provide more information about the repro steps for this issue?

**Comment by bergmeister** [comment]
@rjmholt I tried to clean everything: did a 'git clean -dfx' on the the vs-code  and PSES repo and made sure I had the latest changes on master. Using pwsh 7-rc2 (waiting for chocolatey to update to rc3...). Usually I also use the latest master version of pssa, I deleted that one and now use the out of box version of pssa as well. However, PSSA still does not work. OS is Windows 1909. Building using RTM version of code. NPM version is 6.3.14. I just build it the usual way by doing an `invoke-build build` in pses and then press F5 in the vscode repo and do something like typing `gci` to see a PSSA warning on it, either in a file or an unsaved in-memory file and I don't see any PSSA warnings or squiggles..

**Comment by rjmholt** [comment]
> Let me try supply some logs

Yeah I'm hoping some info will be in there. Rewriting the analysis service I added extra logging, so we should know what's going on there

**Comment by bergmeister** [comment]
[EditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4247204/EditorServices.log)
[StartEditorServices.log](https://github.com/PowerShell/vscode-powershell/files/4247205/StartEditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/vscode-powershell/files/4247206/vscode-powershell.log)

**Comment by rjmholt** [comment]
Interesting. This also contains the line:

```
2020-02-24 22:44:22.265 +00:00 [INF] Configuring PSScriptAnalyzer with rules at 'c:\Users\christoph.bergmeiste\git\choco\PSScriptAnalyzerSettings.psd1
```

**Comment by bergmeister** [comment]
The repo in question is a 6 month old version of https://github.com/chocolatey/choco
But I tried different folders, so it is not a problem specific to this repo and as I said I tried both physical files or in-memory files. Could it be because you guys run your dev env mostly on Unix systems and not Windows?

**Comment by rjmholt** [comment]
Is it possible you're starting PSES with a settings file present on the file system, but later removing it?

**Comment by bergmeister** [comment]
I don't think so, I've even tried to re-open a new folder

**Comment by rjmholt** [comment]
> Could it be because you guys run your dev env mostly on Unix systems and not Windows?

I'm almost always on Windows, both in the office and at home. My daily driver in the office is Windows 10.0.19535 (right now, I'm sure I'll get another update in the week).

I'm still not quite sure what's going on here, but if you're able to debug it you might be able to find the source of that error log (it's not one of our messages). If it's coming from a caught error, it might be somewhere where we need to include a stack trace and don't currently.

**Comment by bergmeister** [comment]
Ok.
The  situation in the debugger is quite clear, especially when reading the code as well: Due to the default setting being `PSScriptAnalyzerSettings.psd1`, the used setting path in the `TryFindSettingsFile` method already has the value of combining the workspace root with `PSScriptAnalyzerSettings.psd1`
https://github.com/PowerShell/PowerShellEditorServices/blob/c99aae37481462b3423e77852e832a9bcae96051/src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs#L287
A few lines later, the `ResolveWorkspacePath` only resolves the path without checking for its existence and therefore makes PSES use a file that does not exist.
Even looking at earlier stages where settings are being set in the internal `ScriptAnalysisSettings` class, there is no checking against whether the path actually exists and it just sets it if it resolves to a valid path
https://github.com/PowerShell/PowerShellEditorServices/blob/65bcbb17653d2e2c33bde1f0c14e9a5eff3e7c72/src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs#L103

Therefore, it escapes me how it works on your environements, you must have either a user or workspace setting defined. Let me know if that info helps, happy to do a screen share session as well in case you still cannot repro.

**Comment by rjmholt** [comment]
I agree with that analysis; thanks for looking into that.

> Therefore, it escapes me how it works on your environements, you must have either a user or workspace setting defined.

Yeah I'm not sure either. Very explicitly cleared my settings.

Testing out a fix now.
