### ISSUE TITLE
Register-EditorCommand fails due to ALC changes

### ISSUE THREAD

**Issue by Ayanmullick** [PowerShell/vscode-powershell#2495]
Issue Description
=====

I am experiencing a problem with running the below code in the Integrated terminal.

```powershell
Register-EditorCommand -Name 'RunFileInExternalWindow' -DisplayName 'Run current file in external window' -ScriptBlock { Start-Process pwsh '-File',$psEditor.GetEditorContext().CurrentFile.Path }
```

Creating as discussed with @SeeminglyScience .

Attached Logs\screenshot
=====
![image](https://user-images.githubusercontent.com/17693249/75209178-40cfb180-5743-11ea-8296-5ec38b6d70f4.png)

Environment Information
=====

Visual Studio Code
-----

<details><summary>Visual Studio Code(Click to Expand)</summary>

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18363 |
| VSCode | 1.42.1|
| PowerShell Extension Version | 2020.2.0 |

</details>

PowerShell Information
-----

<details><summary>PowerShell Information(Click to Expand)</summary>

|Name|Value|
|---|---|
|PSVersion|7.0.0-rc.3|
|PSEdition|Core|
|GitCommitId|7.0.0-rc.3|
|OS|Microsoft Windows 10.0.18363|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.0-rc.3|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

</details>

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|powershell-preview|ms-vscode|2020.2.0|
|remote-wsl|ms-vscode-remote|0.42.3|

**Comment by TylerLeonhardt** [comment]
I can repro this on macOS in PS7.

I can't repro this on macOS in PS6 though, which is interesting.

**Comment by rjmholt** [comment]
[Code for reference](https://github.com/PowerShell/PowerShellEditorServices/blob/4c12d38a3f08d92c90846fa1dbb8a71495c4ad48/module/PowerShellEditorServices/Commands/Public/CmdletInterface.ps1#L50)

**Comment by SeeminglyScience** [comment]
`Import-EditorCommand` has some too, may just want to do a sweep of all the ps1's

**Comment by rjmholt** [comment]
I'm a bit confused by this. [It looks like that's the right namespace for `EditorCommand`](https://github.com/PowerShell/PowerShellEditorServices/blob/4c12d38a3f08d92c90846fa1dbb8a71495c4ad48/src/PowerShellEditorServices/Extensions/EditorCommand.cs#L8-L14).

**Comment by SeeminglyScience** [comment]
Oh... PowerShell can't resolve any types from PSES outside of the `Microsoft.PowerShell.EditorServices.Hosting` assembly.

This might not be new, wasn't there an issue about `Import-EditorCommand` already from around the time ALC changes were made?

**Comment by TylerLeonhardt** [comment]
But why would it work on 6.2?

**Comment by SeeminglyScience** [comment]
🤷‍♂ differences in how ALC's work?

**Comment by rjmholt** [comment]
Ah, I had assumed that loading the PSES asm into the default ALC would work for PowerShell, but I suppose it doesn't. It happens that the [way PowerShell exposes types in 7](https://github.com/PowerShell/PowerShell/blob/d46dfc26b7ee22a5598fff7680ea654ff9f7175d/src/System.Management.Automation/utils/ClrFacade.cs#L52-L64) has changed since [6.2](https://github.com/PowerShell/PowerShell/blob/ba332d042b2fb58d07f4ccd80c195ea7cbf690e7/src/System.Management.Automation/utils/ClrFacade.cs#L51-L63).

I'll see if I can find a way to attach the PSES assembly to the default ALC properly.

**Comment by rjmholt** [comment]
> I'll see if I can find a way to attach the PSES assembly to the default ALC properly.

Turns out this isn't possible, from what I've tried.

Ideally we could spin this out into a new assembly which is internally enlightened through the various APIs, but I don't think we have time for that before the release given the other high-priority bugs we want to address.

This works if we fully-qualify the type names for now, so I'll do that. Later on I'd like to spin out a separate module for it all. That will be a breaking change, but we'll do it with consultation and in a way that minimises the exposure to PowerShell. Certainly all the commands will be the same (just not the types).
