### ISSUE TITLE
PowerShell Terminal won't load

### ISSUE THREAD

**Issue by sidetrak2** [PowerShell/vscode-powershell#2512]
Issue Type: <b>Bug</b>

3/2/2020 1:49:31 PM [NORMAL] - Visual Studio Code v1.42.1 64-bit
3/2/2020 1:49:31 PM [NORMAL] - PowerShell Extension v2020.1.0
3/2/2020 1:49:31 PM [NORMAL] - Operating System: Windows 64-bit
3/2/2020 1:49:31 PM [NORMAL] - Path specified by 'powerShellExePath' setting - '"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"' - not found, reverting to default PowerShell path.
3/2/2020 1:49:31 PM [NORMAL] - Language server starting --
3/2/2020 1:49:31 PM [NORMAL] -     exe: C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
3/2/2020 1:49:31 PM [NORMAL] -     args: c:\Users\eric.lemonnier\.vscode\extensions\ms-vscode.powershell-2020.1.0\modules\PowerShellEditorServices\Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.1.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\eric.lemonnier\.vscode\extensions\ms-vscode.powershell-2020.1.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\eric.lemonnier\.vscode\extensions\ms-vscode.powershell-2020.1.0\logs\1583185771-a0bf354a-9adf-4006-b457-526bc09f908f1583185675563\EditorServices.log' -SessionDetailsPath 'c:\Users\eric.lemonnier\.vscode\extensions\ms-vscode.powershell-2020.1.0\sessions\PSES-VSCode-7032-853809' -FeatureFlags @()
3/2/2020 1:49:32 PM [NORMAL] - powershell.exe terminated or terminal UI was closed
3/2/2020 1:51:31 PM [NORMAL] - Language server startup failed.
3/2/2020 1:51:31 PM [ERROR] - The language service could not be started: 
3/2/2020 1:51:31 PM [ERROR] - Timed out waiting for session file to appear.

Tried 
-creating new workspace
-Setting powershell path
-restarting
-32bit and 64 bit version
-downgrading powershell extention a few versions back

Extension version: 2020.1.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjmholt** [comment]
@sidetrak2 thanks for opening an issue.

This looks similar to https://github.com/PowerShell/vscode-powershell/issues/2417, https://github.com/PowerShell/vscode-powershell/issues/1626 and https://github.com/PowerShell/vscode-powershell/issues/2014 (which may need consolidation). Unfortunately, we've tried a number of things to reproduce those issues and haven't been able to do it. To fix the issue, we need to collect more information to work out what the issue is.

Can you provide:

- Your PowerShell version
- A screenshot of VSCode when the extension has failed to start

Did the same version of the PowerShell extension work for you on this machine previously? Do you recall what changed in that time (Windows update, VSCode update, policy update)?

The PowerShell extension is getting a big update this week too, so it will be worth trying that when it comes out. I also note that your Windows version is RS3, which goes ends life in mid-April, so if you know what operating system you're migrating to, it might be worth trying this out on that.

**Comment by sidetrak2** [comment]
PSVersion 5.1.16299.1146
![image](https://user-images.githubusercontent.com/1693716/75732586-b689cf00-5ca7-11ea-8dc4-376b125752bd.png)

**Comment by rjmholt** [comment]
> but a recent update must have caused it to start failing

Do you mean a Windows, VSCode or extension update?

**Comment by sidetrak2** [comment]
I do recall an update, in the last few weeks, to VSCode that failed and left it uninstalled; I had to reinstall it from scratch. Though I don't recall if the problem began after that.

**Comment by rjmholt** [comment]
Ok. Well given that this is the 2020.1.0 extension (which came out in January) it sounds like this has been caused by an update in VSCode or Windows. We can review at the end of the week to see if this problem persists

**Comment by sidetrak2** [comment]
Windows did an update this morning and now it is loading correctly.
