### ISSUE TITLE
[Erreur] Could not start language service: undefined

### ISSUE THREAD

**Issue by theyanster** [PowerShell/vscode-powershell#252]
Extension version: 0.7.0
Visual Code version: 1.4.0
OS: Windows 7 Pro SP1 x64, **French**
PowerShell version installed on system (output of $PSVersionTable):

```
Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.2.9200.16398
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2
```

Description:

Getting following errors when opening a PowerShell script after installing the PowerShell extension:

**[Erreur]** Could not start language service: undefined
**[Erreur]** Couldn't start client PowerShell Editor Services

(Note: the word Erreur is not a typo, it's in French)

Steps to reproduce:

1. Install the PowerShell extension
2. Activate it
3. Once the interface reloads, open any PowerShell script

I'm not sure if this could be an issue with the fact my OS is in French, but it could be as I didn't have the issue on other English versions of Windows and even Ubuntu 16.04.

**Comment by theyanster** [comment]
![2016-08-22_11-16-54](https://cloud.githubusercontent.com/assets/21135311/17860212/a86b9790-685a-11e6-9af8-46f21a92cec4.png)

**Comment by daviwil** [comment]
Hey @theyanster, this is definitely an issue with the extension running on PS 3.0.  I'm going to try to get a fix out for this today or tomorrow.  You can check out the following issue for more details and a temporary workaround:

https://github.com/PowerShell/vscode-powershell/issues/248

I'll close this issue since we're already tracking it over at #248.  Thanks for the report!
