### ISSUE TITLE
conhost.exe remains after exiting VS Code

### ISSUE THREAD

**Issue by utw4376** [PowerShell/vscode-powershell#2530]
Issue Type: <b>Bug</b>

I am using VS Code w/ PowerShell module. Since updating to 2020.3 and released version of PS 7.0 after closing VS Code a conhost.exe process keeps running.

Steps to reproduce:
1. Start VS Code. (As I have PS as default language a PS 7.0 session gets started)
2. File -> Exit
3. conhost.exe is still running

When using PowerShell 5.1 instead of PS 7.0 conhost.exe terminates  together w/ all the other processes.

Extension version: 2020.3.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (8.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rjmholt** [comment]
This is https://github.com/microsoft/vscode/issues/50308.

Also discussed in https://github.com/PowerShell/PowerShell/issues/11542.

**Comment by CrendKing** [comment]
Why is this microsoft/vscode#50308? I think this is the opposite of that problem. We are talking about the PowerShell extension for VSCode, right? Since the extension can't do anything without starting a "session", which is a powershell process, which spawns a conhost.exe process, when exiting VSCode, it knows to kill the processes it directly spawns (powershell), but missing conhost.

I can clearly see the conhost process holding VSCode directory handle when inspecting with something like Process Explorer.

**Comment by eddiezato** [comment]
VS Code keeps recommending the "powershell extension" all the day, but I just can't use it. After a full day of editing ps1 files, I regularly find that the task manager is overflowing with dozens of conhost processes. I have to either manually kill them one by one or reboot the computer. It's frustrating as hell.

**Comment by CrendKing** [comment]
After some digging, I found that if `powershell.integratedConsole.useLegacyReadLine` is set to true (default is false), the conhost.exe no longer lingers after VSCode is terminated. Since this setting is [related to PowerShellEditorServices](https://github.com/PowerShell/vscode-powershell/blob/0ec48b0542618657a062b8a619e7e8158883c756/src/process.ts#L61), something might need fix on that side. But at least we have a workaround now.

**Comment by andschwa** [comment]
Oo good to know @CrendKing, thanks! @rjmholt and @daxian-dbw sounds like something with `PSReadLine` might be keeping `conhost.exe` around.
