### ISSUE TITLE
CLS in the temporaray integrated console does not work as expected

### ISSUE THREAD

**Issue by Hypernut** [PowerShell/vscode-powershell#2574]
Instead of removing all output from the console, the CLS-command in the integrated console just scrolls the current prompt to the top. 
That causes multiple problems, especially with large data output, as the scrollbar gets smaller and smaller, because output never gets removed.
Also, you can't output a few screens worth of data and then quickly scroll to the top to read it. Because output never gets removed it gets more difficult to scroll back to the line where the last output started.

Expected behavior: let CLS behave like in the standalone powershell-console and in ISE.

**Comment by corbob** [comment]
You'll want to enable the `powershell.integratedConsole.forceClearScrollbackBuffer` setting which will use the VS Code API to clear the scrollback buffer.

**Comment by Hypernut** [comment]
Right, thanks, this works for the (normal) integrated console, BUT it does not work in the temporary console. Ill update the bug-description above. Thanks!

**Comment by TylerLeonhardt** [comment]
Unfortunately, it just can't work for the Temporary Console at this time. It's a limitation.

There use to be a warning that said "this won't clear the whole screen" if you had the setting @Corbob mentioned turned on but someone complained so we took out the warning.

There are 2 message protocols:
* language server 
* debug adapter

The reason why it doesn't work is because clearing the scrollback buffer is done by sending a message to the client via the language server protocol and in a temporary console, there is no language server... Only a debug adapter.

The only way I can see this ever getting fixed is by figuring out how to clear the screen using an ANSI Esc sequence instead of the VS Code API... But older versions of Windows have had trouble supporting these.

**Comment by Hypernut** [comment]
Thats a shame. Thanks for the explanation though.
