### ISSUE TITLE
Psremoting with Prefix causes intellisense to go wild

### ISSUE THREAD

**Issue by bobthewonderdog** [PowerShell/vscode-powershell#2584]
Hi all,

I am using the powershell preview and vscode insiders.

I import a module with a prefix  eg.

Import-PSSession $EXOSession -prefix O365 -AllowClobber

when i run any commands i get this issue and the console locks up and cannot be recovered until it has finished searching help

Notice it doubles the Prefix in searching help.

Get-Help 100% Searching Help for New-O365O365ActiveSyncDeviceAccessRule ...
 Get-Help 100% Searching Help for New-O365O365ActiveSyncDeviceAccessRule ...
 Get-Help 100% Searching Help for New-O365O365ActiveSyncDeviceAccessRule ...
 Get-Help 100% Searching Help for New-O365O365Mailbox ...
 Get-Help 100% Searching Help for New-O365O365Mailbox ...
 Get-Help 10% Searching Help for New-O365O365Mailbox ...

**Comment by bobthewonderdog** [comment]
This happens when i highlight an area in the command with the mouse to copy or paste information

**Comment by nakosenk** [comment]
This is likely caused by the same root problem I came across with the RemoteDesktop module that I ran into [here](https://github.com/PowerShell/PowerShellEditorServices/issues/1242).

**Comment by TylerLeonhardt** [comment]
@nakosenk did you also import the module with a prefix?

**Comment by nakosenk** [comment]
I did not import it with a prefix, but it's one of the few Microsoft modules that specifies a Prefix in its module manifest.

**Comment by TylerLeonhardt** [comment]
> it's one of the few Microsoft modules that specifies a Prefix in its module manifest.

Very good to know.

**Comment by TylerLeonhardt** [comment]
Thanks for the info, @bobthewonderdog ! Can you also [attach the logs](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment) here so we can get a better idea of what's going on?

**Comment by TylerLeonhardt** [comment]
> when i run any commands i get this issue and the console locks up and cannot be recovered until it has finished searching help

For each item you are looking at in intellisense, we run `Get-Help` to give you the extra info you see (Parameter details, help text, etc). That is by design in the PowerShell extension:
![image](https://user-images.githubusercontent.com/2644648/77674839-6837bb00-6f49-11ea-9643-98ab32eb78e6.png)


The odd part here is that for cmdlets that use prefix, `Get-Help` seems to be slower than normal and the progress text shows a duplicate prefix.

You can verify this in PowerShell:
```powershell
Import-PSSession $EXOSession -prefix O365 -AllowClobber
Get-Command "New-O365ActiveSyncDeviceAccessRule" | Get-Help
```

When I run that ^ (well for me I just imported a module with a prefix...) the progress text shows:

```
Get-Help 100% Searching Help for New-O365O365ActiveSyncDeviceAccessRule ...
```

with the duplicate prefix... but the operation seems to work as expected...

That makes this (and @nakosenk's issue) a PowerShell bug which has two problems:
* The prefix is duplicated in the progress text - a purely cosmetic issue
* `Get-Help` is _slow_ when dealing with a cmdlet that has a prefix...

Can one of you open an issue on _each_ of these things over in https://github.com/PowerShell/PowerShell

**Comment by TylerLeonhardt** [comment]
I think given `Get-Help`'s poor perf, we may need to skip over running `Get-Help` for cmdlets with a prefix...

**Comment by nakosenk** [comment]
I haven't had a chance to try it, but the underlying problem might be with CommandInfo.ToString(). When converting a [CommandInfo](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.commandinfo?view=powershellsdk-1.1.0) object to a string, it duplicates the prefix, but accessing the Name property gives the correct correct name. 

In CommandHelpers.cs, when it builds the call to Get-Command, it [passes the name of the command directly](https://github.com/PowerShell/PowerShellEditorServices/blob/9af08231bed84a9701e62a25bcd73f9920ea1539/src/PowerShellEditorServices/Services/PowerShellContext/Utilities/CommandHelpers.cs#L60) which does not duplicate the prefix. But when building the call to Get-Help, [it passes the whole CommandInfo object](https://github.com/PowerShell/PowerShellEditorServices/blob/9af08231bed84a9701e62a25bcd73f9920ea1539/src/PowerShellEditorServices/Services/PowerShellContext/Utilities/CommandHelpers.cs#L90). Changing the argument to be `commandInfo.Name` should probably resolve the problem.

**Comment by TylerLeonhardt** [comment]
@nakosenk yep great find. I was just about to make that exact change :)

Please do open an issue on PowerShell about `CommandInfo.ToString()` and how it causes `Get-Help` to fail.

**Comment by TylerLeonhardt** [comment]
PR out (for the extension) ^
