### ISSUE TITLE
Debugging (PowerShell Preview for VS Code): How to select different console/terminals when running (F5) a script?

### ISSUE THREAD

**Issue by swinster** [PowerShell/vscode-powershell#2585]
Hi,

With PS Preview for VS Code (Windows) I have two terminals:

* The Integrated Console (default) with uses PS Core v7
* A Normal Windows PS 5.1 terminal 

When debugging, If I need to run a section of a script (F8), I can select the terminal that I wish this to run in, select the lines and run those, and the pre-selected terminal is used.

However, if I run the full script (F5), the debugger immediately jumps into the Integrated Console.

Whilst this is fine and desirable to many scripts, there are some that still require the older Windows PS 5.1 terminal to run.

I looked at https://code.visualstudio.com/docs/editor/debugging which seemed to suggest the a "Console" parameter could be added to a Debugging configuration, but when I do, it shows as "Property console is not allowed."

Is it possible to be able to run the script using different terminal contexts?

**Comment by TylerLeonhardt** [comment]
This is what makes the Integrated Console "integrated". The Integrated Console is hooked up to the debugger and other language features (like intellisense, CodeLens, etc).

The only reason F8 works is because vscode added a mechanism to take the selected text and run it in the terminal below...It's really a glorified copy/paste... but if you do F8 with a normal terminal vs an F8 with the integrated terminal, you'll notice they're different and that's because the integrated terminal has a special mechanism in place to send the whole selection to the PowerShell session - that's better than the glorified copy/paste.

This is unfortunately by-design and I can't really help you. There _is_ however an editor command called "Run active file in active terminal" that can run your whole script in the terminal below, but that won't have debugging set up.

Also keep in mind you can change the version that the extension uses any time by clicking on the green version number at the bottom right (if you have a PowerShell file opened) or running the editor command "PowerShell: Show Session Menu"

**Comment by swinster** [comment]
@TylerLeonhardt that last sentence was the nugget of info I was looking for. I have been banging my head for about a day try to think where I used to switch versions (such as the problem if not being a "proper dev"). This worked perfectly and is all that is required,

**Comment by TylerLeonhardt** [comment]
There's some documentation for your future reference :) 

https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-7#choosing-a-version-of-powershell-to-use-with-the-extension
