### ISSUE TITLE
VS Code hangs when i launch Powershell debug with f5

### ISSUE THREAD

**Issue by sandy081** [PowerShell/vscode-powershell#266]
_From @maxcli on August 25, 2016 17:11_

VSCode Version: 0.7.0. (Installed Aug 25,16)
OS Version: win 10  

I immediately hang 

Steps to Reproduce:
1. set a breakpoint on 2nd line of ps1 code.  
2. f5

_Copied from original issue: Microsoft/vscode#10966_

**Comment by daviwil** [comment]
Hey @maxcli, can you try updating to version 0.7.1 of the PowerShell extension and see if the issue improves for you?  If not I'll get you to grab some logs so I can take a look.  Thanks!

**Comment by daviwil** [comment]
Hey @maxcli, just checking back in, can you try this with the latest version of the PowerShell extension (0.7.2, released last Thursday) to see if the problem has been resolved?  If not, [follow these instructions](https://github.com/PowerShell/vscode-powershell#2-capture-verbose-logs-and-send-them-to-us) to grab logs so that we can take a look.

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if this is still an issue.
