### ISSUE TITLE
Error: Input fields of type 'PSCredential' are currently not supported.

### ISSUE THREAD

**Issue by smiket** [PowerShell/vscode-powershell#268]
I ran into this issue when debugging in Studio Code 1.4.0 with Powershell Extension 1.7.1.
Not sure if the exception is from Studio Code, or from the extension.

Input fields of type 'PSCredential' are currently not supported.
At C:\Dev Poc\PowerShell\Advisor TFS Crawler\GetTfsSettings.ps1:10 char:1
+ $creds = Get-Credential
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException

**Comment by daviwil** [comment]
This is coming from the extension, we currently don't support PSCredential in the debugger because we need to find a secure way to pass credentials from the editor to the debug server.  There may be a different way to solve this in the near future, fingers crossed!

Also related: https://github.com/PowerShell/vscode-powershell/issues/57

**Comment by smiket** [comment]
Thanks David, sorry I missed the other report on this.  Excellent job on the extension - really nice product.
