### ISSUE TITLE
Execution results of powershell.exe and vscode terminal are different.

### ISSUE THREAD

**Issue by engnut** [PowerShell/vscode-powershell#2680]
windows powershell version 5.1

## Script
```powershell
# pattern 1
$Paths = @'
HKLM:\Software\Microsoft\Windows\CurrentVersion\Run
HKCU:\Software\Microsoft\Windows\CurrentVersion\Run
'@ -split "`n"

foreach ($Path in $Paths) {
 Write-Host ('{0}: {1}' -f $Path ,(Test-Path $Path))
}

# pattern2
$ChangedIndexPaths = @'
HKCU:\Software\Microsoft\Windows\CurrentVersion\Run
HKLM:\Software\Microsoft\Windows\CurrentVersion\Run
'@ -split "`n"

foreach ($ChangedIndexPath in $ChangedIndexPaths) {
  Write-Host ('{0}: {1}' -f $ChangedIndexPath , (Test-Path $ChangedIndexPath))
}
```

## VSCode F8 Result (powershell integrated console)
```
: Falseoftware\Microsoft\Windows\CurrentVersion\Run
HKCU:\Software\Microsoft\Windows\CurrentVersion\Run: True
: Falseoftware\Microsoft\Windows\CurrentVersion\Run
HKLM:\Software\Microsoft\Windows\CurrentVersion\Run: True
```

## powershell.exe Result
```
HKLM:\Software\Microsoft\Windows\CurrentVersion\Run: True
HKCU:\Software\Microsoft\Windows\CurrentVersion\Run: True
HKCU:\Software\Microsoft\Windows\CurrentVersion\Run: True
HKLM:\Software\Microsoft\Windows\CurrentVersion\Run: True
```

**Comment by rjmholt** [comment]
I'm able to get the same behaviour in `powershell.exe`:

![bug](https://user-images.githubusercontent.com/7009879/81116431-2e5bbc00-8eda-11ea-90e5-3623b1d2e7bc.PNG)

The issue seems to be that you're splitting by ``"`n"`` instead of by ``"`r`n"``. This means that the first path you look for is ``"HKLM:\Software\Microsoft\Windows\CurrentVersion\Run`r"``. When you format this as you describe, you're doing this:

```powershell
'{0}: {1}' -f "HKLM:\Software\Microsoft\Windows\CurrentVerrsion\Run`r",$false
```

which outputs exactly what you see:

```
: Falseoftware\Microsoft\Windows\CurrentVerrsion\Run
```

I suspect the reason you're seeing something different in powershell.exe is that the newlines are ones you've written into the terminal rather than into a file. Try running the script you've got in VSCode from powershell.exe directly by its path and you should see the same outcome.

The solution is to split by `[system.environment]::newline` instead or to write the paths into an array ahead of time.

**Comment by engnut** [comment]
I see, thank you.
