### ISSUE TITLE
Inline C# highlighting/completion

### ISSUE THREAD

**Issue by Serentty** [PowerShell/vscode-powershell#2690]
When using ``Add-Type`` to include C# code in a script, it would be nice if the C# code inside of the string could benefit from C# highlighting and/or completion if the user also has that installed. Hopefully, this plugin could defer to another plugin for just that section of code, and not the rest of the file.

**Comment by rjmholt** [comment]
While this would be nice to have, it's quite a complex request, since:

- Highlighting currently depends on the [EditorSyntax repo](https://github.com/powershell/editorsyntax) and [while it's possible to embed a language](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages), the TM grammar is hard to make changes to
- Any change to the TM grammar wouldn't be able to detect (or would have a very hard time detecting) any of:
    - Using Add-Type with other parameter sets that don't involve could
    - Choosing a language other than C# for highlighting
    - Using a template string
    - Writing the C# code into a string in one place and passing it to Add-Type elsewhere
- Those second two are where things get particularly tricky, since you're not writing C# anymore, but a templatised PowerShell string that will become C#, which belongs to neither language. And because you could perform arbitrary transformations on the string, there's no general way to solve this issue.
- We are projecting moving away from the TM grammar toward a semantic syntax provider implementation in the medium term, so changes to the grammar wouldn't be long lived anyway. It might be possible to solve this using semantic highlighting, but there's a list of things we want to solve first.
- Completions we can't offer at all and would need to rely on another extension (and the user would need to install that), but as far as I know there's no mechanism to (1) get an extension to look at just a section of a file, or (2) communicate directly from one extension to another, which we would probably need to do. Every problem for highlighting essentially applies doubly for completions.

Also, the extension tries not to be opinionated (certainly when features go in, it tries to keep them configurable), but in this case it's arguable that C# embedded in PowerShell should be short enough to not want highlighting or intellisense.

For now, we're going to close this is beyond our scope due to the complexity of the implementation and narrow confines under which we could expect it to work. My recommendation instead would be:

- Write the C# code as a separate file with a `.cs` ending and use `Get-Content -Raw`,
- Or ideally, build the C# ahead of time into a DLL and ship that

**Comment by Serentty** [comment]
Thanks for the in-depth answer. Using a separate file is certainly an acceptable solution. I figured I would ask anyway because I wasn't sure how hard it would be to get extensions to communicate.
