### ISSUE TITLE
PowerShell Extension: Problem with [System.Windows.Forms.MessageBox]

### ISSUE THREAD

**Issue by Hed86** [PowerShell/vscode-powershell#2739]
### System Details
VS COde Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

### Issue Description
**The following error occurs on Start / Reload Window**

- Unable to find type [System.Windows.MessageBox]

![image](https://user-images.githubusercontent.com/6883550/83525062-c4d4ca80-a4e4-11ea-8d0b-a6836eb7c31b.png)

- although "Add-Type -AssemblyName System.Windows.Forms" is declared at the beginning of the script

![image](https://user-images.githubusercontent.com/6883550/83525176-edf55b00-a4e4-11ea-9f05-6bc61f1b7e88.png)

- if I run "Add-Type -AssemblyName System.Windows.Forms" in the terminal, everything works again

![image](https://user-images.githubusercontent.com/6883550/83525294-0ebdb080-a4e5-11ea-8fd1-6ba9b81785fe.png)

- the error does not occur in PowerShell ISE

![image](https://user-images.githubusercontent.com/6883550/83525414-3ad93180-a4e5-11ea-8f41-81a988c4225f.png)

**Comment by TylerLeonhardt** [comment]
The ISE is a WinForm application so it already has it loaded. That's more of a necessity than a feature.

 You have to do this same step in `powershell.exe`/`pwsh.exe` to get it to work so the PowerShell extension is _closer_ to the actual executable than the ISE.

If you always want it loaded, you can always include that `Add-Type` in your $profile but since not everyone does WinForm development (or is on Windows for that matter) I don't think we can do this automatically for you.

**Comment by Hed86** [comment]
The problem only occurs with the **MessageBox** class.
![image](https://user-images.githubusercontent.com/6883550/83738565-c0c7ba80-a654-11ea-89f7-2ade2269ab2d.png)

This is not the case with the normal **Window** class.
![image](https://user-images.githubusercontent.com/6883550/83738649-db019880-a654-11ea-97ad-05ad72500172.png)

Anyway, if someone has the same problem, **here is the solution**:

![image](https://user-images.githubusercontent.com/6883550/83739963-8a8b3a80-a656-11ea-9ea9-2e1988b0a7b7.png)
If the file does not exist, just create it.

Then insert "Add-Type -AssemblyName System.Windows.Forms", save and close
![image](https://user-images.githubusercontent.com/6883550/83740574-5106ff00-a657-11ea-93f3-17d915260b85.png)

PS: nonetheless, in my humble opinion, if there is a functionality, so it has to work well. 
Solving the problem with a workaround works for a short time, but in the long run it is not a particularly professional approach.
Thanks anyway for your answer, helped me a lot.

**Comment by rjmholt** [comment]
I think the point is that the ISE isn't *designed* for this to work, it just happens to work because the ISE is a WinForms application, meaning the assembly is already loaded. Expecting this to work depends on an implementation detail of the ISE that it wasn't possible to hide.

The PowerShell extension is specifically designed to get out of the way and hide dependencies, and tries to work more like powershell.exe than psise.exe. Adding the `Add-Type` will keep your script working in the ISE, but will also make it work in the PowerShell extension and powershell.exe, where it wouldn't have worked before.
