### ISSUE TITLE
Make the progress of searching PS function implement faster

### ISSUE THREAD

**Issue by gaofeibupt** [PowerShell/vscode-powershell#2877]
First, Thanks to your contributions to this project.

_**The weakness about PowerShell plugin**_
I used this plugin for a long time. I find the progress of searching PS function implement is slow. So, I prefer to use "git grep" to find the implements of functions, it's faster enough than this plugin. The statue is that it's slow and cost lots of memory. When I click the definition of a function, the plugin begin to search, after a long time, it find the implement, but I check my PC station memory usage, the vscode used 30GB, My PC holds 32GB memory totally. I'm not sure that how do you implement this feature which can find a implement. My working repo's disk usage is about 28GB.

**_My idea about how to tackle with this weakness_**
Base on PowerShell SDK, and use syntax analysis tool to build a function implement index **_in advance_**, after this we can find the definition of a function more quickly. 😁 Here is my idea.

The content of example.ps1 file
```powershell
function A {  # line 1
}             # line 2
              # line 3
function B {  # line 4
}             # line 5
```

And the index will be built like this
```txt
function A, example.ps1:1 # function A at line 1 of example.ps1
function B, example.ps1:4 # function B at line 4 of example.ps1
```

**Comment by rjmholt** [comment]
> the vscode used 30GB

Do you mean VSCode or the PowerShell process that drives the PowerShell extension backend ([PowerShell Editor Services](https://github.com/powershell/powershelleditorservices))? The former is the text editor that hosts the extension client, and does almost no processing of PowerShell -- any memory usage there is not being used for PowerShell but for node and Electron.

If you want to look at the process performing reference analysis for the PowerShell extension, go into the Integrated Console and get the `$PID`.

> Base on PowerShell SDK, and use syntax analysis tool

Do you mean [like this](https://github.com/PowerShell/PowerShellEditorServices/blob/c40734354631043cf3c390d36c9b1ef6a80b3949/src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs#L182-L205)?

> build a function implement index in advance, after this we can find the definition of a function more quickly

Yeah, a cache would be nice.

Building it in advance would be bad for startup time, so we'd need to do it lazily.

The problem is that caches become invalid. We're in an editing environment and files get edited and so you have to rerun the analysis when that happens. That's not a big deal. The problem is that PowerShell is a lot more state-dependent and implicit than other languages. Doing something like changing the PSModulePath might mean we have to go an recalculate all the references. Or executing a command in the Integrated Console.

**Comment by gaofeibupt** [comment]
**_About the memory usage_**
I don't think it's a big deal 😁.

**_About the PS syntax analysis_**
I used the API name `[System.Management.Automation.Language.Parser]::ParseFile` of the PowerShell SDK, but I think it's familiar with API `public static IEnumerable<SymbolReference> FindReferencesOfSymbol`.

**_About building a index in advance_**
I think I need it. In a huge repo with lots of PowerShell files, it's so slow for doing search function definitions or references. Even if you edit some files, VScode can rebuild the hole index. You may think it's stupid. But it should save much of times in code searching.

**Comment by rjmholt** [comment]
> About the memory usage
> I don't think it's a big deal 😁.

Yeah, my point there is that you're looking at the wrong process. VSCode isn't the process where PowerShell references are being calculated, `powershell.exe` is.

**Comment by gaofeibupt** [comment]
Is there any plan for improving code searching? Most of times, we reading the code written by others. In a huge repo, we just change several files in once commit, I think rebuilding a the coding index is not a bad idea. 🤣 What do you think about it?

**Comment by SydneyhSmith** [comment]
@gaofeibupt are you thinking of VScode's code search or something within the PowerShell extension?

**Comment by gaofeibupt** [comment]
@SydneyhSmith  Yeah, but I'm not familiar with extension development.

**Comment by rjmholt** [comment]
I think @SydneyhSmith's question was about whether you're referring to this:

![image](https://user-images.githubusercontent.com/7009879/90271351-862a8d00-de10-11ea-9802-fe7bcbbc0ffa.png)

Or to something else?
