### ISSUE TITLE
Extension crashes/stops working when opening large JavaScript file

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/vscode-powershell#2920]
Issue Description
=====

I am experiencing a problem with...extension crashing or just vanishing somewhere.

1. Open PowerShell
2. See it works
3. Go and open minimized JS script (huge one I guess) 
4. Notice PS extension no longer works

![ExtensionStopsWorking](https://user-images.githubusercontent.com/15063294/91542074-9157df80-e91d-11ea-8da5-7314070580e5.gif)

[1598604992-0f6cc825-a16d-4ba7-8b4a-7180a45d695a1598604991086.zip](https://github.com/PowerShell/vscode-powershell/files/5141104/1598604992-0f6cc825-a16d-4ba7-8b4a-7180a45d695a1598604991086.zip)

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) about
capturing and sending logs.

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19042 |
| VSCode | 1.48.2|
| PowerShell Extension Version | 2020.7.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.19041.1|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.19041.1|
|BuildVersion|10.0.19041.1|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|better-toml|bungcip|0.3.2|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|errorlens|usernamehw|3.2.1|
|format-selection-as-html|adrianwilczynski|2.3.0|
|github-linker|gimenete|0.2.3|
|gitlens|eamodio|10.2.2|
|line-endings|steditor|1.0.3|
|markdown-all-in-one|yzhang|3.2.0|
|material-icon-theme|PKief|4.2.0|
|open-in-browser|techer|2.0.0|
|powershell-preview|ms-vscode|2020.7.0|
|project-manager|alefragnani|11.2.0|
|run-in-powershell|tobysmith568|1.1.0|
|vscode-markdownlint|DavidAnson|0.36.3|
|vscode-toggle-quotes|BriteSnow|0.3.3|
|vscode-wakatime|WakaTime|4.0.7|
|vscode-yaml|redhat|0.10.1|
|xml|DotJoshJohnson|2.5.1|

**Comment by SydneyhSmith** [comment]
Thanks @PrzemyslawKlys looking at the GIF we are having a bit of trouble understanding where the extension crash is happening, what behaviors/messages did you receive to know it had crashed?

**Comment by PrzemyslawKlys** [comment]
1. Before I switch to JS in right bottom corner you can see 5.1 PowerShell - meaning extension is active
2. When I switch to JS you see at the bottom - activating extension (middle of the screen)
3. When you switch back to PowerShell, notice how in right bottom corner 5.1 is missing

Clearly minimized JS is making problems for Code, but it impacts PowerShell extension as well as it never recovers from that.

**Comment by TylerLeonhardt** [comment]
Gotcha, can you attach what you see in dev tools console tab?:
![image](https://user-images.githubusercontent.com/2644648/91905251-195e2200-ec5b-11ea-8f14-573e00332954.png)
![image](https://user-images.githubusercontent.com/2644648/91905289-2bd85b80-ec5b-11ea-9a2a-9680cf83ae34.png)

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/91905478-e477bc80-eca6-11ea-877e-fd435824347e.png)

**Comment by PrzemyslawKlys** [comment]
Hrms, actually PowerShell extension didn't crash. It's just waiting for very long time (1+ minute) and finally comes back. It seems minimized JS may be too big for Code and it halts everything until it's processed.

**Comment by TylerLeonhardt** [comment]
@PrzemyslawKlys very possible. That "UNRESPONSIVE" warning might be a clue that the bracket-pair-colorizer-2 is unable to handle it... just a guess.

**Comment by rjmholt** [comment]
Certainly an issue with node is that anything running on the event loop will block it for everything else. Despite two extensions being unrelated, one can block the event loop and cause the other to starve. It's likely that:

- The PowerShell extension can do nothing itself to prevent this. The hosting architecture is responsible for what happens here.
- In particular, being a good citizen on this platform means breaking things up into asynchronous chunks. Being a thin client, the PowerShell extension almost exclusively performs asynchronous IO actions, rather than heavy computation in the VSCode process.
- Document formatting and analysis tends not to be simple to make asynchronous, making accomplishing this task hard unless it's simply pushed out of process (significantly increasing the complexity of the extension).
- Another classic trap that causes big slow downs is trying to store text files by lines. When files are minified or otherwise deflated, whitespace including newlines gets taken out, leaving everything on the same line. When extensions use backing data structures that break down text documents by line, they suddenly have a degenerate case of an array with a huge single element, which causes issues both for the logic itself but also for allocation and GC (single allocations beyond about 10kB tend to be handled as "large objects" by runtimes, requiring special, slower behaviour to keep things working nicely -- [e.g. in node](http://jayconrod.com/posts/55/a-tour-of-v8-garbage-collection)). You can see [bracket-pair-colorizer-2](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/blob/09f150628583ea40c69374daf31f61e987321440/src/documentDecoration.ts#L36-L74) uses such a line-array structure. [As does the PowerShell extension, unfortunately](https://github.com/PowerShell/PowerShellEditorServices/blob/f910888198af5e64134d8a337ea70c895d41535f/src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs#L315-L404). But then, so does `vim` I suppose...
- bracket-colorizer-2 also uses a strange search heuristic which will [allocate a new string in O(n) of the original line for each bracket pair](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/blob/09f150628583ea40c69374daf31f61e987321440/src/documentDecoration.ts#L325-L339). So basically if you accept that the number of brackets in a line also increases linearly, you're seeing the worst case O(n^2) performance here (and in the case where n is high...).
- VSCode themselves could conceivably try to mitigate this by running extensions out of process, but:
    - The overhead of that would be large, and VSCode's overhead is already substantial
    - Existing APIs may depend on mechanisms that cannot be converted to a serialised form
    - Extensions are already free to do this themselves; there's arguably no reason to force it on them

I think if you want to examine this further, it's worth doing some performance profiling of this, for example by building a flame graph. I suspect we would see that we're spending almost the full minute in the bracket colouriser.

**Comment by PrzemyslawKlys** [comment]
I don't think my skills allow me to debug this kind of application at this moment. I was more worried that the PS extension was crashing and that got me worried, but it seems I was just impatient. So I'll let it go, as I don't have to edit those minified files anyways, just rarely stumbling upon them. I could open the issue in Code but seeing as some more crucial ones like the newest git versions not working with linked files I'm gonna just skip it. Thank you for your assessment. I guess I could also try disabling bracket-pair-colorizer-2 as it could be the offender here - but I quite like it.
