### ISSUE TITLE
Matches multiple schemas when only one must validate

### ISSUE THREAD

**Issue by RevealedFrom** [PowerShell/vscode-powershell#2980]
### System Details

System Details Output
```
- PowerShell extension version: v2020.6.0
- Output from `$PSVersionTable`: 6.2.2 Core
```

### Issue Description

I am experiencing a problem with launch.json saying: `Matches multiple schemas when only one must validate`.

#### Expected Behaviour
launch.json was last modified in June 2019, and there were no errors.

#### Actual Behaviour
Now, enabling PowerShell extension results in `Matches multiple schemas when only one must validate`

### Attached Logs
My launch.json is:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "protocol": "inspector",
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}\\bin\\www"
    }
  ]
}
```

**Comment by rjmholt** [comment]
> - Output from `$PSVersionTable`: 6.2.2 Core

Just FYI, your PowerShell version is very much end-of-life. You should upgrade to PowerShell 7 to be in support.

This kind of warning seems to be issued when schemas are applied to the launch.json. There's no explicit `$schema` here, so it's possible an extension causes it. However:

- I notice this is a node configuration rather than a PowerShell one
- I'm not able to reproduce it with VSCode 1.50.0-insider and PowerShell Preview extension 2020.9.0 (if you disable the PowerShell extension and install the PowerShell Preview extension, does this issue persist?)
- The issue may be caused by other extensions. If you look in the issue template you'll see the list of installed extensions is something we ask you to provide to better debug your issue.

**Comment by RevealedFrom** [comment]
I upgraded to Powershell 7.1.0-rc.1 and it's the same.

The other extension that could be causing the same Problem (VS Code lists it in the Problems window) is C# for Visual Studio Code (powered by OmniSharp). But I disabled that to isolate testing with the PowerShell extension.

I have installed PowerShell Preview 2020.9.0 and the Problem has gone away!

**Comment by rjmholt** [comment]
> I upgraded to Powershell 7.1.0-rc.1 and it's the same

Yeah, I wouldn't have expected that to affect the schema issue.

> I have installed PowerShell Preview 2020.9.0 and the Problem has gone away!

Ok great — sounds like the issue is fixed upstream and the fix will come to stable in time.
