### ISSUE TITLE
Implement document and workspace symbol providers for classes

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#3]
This requires an implementation of the DocumentSymbolProvider and WorkspaceSymbolProvider interfaces.  Relevant code will need to be added to PowerShell Editor Services to support this behavior.

**Comment by sgtoj** [comment]
Would this allow for symbols search and goto for PS 5.0's classes and enums?

**Comment by daviwil** [comment]
Yep, that's something we haven't finished yet.  Seems like you had commented on the Editor Services issue for this a while back:

https://github.com/PowerShell/PowerShellEditorServices/issues/14

Sorry about that :/  I'll see if I can get some help to get that implemented for the 0.8.0 release!

**Comment by Golosok** [comment]
Any updates on this? I have version 0.9.0 now and this doesn't seem to work.

**Comment by powercode** [comment]
Any updates?

This is a big missing piece for me. I try to do most of the development as classes, and wrap them with functions to get the task based abstractions.
But that means navigation is only available for a minor subset of my code.

**Comment by mmajcica** [comment]
Same here, enums are not 'colored' at all (plain white).

**Comment by tylerl0706** [comment]
Just for the record, @mmajcica, enums being not colored is an EditorSyntax issue. That's all the syntax highlighting. This issue is opened there:
https://github.com/PowerShell/EditorSyntax/issues/29

Thank you all for your patience! Classes and enums are lacking at the moment for sure.

**Comment by rjmholt** [comment]
> Go to definition for class and class methods do not work on ps core

That's a 2.0.0 feature. Compatibility with PowerShell v3/v4 mean we can't use new APIs that expose class ASTs. So no class symbols until we drop v3/v4 support.

**Comment by msftrncs** [comment]
@rjmholt, that doesn't sound correct.  That doesn't sound like a smart thing to do, to not be able to use a new API because you must still support an old API.  At that rate, we'd never have moved past DOS.    If this is such a problem, maybe both versions of the extension should be made available, but I would like to think that should not be needed.

**Comment by abelal83** [comment]
Agreed, it would be much better to provide both versions. Right now we're managing with some difficult with relatively small code base, but can't imagine how complex it will be as our code base gets larger.

**Comment by mud5150** [comment]
@rjmholt Should I expect go to definition to work now if I'm using the 2.0 preview extension? Just installed and it doesn't appear to be working.

**Comment by rkeithhill** [comment]
Not  yet.  First step is dropping support for v3 AST which 2.0 preview does.  Next step is to add support for classes (and enums).

**Comment by rjmholt** [comment]
> Agreed, it would be much better to provide both versions. Right now we're managing with some difficult with relatively small code base, but can't imagine how complex it will be as our code base gets larger.

Precisely the problem we face in this code base. We've been trying to make the code more maintainable since we're spread thin across 30k lines of C#, and tangling things up in compile-time macros means the code gets harder to reason about and we have to juggle multiple DLLs to load at runtime.

The decision to not compile a different DLL for PS v3/4 (compared to PS v5) was made by @daviwil in an earlier iteration of the project, but adding the capability back in presented a significant architecture-changing work item for new maintainers.

Anyway, now that PSReadLine means we are incompatible with PS v3/4, we can feasibly move back to an `AstVisitor2` implementation without much complexity.

**Comment by TylerLeonhardt** [comment]
This will be trickier than anticipated. Uncommenting the code that already existed didn't really do much. Here's what it has:

- Class method symbols (but not references)
- Class constructor symbols (but not references)

Here's what it's missing:

- Class property symbols and references
- Class (as in the type itself) symbols and references
- Class method references
- Class constructor references
- Enum symbols and references

References here means actually going through and figuring out that a symbol (`[MyClass]::Foo`) is a reference of a class symbol (in this case a property of class MyClass). This will be tricky with non-static members... and will probably be best effort.

So yeah. Lot's to do.

**Comment by lesterm5150** [comment]
Is this planned or being worked on?

**Comment by Golosok** [comment]
Any update or ETA?

**Comment by DougChandler** [comment]
Not sure if this been reported, but when editing a script that contains classes, the breadcrumb at the top of the script does not work for any class/method/enum.
Since I use classes, this is very frustrating :(

**Comment by mpetr** [comment]
as an heavy user of classes in all bigger projects, the ETA (or knowing any alternative approach) would be nice

**Comment by andschwa** [comment]
This is landing in the next preview!!!

**Comment by andschwa** [comment]
Fixed by https://github.com/PowerShell/PowerShellEditorServices/pull/1984

**Comment by JustinGrote** [comment]
@andschwa working great! I have about as complex of a class as it gets in ModuleFast, and methods aren't showing up for some reason for the most part, I think maybe because I implement IComparable and it's only picking up those base methods like `Equals`?

https://github.com/JustinGrote/ModuleFast/blob/b531aa9ee95eb5941a064c9c0d0f2892e298db15/ModuleFast.psm1#L608-L620

![image](https://user-images.githubusercontent.com/15258962/217321733-fef0f276-9b4f-40b6-83b2-a405fe360311.png)

I have less complex classes that work fine and show all methods like `NuGetRange`
![image](https://user-images.githubusercontent.com/15258962/217322017-cf9fce37-ec31-4cf3-8359-57b51429252f.png)

Let me know if this needs a new issue.

**Comment by SeeminglyScience** [comment]
Yeah there's typically nothing we can do in the extension to make new completions appear.

That said, you might be hitting PowerShell/PowerShellEditorServices#1810 which *is* our problem. If it shows up after a <kbd>Esc</kbd> then <kbd>Ctrl</kbd> + <kbd>Space</kbd> then it's ours. If not, then you'd want to open in PowerShell/PowerShell

**Comment by JustinGrote** [comment]
@andschwa @SeeminglyScience oops I conflated two different things, you're right! Sorry about that, doing a quick symbol search and I'm seeing what I expect to see as well. Thanks!
