### ISSUE TITLE
Add Syntax Highlighting for EPS (Embedded PowerShell)

### ISSUE THREAD

**Issue by Deastrom** [PowerShell/vscode-powershell#3060]
**Summary of the new feature**

I know Embedded PowerShell isn't a built-in module, but it is powerful and has allowed my team to migrate away from jinja and maintaining a python install on our administration machines.

There is no syntax highlighting support in vscode for EPS, not like there is for Jinja2 (through an extension).

**Proposed technical implementation details (optional)**

The syntax highlighting should use powershell syntax highlighting between template indicators as defined in https://github.com/straightdave/eps it then should use the syntax highlighting of the base file.

This could be based on extensions.  For example, test.xml.eps or test.xml.eps1 should use both powershell and xml syntax highlighting.

**Comment by SydneyhSmith** [comment]
Thanks @Deastrom this is a really interesting concept! We dont have any expertise in this language and likely would not be the right place for us to add this to the extension...instead it would make sense for a separate community extension to support this module (this extension could depend on the PowerShell extension for the intellisense, analysis etc.). In the VSCode API there may be a way to indicate that certain portions of a particular file should be analyzed as a particular language..I am going to close this issue since we dont plan to implement this but feel free to reach out if you plan to build an extension and are looking for some guidance on depending on the PowerShell extension.
