### ISSUE TITLE
PowerShell Preview: Command 'PowerShell: Get details about the PowerShell version that the PowerShell extension is using' resulted in an error (command 'PowerShell.GetPowerShellVersionDetails' not found)

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#3105]
### System Details

System Details Output
```
### VSCode version: 1.52.1 ea3859d4ba2f3e577a159bc91e3074c5d85c0523 x64

### VSCode extensions:
amazonwebservices.aws-toolkit-vscode@1.17.0
arcticicestudio.nord-visual-studio-code@0.15.0
cweijan.vscode-autohotkey-plus@2.6.2
daylerees.rainglow@1.5.2
donjayamanne.githistory@0.6.14
DotJoshJohnson.xml@2.5.1
dracula-theme.theme-dracula@2.22.3
eamodio.gitlens@11.0.6
EliverLara.andromeda@1.7.0
Equinusocio.vsc-community-material-theme@1.4.2
Equinusocio.vsc-material-theme@33.1.2
equinusocio.vsc-material-theme-icons@1.2.0
felipe-mendes.slack-theme@1.9.13
formulahendry.code-runner@0.11.1
hbenl.vscode-test-explorer@2.19.3
icsharpcode.ilspy-vscode@0.9.0
influxdata.flux@0.5.13
johnpapa.vscode-peacock@3.9.1
kenhowardpdx.vscode-gist@3.0.3
littlefoxteam.vscode-python-test-adapter@0.6.5
ms-azuretools.vscode-azurefunctions@1.1.0
ms-azuretools.vscode-docker@1.9.0
ms-dotnettools.csharp@1.23.8
ms-kubernetes-tools.vscode-kubernetes-tools@1.2.1
ms-python.python@2020.12.424452561
ms-toolsai.jupyter@2020.12.414227025
ms-vscode-remote.remote-containers@0.154.1
ms-vscode-remote.remote-ssh@0.62.0
ms-vscode-remote.remote-ssh-edit@0.62.0
ms-vscode-remote.remote-wsl@0.52.0
ms-vscode.azure-account@0.9.4
ms-vscode.cpptools@1.1.3
ms-vscode.powershell@2020.6.0
ms-vscode.powershell-preview@2020.9.0
ms-vsliveshare.vsliveshare@1.0.3375
Nuuf.theme-hackershaze@2.0.1
octref.vetur@0.31.3
redhat.vscode-yaml@0.13.0
ritwickdey.LiveServer@5.6.1
RobbOwen.synthwave-vscode@0.1.8
samrapdev.outrun@0.2.2
Unity.unity-debug@3.0.2
usernamehw.errorlens@3.2.4
vscodevim.vim@1.18.5
webrender.synthwave-x-fluoromachine@0.0.12
ymotongpoo.licenser@1.5.0


### PSES version:

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Issue Description

VSCode displays error message

> Command 'PowerShell: Get details about the PowerShell version that the PowerShell extension is using' resulted in an error (command 'PowerShell.GetPowerShellVersionDetails' not found)

![image](https://user-images.githubusercontent.com/466713/102727250-d4c9c580-42e1-11eb-817e-26c40ae3afff.png)

#### Expected Behaviour

VSCode returns details about the PowerShell version that the PowerShell extension is using.

#### Actual Behaviour

See Issue Description

**Comment by rjmholt** [comment]
This command is one of the three that make up the current (small/WIP) [external APIs](https://github.com/PowerShell/vscode-powershell/blob/master/src/features/ExternalApi.ts).

I need to track down whether the fact that they're unregistered is intentional or not, but basically we need to either:

- Register the ones that make sense for an editor user to call
- Find a way to hide them from VSCode while still exposing them to other extensions (may not be possible)
- Make it so that calling them from the editor shows a nicer error message (may not be possible)

For this particular API, you can get the information it retrieves from the integrated console for now (`$PSHOME` and `$PSVersionTable` should do it).

**Comment by TylerLeonhardt** [comment]
These commands were removed in favor of a much cleaner exported API. An example of how you can take advantage of this is here:

https://github.com/TylerLeonhardt/vscode-pester-test-adapter/blob/master/src/powershellExtension.ts#L21-L23

It's much easier to use the actual language rather than these weird commands that I had originally started with. Since they were only ever added to the preview extension, we were able to break this way.

My dream was to one day ship that file (https://github.com/TylerLeonhardt/vscode-pester-test-adapter/blob/master/src/powershellExtension.ts) in an npm package so it was easier to pull in and you'd get completions and whatnot... but never had time.

**Comment by TylerLeonhardt** [comment]
Looks like I forgot to remove the references here:
https://github.com/PowerShell/vscode-powershell/blob/master/package.json#L350-L364

**Comment by andschwa** [comment]
Just ran into this and was about to open an issue against myself 🤣
