### ISSUE TITLE
No way to do a run with powershell ?

### ISSUE THREAD

**Issue by ElMiguel123** [PowerShell/vscode-powershell#3138]
Good afternoon,
I'm working with Visual Studio code on Windows 10 and I tried a script I have on Visual Studio Code with a breakpoint.
I tried with F5 (RUN) and receive this : 

**PowerShell does not support debugging this file type: 'test.ps'.**

But script work with F8 if I select part of the code.

**Comment by SydneyhSmith** [comment]
Hi @ElMiguel123 it looks like the file may need to be renamed with the `.ps1` file extension as that will indicate it is a PowerShell file , the F8 functionality essentially just copies the selection into the integrated console so that is why it still works even without the correct file extension...thanks!

**Comment by ElMiguel123** [comment]
sorry we can close the incident. My fault. The file is save with extention .ps instead ps1
You right Sidney. Thanks :)
