### ISSUE TITLE
microsoft store installed powershell can not be recognized

### ISSUE THREAD

**Issue by Wongboo** [PowerShell/vscode-powershell#3181]
I used to use powershell delivered by github release, now as I favor the convenience of microsoft-store's integrated update, I switch to powershell in microsoft store.
But then bugs appear:
1. *vscode-powershell* cannot **automatically** recognize microsoft store installed powershell
2. even if I changed “PowerShell Additional Exe Paths” in JSON with the value
  $PSHOME\pwsh.exe which is
 "C:\\Program Files\\WindowsApps\\Microsoft.PowerShellPreview_7.2.2.0_x64__8wekyb3d8bbwe\\pwsh.exe"
 *vscode-powershell* cannot recognize microsoft store installed powershell **as well**

**Comment by Wongboo** [comment]
I tried to change   "terminal.integrated.shell.windows" as well,but no use

**Comment by Softgrider** [comment]
This happens since updated to Visual Studio Code Version 1.53. 
Uninstall Store Version and install msi Version brings the powershell 7.1.x back

**Comment by rjmholt** [comment]
The logic to automatically pick up a store installation is here:

https://github.com/PowerShell/vscode-powershell/blob/7f0b9696d74a6813253ff54f3d64eabd3465b68e/src/platform.ts#L262-L290

It's not clear why this would suddenly fail, especially due to a VSCode update (since that shouldn't update anything within the extension itself).

It's also mysterious why giving an explicit absolute path would also fail -- that's effectively a bypass for the PowerShell-finding logic and should work no matter where it's pointed (as long as that's a valid PowerShell executable).

**Comment by SydneyhSmith** [comment]
Thanks @Softgrider just to clarify did this issue not occur for you before 1.53? Thanks @Wongboo for the bug report

**Comment by rjmholt** [comment]
So we've now had a second report of this, and I'm wondering if there's a permissions issue or similar going on -- hopefully we can reproduce this locally to investigate

**Comment by wjvii** [comment]
@rjmholt I can confirm the same behavior here as well.

**Comment by rjmholt** [comment]
So it looks like this is due to [`fs.existsSync` returning false for symlinks](https://stackoverflow.com/questions/23253332/check-if-a-symlink-exists-in-node-js), causing this to be false here:

https://github.com/PowerShell/vscode-powershell/blob/ce41617eb6eb10cb41b9d6076593490617267e59/src/platform.ts#L494

It's not clear why this previously worked, but either node or Windows/the store has changed its behaviour here.

We need to update this check to be something like:

```typescript
try {
    fs.lstatSync(this.exePath);
    this.knownToExist = true;
} catch {
    this.knownToExist = false;
}
```

Or alternatively do a readlink operation to resolve the link...
