### ISSUE TITLE
The term 'Register-EditorCommand' is not recognized...

### ISSUE THREAD

**Issue by johncwelch** [PowerShell/vscode-powershell#3198]
<!--

### System Details

<!--
To help diagnose your issue, the following details are helpful:
- Windows 10 Enterprise 1809
- VS Code version: 1.54.0-insider (user-setup)
- PowerShell extension version: this happens with both 2020.6.0 and preview version 2020.9.0
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Issue Description

I am trying to add custom commands to vscode via Register-EditorCommand, but it is erroring out on load. The profile script is signed.

#### Expected Behaviour

The items I added to the profile script with Register-EditorCommand work

#### Actual Behaviour

I get: 

Register-EditorCommand : The term 'Register-EditorCommand' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.

### Attached Logs

attached in logs.zip file

**Comment by johncwelch** [comment]
tried to attach zipped logs file, doesn't seem to like that.

**Comment by SydneyhSmith** [comment]
Thanks @johncwelch could you please provide detailed reproduction steps including a screenshot/GIF of what you are experiencing, thanks! 
(looks like nothing came through the first time) 
![image](https://user-images.githubusercontent.com/43417619/108912725-e11e1780-75dd-11eb-8702-19e6e8015a68.png)

**Comment by rjmholt** [comment]
In particular, which terminal are you running in, the Integrated Console or the PowerShell console. Compare the below:

![image](https://user-images.githubusercontent.com/7009879/108912721-e0858100-75dd-11eb-86b9-1cfd1cd36502.png)

![image](https://user-images.githubusercontent.com/7009879/108912870-10cd1f80-75de-11eb-8ace-9772ca962411.png)

**Comment by johncwelch** [comment]
Okay, so the error is happening when I start vscode, specifically on my profle file: \\networkpath\networkpath\username\WindowsPowerShell\Microsoft.PowerShell_profile.ps1

In that file I have two statements:

Register-EditorCommand -Name SignCurrentScript -DisplayName 'Sign Current Script' -ScriptBlock {
    $signToolPath = "c:\Program Files (x86)\Windows Kits\10\App Certification Kit\signtool.exe"
    $certFingerPrint = "63747bd98eab349eb6a97faceb98347e306f9bb6"
    $trURL = "http://timestamp.entrust.net/TSS/RFC3161sha2TS"
    $currentFile = $psEditor.GetEditorContext().CurrentFile.Path
    $argList = " sign /sha1 " + $certFingerPrint + " /tr " + $trURL +  " /fd sha256 `"" + $currentFile + "`" "
    Start-process -FilePath $signToolPath -ArgumentList $argList -NoNewWindow -Wait
}

Register-EditorCommand -Name "Helpers.EditVSCodeProfile" -DisplayName "Edit VSCode Profle" -ScriptBlock {
    param([Microsoft.PowerShell.EditorServices.Extensions.EditorContext] $content)
    $psEditor.Workspace.OpenFile("\\networkpath\networkpath\username\WindowsPowerShell\Microsoft.PowerShell_profile.ps1")
}


As soon as staart vscode with those statements, I get:

Register-EditorCommand -Name SignCurrentScript -DisplayName 'Sign Cur ...
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Register-EditorCommand:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Register-EditorCommand : The term 'Register-EditorCommand' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.
At \\networkpath\networkpath\username\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:1 char:1
+ Register-EditorCommand -Name SignCurrentScript -DisplayName 'Sign Cur ...
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Register-EditorCommand:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Register-EditorCommand : The term 'Register-EditorCommand' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.
At \\networkpath\networkpath\username\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:10 char:1
+ Register-EditorCommand -Name "Helpers.EditVSCodeProfile" -DisplayName ...
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Register-EditorCommand:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

If I run that script manually by opening it in VSCode and running it, no errors.

within the console, i have two options: powershell and Powershell integrated console. If I run gcm register-editorcommand in powershell, i get the "command not recognized" error. 

If I run gcm register-editorcommand in the Powershell integrated console, i get CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Register-EditorCommand                             0.2.0      PowerShellEditorServices.Commands

so I'm not sure what's happening. If I have the same two register-editorcommand statements in \\networkpath\networkpath\username\WindowsPowerShell\Microsoft.VSCode_profile.ps1, and I move the Microsoft.PowerShell_profile.ps1 file to my desktop, I don't get the error, but I also still can't use the commands.

**Comment by rjmholt** [comment]
I wonder if this means we're loading the profile before defining the commands

**Comment by rjmholt** [comment]
[Looks like I'm right about that](https://github.com/PowerShell/PowerShellEditorServices/blob/e8fdd91866cb1f9e5c279b24c38a62eb0d782138/src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs#L218-L220).

The fix then is for us to import that module before we load the profiles.

**Comment by johncwelch** [comment]
ah, that makes sense. I'm glad I was able to help.

**Comment by rjmholt** [comment]
Actually I'm not right about it. We queue the module import before we queue profile loading (it's hard to see in the existing logic, because profile loading is done when the configuration is received so we know whether to load it or not).

However, if we can repro this we might be able to debug it at least. If this ends up being a race condition, then it'll be a PowerShell/PowerShellEditorServices#1295 issue I think

**Comment by corbob** [comment]
> Okay, so the error is happening when I start vscode, specifically on my profle file: `\\networkpath\networkpath\username\WindowsPowerShell\Microsoft.PowerShell_profile.ps1`

This looks like it's the Windows PowerShell terminal in VS Code, and not the PowerShell Integrated Console from the extension.

PSIC:
![image](https://user-images.githubusercontent.com/30301021/109069852-9e744200-76a6-11eb-99df-1b26c953c8d1.png)

VSCode terminal:
![image](https://user-images.githubusercontent.com/30301021/109069897-afbd4e80-76a6-11eb-9d94-60f6155700c1.png)

Are you able to use the commands when you switch to PowerShell Integrated Console in the drop down at the top right?

**Comment by rjmholt** [comment]
Oh I missed this bit:

> Okay, so the error is happening when I start vscode, specifically on my profle file: \\networkpath\networkpath\username\WindowsPowerShell\Microsoft.PowerShell_profile.ps1

If you're running anything with `Register-EditorCommand` not in the Integrated Console, it's not going to work. And that profile file is going to be run outside the Integrated Console.

So for example, if you add those lines to your *normal PowerShell profile* (which the PowerShell extension doesn't load) and then open VSCode (so that it runs a `powershell.exe` console), you'll hit this error and that's by design.

You need your `Register-EditorCommand` calls to be in the PowerShell-extension-specific profile (`~\Documents\WindowsPowerShell\Microsoft.VSCode_profile.ps1`), because `Register-EditorCommand` is specific to the PowerShell extension for VSCode. That integration between the editor and the console is what makes the Integrated Console "Integrated".

BTW, if you want to run your normal profile in the VSCode profile, a common thing to do is to dot-source the former at the top of the latter.

**Comment by johncwelch** [comment]
Honestly, no matter where I put it, I can't get it to do the thing I want, which is add the commands to my command palette so I can easily sign scripts and/or edit my profile. Which makes me think the process for doing this is fussy to the point of being unusable by someone not already writing in-depth extension code for VSCode. If i put it where $profile says it should be, which is the network home, doesn't work. If I put it in ~\Documents\WindowsPowershell, doesn't work.

This process, which is not what I would call terribly well-documented only seems to work in a highly narrow range of configurations and use cases, none of which i appear to meet. Given the requirements of my corporate PTB, I am literally incapable of changing this to the thing that VSCode seems to want. Whatever that is.

I am not sure why this is as complicated as it is, but, it is what it is. I would suggest that there should be a ~\Documents\VSCode folder, within which there could be a Script or Scriptlets folder, where one could drop in powershell scripts that do things like this and it should just work. One could then have a dynamic scripts menu that would only be usable when there were scripts within that folder, and each module in the  script, or the entire script if it was only one task would appear in the menu, one could click on it, and the script would run in the proper context.

documenting this kind of process would seem to be much easier than the current process, which doesn't seem to be terribly well documented, and it would seem to be a lot less fragile to say "put that file *there* and it will do the thing" rather than whatever the current process seems to be.

I do appreciate the help, but I think until this process is *much* less fragile, I'll just build my own UI to do this. It won't be as convenient as what I was attempting, but it will have the advantage of working in a consistent manner that is documentable, and that is ultimately more convenient.

thank you again for your help, apologies for wasting your time.

**Comment by rjmholt** [comment]
The profile you want is the value of `$profile` in the Integrated Console -- that's where you need to call `Register-EditorCommand`.

`$profile` is the variable you can inspect to get this information. From there you can use `New-EditorFile $profile` to create and edit that file, or `psedit $profile` to edit it if it already exists.

>  I would suggest that there should be a ~\Documents\VSCode folder, within which there could be a Script or Scriptlets folder, where one could drop in powershell scripts that do things like this and it should just work.

Unfortunately, we can't do that because we're not VSCode, we're an extension to VSCode more closely affiliated with PowerShell (and owned by the PowerShell team).

> One could then have a dynamic scripts menu that would only be usable when there were scripts within that folder, and each module in the script, or the entire script if it was only one task would appear in the menu, one could click on it, and the script would run in the proper context.

I understand why you might feel that's less complicated for you, but the goal of the Integrated Console commands is to provide a TUI for VSCode from PowerShell rather than to extend VSCode's GUI to extend PowerShell.

To be honest with you though, the Integrated Console commands do currently need some work. Because they are all about integration with VSCode and because there aren't currently many users of them, they're not well tested and have suffered as we've refactored other parts of the extension. However, we're still concentrating on improving those core scenarios before we can iron out more advanced scenarios like `Register-EditorCommand`, and really it's once those have been improved that we'd think about documenting them (since they may undergo changes before then).
