### ISSUE TITLE
Include regions in symbol list/outline/breadcrumbs

### ISSUE THREAD

**Issue by theaquamarine** [PowerShell/vscode-powershell#3210]
**Summary of the new feature**

It'd be helpful for navigating large scripts that don't make heavy use of functions if `#region`s were available for navigation on the go to symbol menu, outline, or breadcrumbs like functions etc are now.

**Comment by fflaten** [comment]
Outline is being worked on in #1911 for shortcut-navigation 👍 

Go to symbol: Out of scope in the current PR. Does it make sense to see ex. hundreds of "#region helperfunctions" because you have them in every file?

Breadcrumbs: Out of scope in the current PR. It causes trouble with outline-hierarchy because endregion could be inside ex a function, breaking the hierarchy/nesting in outline. _Maybe possible after we move to `DocumentSymbol`._

Any other languages that have these symbols-features for regions? Haven't seen any myself.

**Comment by andschwa** [comment]
> Maybe possible after we move to newer API (DocumentSymbol).

I think we gotta prioritize doing this. I don't like using a deprecated API, but damn, keeping track of parent/child relationships when building the symbol tables doesn't seem like it'll be easy to get right.

> Go to symbol

This should "just work" unless you explicitly skip them in that logic, no?

**Comment by fflaten** [comment]
> I think we gotta prioritize doing this. 

👍

> keeping track of parent/child relationships when building the symbol tables doesn't seem like it'll be easy to get right.

Tracking parent [should be easy](https://github.com/PowerShell/PowerShellEditorServices/pull/1984#issuecomment-1403213148). Efficiently building the symbol-tree from Parent-reference might be a bit harder. Unless also store a list of children per symbol. Feels redundant, but at the same time, we clear and rescan every symbol on file change so should always be in sync. (Should move this to own issue 🙂 )
  
> > Go to symbol
>  
> This should "just work" unless you explicitly skip them in that logic, no?

Yes. Was intentionally ignored in PR because it felt noisy. That's why I was hoping for feedback here. Maybe it's just me. 🙂

**Comment by andschwa** [comment]
> Go to symbol: Out of scope in the current PR. Does it make sense to see ex. hundreds of "#region helperfunctions" because you have them in every file?

There is actually "Go to Symbol In Editor" which means _only_ the current file (and I think it's fed via `Occurrences` in PSES) so we can do this.

**Comment by fflaten** [comment]
> There is actually "Go to Symbol In Editor" which means _only_ the current file (and I think it's fed via `Occurrences` in PSES) so we can do this.

Good catch! We got that included for free with DocumentSymbolHandler 👍

**Comment by andschwa** [comment]
Resolved!
