### ISSUE TITLE
Commandline Args in launch.json

### ISSUE THREAD

**Issue by tibmeister** [PowerShell/vscode-powershell#322]
So not sure what format these args need to be in, I've tried several including a json array to no avail.  One of the args also has a UNC path so that's fun, takes me back to good ole C++!

Anyway, running Windows 10, Code 1.6.0, POSH Extension 0.7.2.  

Whenever I try to debug I get that lovely error "Debug adapter process has terminated unexpectedly".

**Comment by daviwil** [comment]
Hey Jody, can you paste your launch.json here so we can take a look?

**Comment by rkeithhill** [comment]
Try passing the arguments as a single string.  Also, yes, you have to obey JSON string syntax so `\` have to be escaped.  Keep in mind that PowerShell will accept `/` as a path sep so that might be easier to use.

**Comment by tibmeister** [comment]
So it would be something like 
"args": [
"-Param1 MyParam -ParamUNC \\\\myserver\\folder\\file"
],
So I also tried
"args": [{
"-Param1": "MyParam",
"-ParamUNC": "\\\\myserver\\folder\\file"
}],

**Comment by daviwil** [comment]
I think in your first example you shouldn't enclose the args string inside of square brackets, the "args" value should just be a string.  Can you try that and let us know if it resolves the issue for you?

**Comment by rkeithhill** [comment]
And don't forget that in JSON a `\` has be escaped.  I'd use:
```json
"args": [
"-Param1 MyParam -ParamUNC //myserver/folder/file"
],
```
Unless you are passing that path to a native Windows exe.  The `[]` are required based on our type def of args taking an array.  :-(

**Comment by tibmeister** [comment]
Sorry for not getting back sooner, yes, the "Bash" style path worked like a charm :)
One question, does the debug session run in the overall powershell session as the rest of VSCode or is it different?  There's some pre-work I have to do before I can debug and currently I have to paste this into the debug console for each debugging run.

**Comment by daviwil** [comment]
@tibmeister Glad to hear it worked!  You are correct, the debug session is not the same as the one used for IntelliSense/F8 support.  For script debugging that requires some initial setup, we recommend (for now) that you have a "bootstrapper" script that you set as your "program" in `launch.json` which does the necessary setup and then dot-sources the script you want to debug.  We'll find a better way to enable this in the near future.

Closing this issue now since the initial issue is resolved, please feel free to ask more questions about debugging if you like.
