### ISSUE TITLE
Should have "eval function" and "eval file"

### ISSUE THREAD

**Issue by andschwa** [PowerShell/vscode-powershell#3278]
So we pleasingly have "run selection" which evaluates the selected text in the integrated terminal. This is great, and very Emacs-y! But what is missing to me is "eval function" (or expression) to evaluate the entire surrounding function, and "eval file" (buffer, in Emacs terms) to evaluate the whole file. That way users don't have to reselect text to run.

**Comment by andschwa** [comment]
Related to #3242.

**Comment by andschwa** [comment]
Also I'd like to see what the expected behavior is for Visual Studio Code users, we should look at some other popular extensions and ask someone like @TylerLeonhardt.

**Comment by TylerLeonhardt** [comment]
Running the whole file sounds like debugging the file to me.

That's F5...and you can run it "without debugging" (skipping over breakpoints) using Shift+F5.

The eval function doesn't sound incredibly useful for me because:

1. There are a lot of PowerShell scripts that just run a bunch of cmdlets and don't use functions at all
2. vscode has [Shift+Alt+Right](https://stackoverflow.com/a/37835842) (it might have a different keybinding these days) to select all text between braces and then you can F8 it.
3. Sadly, F8 was hard to discover (even though it's the same keybinding in the ISE) so I worry that Run Function would be equally hard to discover and would require an additional button in the tab bar

**Comment by andschwa** [comment]
Ooh, these helpful to know...thanks @TylerLeonhardt!!!

**Comment by andschwa** [comment]
Tyler's suggestions have fulfilled my needs pretty well for this. I wish there were a better way to eval a function still (i.e. update its definition in the current session for manual testing in the integrated console, without having to manually select the thing and "run selection" it over), but I can usually go to the start of the function and use brace jump to select to the end.
