### ISSUE TITLE
`Connect-ExchangeOnline` fails because `System.Windows.Forms` objects are used

### ISSUE THREAD

**Issue by baldieavenger** [PowerShell/vscode-powershell#3396]
Hi, 
When updating to the latest ExchangeOnlineManagement module, i'm unable to get the pop out to sign in. This works fine with 2.0.3 and in ISE / PowerShell.
Running 5.1 Powershell, 1.56.2 (system setup) Code.
Attached Diagnostic logs when both versions for comparison and a screenshot of the creds pop up Im expecting.
Thanks!
John

[CodeLogs20210604.zip](https://github.com/PowerShell/vscode-powershell/files/6597678/CodeLogs20210604.zip)

**Comment by andschwa** [comment]
Hi, could you also open an issue with the [module's repo too](https://github.com/MicrosoftDocs/office-docs-powershell)?

**Comment by baldieavenger** [comment]
Hi Andrew,
Anything more you need from me to dig into this?
Thanks!
John

**Comment by dariomws** [comment]
Hi @baldieavenger, thank you for your feedback.

I've tested it and it's working for me.

VS Code:
![image](https://user-images.githubusercontent.com/33589238/124098482-e0e6ca80-da5c-11eb-8aed-9c4b9fe8fec8.png)

ISE:
![image](https://user-images.githubusercontent.com/33589238/124098743-1f7c8500-da5d-11eb-8e79-905f3356a095.png)

**Comment by baldieavenger** [comment]
Looks like its due to "System.Windows.Forms"
https://github.com/PowerShell/vscode-powershell/issues/3394#issuecomment-872416633

**Comment by andschwa** [comment]
@baldieavenger your profile and script aside, is this issue alone resolved by the dev preview I had you try? That is, can you run `Connect-ExchangeOnline` in the integrated terminal?

**Comment by andschwa** [comment]
@baldieavenger With the stable extension, I can reproduce the issue where the authentication prompt doesn't open at all from `Connect-ExchangeOnline`. With the dev build and Windows PowerShell, the authentication prompt _does_ open for me in the integrated console. After authenticating, the module takes a looong time to finish, but eventually drops me back at a prompt, presumably having connected. With the dev build and PowerShell 7, instead of a GUI prompt, the module opens the browser for authentication; this still works correctly and then it sits loading for a while but eventually finishes.

So I believe my patch to OmniSharp has resolved the issue with `Connect-ExchangeOnline` in the integrated terminal.

**Comment by andschwa** [comment]
That fix is merged and will be in the next release!
