### ISSUE TITLE
upgrading extension removes custom PowerShell.json

### ISSUE THREAD

**Issue by nExoRek** [PowerShell/vscode-powershell#3408]
### VSCode extensions:
adammaras.overtype@0.2.0
bencoleman.armview@0.4.5
donjayamanne.githistory@0.6.16
formulahendry.code-runner@0.11.4
GitHub.vscode-pull-request-github@0.26.0
mechatroner.rainbow-csv@1.8.1
ms-dotnettools.vscode-dotnet-runtime@1.1.0
ms-vscode.powershell@2021.5.1
msazurermtools.azurerm-vscode-tools@0.15.1
samcogan.arm-snippets@1.4.19

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.1852
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1852
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

System Details Output
```

```

### Issue Description

after upgrading to new version PowerShell.json .vscode\extensions\ms-vscode.powershell-2021.5.1\snippets is a fresh new file. old file has been removed and there is no backup copy, so I've lost many recent changes. 

#### Expected Behaviour
snippet file should be at least backed up, best copied from previous version

#### Actual Behaviour

old extension folder structure is removed.

**Comment by rjmholt** [comment]
I'm not sure we have control over that folder, since we don't have control over how VSCode installs things.

I suspect though that editing things inside an extension folder like that is something that VSCode deliberately won't support or help with, since to it those are just extension assets to pave over for installation.

Instead, I think [user snippets are intended to be stored elsewhere](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets).

Going to close this since:

- The PowerShell extension doesn't control its own installation, VSCode does
- VSCode almost certainly doesn't support user changes to extension assets, so anything we could implement here could be broken by them at any time
- VSCode has a recommended solution for storing user snippets
