### ISSUE TITLE
Do not auto-load module

### ISSUE THREAD

**Issue by potatoqualitee** [PowerShell/vscode-powershell#3457]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I tried finding this, not sure if it's already implemented but is it possible not to auto-load the module that I'm working on? All of my work is done in Windows Terminal and when I switch branches that have DLL changes, I have to close out VS Code too. I just need Integrated Terminal for code formatting.

### Proposed Design

Add option to stop auto-loading modules if it doesn't already exist

**Comment by andschwa** [comment]
Could you please elaborate on what issues you're hitting? My hunch is perhaps your problem with "DLL changes" is file locks due to being on Windows, since you say you're developing in a separate process (presumably `pwsh` in the Windows Terminal). Modules should not be auto-loaded by the extension (and in fact, recently we merged a PR that prevented completions from auto-importing modules too). If you could upload diagnostics logs using the bug template perhaps we could figure out _when_ your modules are being "auto-loaded." Thanks!

**Comment by potatoqualitee** [comment]
> file locks due to being on Windows

Agreed

> since you say you're developing in a separate process (presumably pwsh in the Windows Terminal).

Yes indeed

> If you could upload diagnostics logs using the bug template perhaps we could figure out when your modules are being "auto-loaded." 

Will do. I recall the process taking a bit, so I'll earmark it for tomorrow, and meanwhile, here you can see me switching branches and no PowerShell or pwsh being open -- just VS Code with nothing being typed in the Integrated Terminal. Perhaps that extra powershell terminal is throwing VS Code for a loop? Nothing was typed there either.

![image](https://user-images.githubusercontent.com/8278033/125527228-f2638edd-dcd7-4cab-90ef-b11ceb5dfea2.png)

![image](https://user-images.githubusercontent.com/8278033/125527364-483634f5-0e90-4cec-b919-90d9ecb84c62.png)

**Comment by andschwa** [comment]
Marking this as a duplicate as we're now tracking in the new issue.
