### ISSUE TITLE
Unresolved dependency

### ISSUE THREAD

**Issue by BruceP99166** [PowerShell/vscode-powershell#352]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: Win 10 
- VS Code version: 1.7.2
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:

Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1Evaluate $PSVersionTable in PowerShell and paste the output here

### Issue Description

Seeing an unresolved dependency while attempting to use VS Code to implement Project REST Basic Operations as described in https://dev.office.com/code-samples-detail/11149.

On opening the project folder, VS Code shows an Info line: There are unresolved dependencies from project.json.  Please execute the Restore command to continue.  
Clicking Restore give this error message in Output
	ERROR: Error: spawn dotnet ENOENT
	Done: -4058.

Project folder zip attached.
[Rest Basic Operations.zip](https://github.com/PowerShell/vscode-powershell/files/619813/Rest.Basic.Operations.zip)

Thanks in advance for your attention.

**Comment by daviwil** [comment]
Hey @BruceP99166, it seems like you need to restore your C# project dependencies before you can continue working on that project.  The message you see must be coming from the C# extension.  It seems like you might need to install the .NET Core tools because it's trying to launch the "dotnet" command but not finding it.

If you need further help with this you might try filing an issue at the [C# extension's](https://github.com/OmniSharp/omnisharp-vscode) GitHub repository.  Thanks!
