### ISSUE TITLE
VS Code Formatting Instability

### ISSUE THREAD

**Issue by potatoqualitee** [PowerShell/vscode-powershell#3565]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Hey Andy, as a follow up to my comment on the Community Call thread, this may have resolved the issue: https://github.com/PowerShell/vscode-powershell/issues/3524

On July 22, I presented at a PS UG meeting and my formatting was not working -- as it hadn't been for a couple weeks. Others on the call confirmed they were having the same issues. Here are the issues I encountered:

* I would get alerts that my code wasn't formatted properly, but then VS Code would not format it so I had to manually tab to get my code properly aligned
* Even though I disabled Format on Save, I'd get a popup that it was trying to format which would stay there until I closed it manually
* As I was coding, I'd suddenly see a large chunk of yellow code in my minimap, which usually means -- and this happens every few months perhaps -- that VS Code would copy/paste a huge chunk of code and place it randomly in the file. Sometimes, reopening VS Code helps, but in that case it did not. This was particularly bad the week of August 31st. When closing/reopening does work, there are days that I have to do it every 10 minutes.

Since then, time has passed and I've seen the extension get updated. I've also updated psreadline across the board, no idea if that impacts anything. Either way, so far this week, things are working well and formatting works nicely 🎉

As for my second question about a rewrite: because extension instability is an on-going issue (it's happened regularly for years), it's my assumption that these issues were going to be permanently fixed as part of the rewrite of the VS Code PowerShell extension. Last time I was on a community call, Steve said Extension instability has to do with the underlying engine, Onyx or Ultima or something, and that the extension was being rewritten to use something else. So I was inquiring about timeline for the total rewrite.

### PowerShell Version

```console
Name                           Value                                                    
----                           -----                                                    
PSVersion                      5.1.22454.1000                                           
PSEdition                      Desktop                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                  
BuildVersion                   10.0.22454.1000                                          
CLRVersion                     4.0.30319.42000                                          
WSManStackVersion              3.0                                                      
PSRemotingProtocolVersion      2.3                                                      
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.60.0
e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2021.9.0
```

### Steps to Reproduce

Code PowerShell in VS Code and wait 😅

**Comment by andschwa** [comment]
Hey Chrissy!

Super great to hear things are finally starting to work better ☺️ The PSScriptAnalyzer update was a tremendous collaboration among the team, and I was so happy to be able to pick it up! It seems to have solved a _lot_ of issues for everyone. That said, it clearly has room for improvement, and I'm hoping we can do that work.

As far as the "large chunk" of code randomly moving/pasting...I feel like I know what you're talking about. I've seen similar things happen in both VS Code with other extensions and in Emacs using various LSP plugins. It seems like a bigger issue than just us, and unfortunately it's a _really_ hard one to nail down because it happens so randomly. I hope we can get a repro of this and finally figure it out.

As for the "rewrite" we got _half_ of that done with the move to OmniSharp, and then the subsequent update to OmniSharp itself. However, @rjmholt is still hard at working at the rest of it, which I'll let him fill in after me. We hope to be able to share more at the community call as well.

**Comment by potatoqualitee** [comment]
awesome news all around! thanks so much for the updates 💯

**Comment by potatoqualitee** [comment]
also glad to know that chunks of code thing is not a ps extension problem. hopefully it will get fixed at that level 👍🏼

**Comment by rjmholt** [comment]
Just to follow up here, the work to improve the fundamental issues in how PowerShell is executed in the extension is being done in https://github.com/PowerShell/PowerShellEditorServices/pull/1459. I've just opened https://github.com/PowerShell/PowerShellEditorServices/pull/1574 onto that branch, which implements debugging (which took much much longer than anticipated because PowerShell's debugger is quite complex, especially when remoting).

There are a number of smaller things we need to implement still, but with the debug implementation done we should pretty much be on the home stretch.

**Comment by potatoqualitee** [comment]
fantastic news! Thank you @rjmholt 🥳
