### ISSUE TITLE
Explore platform-specific extension releases

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/vscode-powershell#3567]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

See microsoft/vscode#23251 (comment), VS Code Marketplace now allows extensions to publish different VSIXs for each platform (Windows, Linux, macOS).

This document has all the details:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions

### Proposed Design

I'm thinking that breaking up PSES into its different targets would be a good candidate for this. This would help make the PowerShell extension package even smaller.

I'm even thinking that on non-Windows, you wouldn't need to include any of the Windows PowerShell specific build pieces.

**Comment by isidorn** [comment]
@TylerLeonhardt thanks a lot for creating this.

**Comment by andschwa** [comment]
Hi @TylerLeonhardt and @isidorn,

Thanks for the suggestion, and it’s neat to see VS Code exploring areas such as this. The PowerShell extension fortunately has a very small footprint, less than 20 MB! We’ve recently shrunk it even further by bundling and minifying its JavaScript.

As you know, PowerShell Editor Services fully embraces the .NET Standard cross-platform target framework approach, as does PowerShell itself with its standard library. This has enabled us to reduce the complexity of building, packaging, and releasing by only having one binary to publish. This makes it more reliable and provides a homogenous experience for users as they move across environments.

Since we’re already able to publish a unified extension binary, we don’t think splitting the extension into platform-specific releases is an appropriate investment for us. This is especially true because we have no user complaints about the extension’s footprint (most of which is .NET and PowerShell, which is out of our control regardless of this new option) and because we have many more pressing areas to invest in, such as reliability and test coverage. It would be wonderful to see VS Code improve its testing libraries, esbuild and ECMAScript module support, and backwards-compatibility.

**Comment by TylerLeonhardt** [comment]
I was mostly referring to the contents of the `Desktop` folder which is around 2.7mb. This folder doesn't need to be in the package for non-Windows because it's only for Windows PowerShell.

![image](https://user-images.githubusercontent.com/2644648/133335790-56238ffb-e4b3-4c62-9c92-82e880242bb5.png)

I agree that this issue isn't a high priority issue and I'm certainly not expecting work on it anytime soon. With that said, I think it could theoretically be a straightforward?

* package vsix for windows
* publish for windows
* delete Desktop folder
* package vsix for everything else
* publish for everything else

**Comment by TylerLeonhardt** [comment]
> It would be wonderful to see VS Code improve its testing libraries, esbuild and ECMAScript module support, and backwards-compatibility.

If you have specific issues, don't hesitate to open issues on vscode! I know that that can be a bit painful... part of the reason I never attempted it.

**Comment by TylerLeonhardt** [comment]
reopen?
