### ISSUE TITLE
64-bit PowerShell modules are not being loaded

### ISSUE THREAD

**Issue by alexandrudima** [PowerShell/vscode-powershell#36]
From Microsoft/vscode#714
From @MakwaWes 
CC @daviwil 

Hi,

**Problem**
Some PowerShell modules aren't automatically loaded by 'Microsoft.PowerShell.EditorServices.Host.exe'.
The following path isn't included : '**C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\**'
although it actually reads the x64 counterpart ('C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules').

Thanks !

**Comment by daviwil** [comment]
Hi @MakwaWes, I believe this is happening because the language service process is being launched in 32-bit mode.  Since that's the case, I think the 64-bit modules folder isn't being loaded.  In a future update I'm going to provide a way to change the bitness of the language service process so that modules are loaded from the appropriate location.

**Comment by rkeithhill** [comment]
This was addressed the 0.4.0 release.  

BTW
> reads the x64 counterpart 'C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules'

Is actually the **x86** counterpart.

Anyway, you can select the "PowerShell" debugger to execute a 64-bit debug host adapter on 64-bit windows.  That will load 64-bit modules.  If you need to load x86 (32-bit) modules on a 64-bit OS, select the "PowerShell x86" debugger.
