### ISSUE TITLE
PSScriptAnalyzer module version support

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/vscode-powershell#365]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: Windows 10
- VS Code version: 1.7.2
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
### Issue Description

Checking the modules folder for this extension, PSScriptAnalyzer shows as 1.7.0. Which corresponds to the last release for this extension (September release, release of analyzer was August). Just wondering how updates to the dependent module will be handled for this extension. 

With use of a module that maintains releases outside of this extension, is it possible to include some override (via settings.json) that would allow us to tell the extension to use the module we installed from the PS Gallery? Outside of that would require a release each time one is [issued for the analyzer module](https://github.com/PowerShell/PSScriptAnalyzer/releases).

### Attached Logs

N/A

**Comment by daviwil** [comment]
Hey Shawn, thanks for the suggestion!  We've been working toward this for a while, actually.  The ultimate goal is to have PSScriptAnalyzer plug into the PowerShell extension without there being a direct dependency on a specific PSScriptAnalyzer version.  This would allow you to get the benefits of any new updates to PSScriptAnalyzer without requiring an equivalent update to the PowerShell extension.

Since we're tracking this work at issue #360, I'll close this issue in favor of that one.  You can subscribe to that issue to be notified when we make more progress on it (hopefully in the January release).
