### ISSUE TITLE
Automatic variables are not available in the debug console

### ISSUE THREAD

**Issue by Andy-AO** [PowerShell/vscode-powershell#3711]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Automatic variables are not available in the debug console, e.g. `$args`, but you can see it in the automatic variables on the debug pane.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.62
```

### Extension Version

```console
2021.10.2
```

### Steps to Reproduce

```PowerShell
        function Combine {
            param (
                [string]$str
            )
            $PsBoundParameters.Values + $args
        }
        Combine a b c | Should -Be 'a', 'b', 'c'
```

Place the breakpoint on the first `$PsBoundParameters.Values + $args`

`$args` is empty on the console

### Visuals

![](https://cdn.jsdelivr.net/gh/Andy-AO/GitHubPictureBed/img/20211205081104.png)

**Comment by JustinGrote** [comment]
@Andy-AO I'm pretty sure this is actually a PowerShell thing, not a vscode thing. Items like `$PSScriptRoot` and `$args` you can't reference when at a breakpoint from the console. We are however able to pull them from the debugging info and that's why they show up there.

![image](https://user-images.githubusercontent.com/15258962/150812641-9f243493-a98d-4e90-80ac-6da7cab90b34.png)

I would say this behavior would need to be fixed in PowerShell rather than trying to shim it in here with some sort of synthetic re-hydration into the console.

I am blocking this issue as dependent on new PowerShell issue https://github.com/PowerShell/PowerShell/issues/16795

**Comment by andschwa** [comment]
Marking as resolved since this is a PowerShell behavior, not exclusive to the extension.
