### ISSUE TITLE
Adopt the pre-release extension feature

### ISSUE THREAD

**Issue by isidorn** [PowerShell/vscode-powershell#3716]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

Refs: https://github.com/microsoft/vscode/issues/15756

VS Code now supports pre-release extensions. Docs that should help: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions

I know powershell has a separate powershell preview extension. Ideally we would deprecate that extension and you would publish pre-release versions. VS Code can migrate your users automatically once you do the adoption.

Let me know what you think. 

fyi @TylerLeonhardt

**Comment by andschwa** [comment]
We've got this on our radar, but question for you @isidorn: I know VS Code now supports this, but isn't the marketplace still working on full support (especially around supporting extensions to publish with proper semantic versioning, with the necessary pre-release suffixes)? I looked and can't find the issue for the latter, but it's a long open one.

**Comment by isidorn** [comment]
@andschwa yes, MP is working on supporting full semver versioning. However since the MP is currently in the process of changing their backend infrastructure this will probably take some time. My very very rough estimate, end of 2022 at the earliest.
Here's the issue on the MP side https://github.com/microsoft/vsmarketplace/issues/50

**Comment by andschwa** [comment]
Cool, thanks! I'll keep an eye on that and when this is fully supported we'd love to do it.

**Comment by JustinGrote** [comment]
@andschwa why is https://github.com/microsoft/vsmarketplace/issues/50? At least since the updated CI and the CalVer versioning, we don't use any semver suffixes in the published packages, and we only use 3 octets so if you wanted to clearly distinguish Preview from stable, the fourth octet could be used e.g. 2022.02.0.4

**Comment by andschwa** [comment]
We use `-preview` suffix for the preview releases, and that's explicitly what marks them as newer (and not stable), and is what their implementation seems to require as well.

**Comment by JustinGrote** [comment]
@andschwa I did some more thinking on this, why not just append .1 as the forth octet to every preview release? Then just have to make sure a preview always goes out with the stable on releases (which they do today)

For instance:

2022.02.1.1 - Prerelease
2022.02.1 - Stable

2022.02.2.1 - Prerelease
2022.02.2 - Stable

2022.03.0.1 - Prerelease
2022.03.0 - Stable

etc.

**Comment by TylerLeonhardt** [comment]
Unfortunately, I don't think npm likes that forth octet :( it's really annoying... any the marketplace doesn't support `-blah`

**Comment by JustinGrote** [comment]
@TylerLeonhardt right, just trying to think of a workaround for the prerelease tag.

**Comment by andschwa** [comment]
@SydneyhSmith Assigned to you for investigation!

**Comment by andschwa** [comment]
I'm pretty sure the versioning issue is sorted out since we no longer maintain two long separate tracks. We really have one extension, and the preview is just exactly that, an early preview of what's planned to go into the stable extension as long at isn't broken. So we don't need full SemVer support any more, and can just use our existing versions like `2023.3.0` with `preview: true` in the `package.json` (and `--pre-release` for `vsce` when packaging and publishing). Additionally it'll be absolutely fine that when we roll preview to stable (just by switching to `preview: false`) that preview users will get the stable installed...it will technically be the newest, and the docs say those users will get the next preview when we push it. So we're on our way to supporting this!

**Comment by JustinGrote** [comment]
Makes sense to me!

**Comment by isidorn** [comment]
Awesome! Love seeing this ❤️ 

We have a mechanism in VS Code for transitioning existing users of "PowerShell Preview" to the new "PowerShell Pre-Release". Sydney and me are discussing to enable this.

**Comment by andschwa** [comment]
@JustinGrote I don't see any `deprecated` field in the extension manifest, but I believe that @isidorn and the VS Code team are handling this in the backend. Thanks very much all!

FYI @TylerLeonhardt I need to update the docs, but we actually need to keep `preview: true` in the manifest for our pre-release versions because it's the way we determine during packaging and releasing that we need to pass `--pre-release` to `vsce`. Since we have to drop the `-preview` suffix from the version, there doesn't seem to be any other good way to determine from the sources (well, unless we check the changelog but that's hairier) if it's a pre-release version. So, that's why the flag is staying!

**Comment by JustinGrote** [comment]
> @JustinGrote I don't see any `deprecated` field in the extension manifest, but I believe that @isidorn and the VS Code team are handling this in the backend. Thanks very much all!

Oops you are right, this is a backend thing
https://github.com/microsoft/vscode-discussions/discussions/1

**Comment by andschwa** [comment]
I don't think so, it's embedded in the VSIX isn't it? So it's already been created and signed. It'd be a heck of a hack to unzip it, edit the `package.json` and rezip it (and that might break whatever the signing is) just to avoid a little "preview" banner.

**Comment by TylerLeonhardt** [comment]
Oh do you unzip the VSIX in order to check the preview?

**Comment by andschwa** [comment]
No, I check it from the sources that exist next to it in the pipeline (from the ADO checkout step). But to change it "right before the publish" as you suggest would entail editing the VSIX, no? Since `vsce` takes a `--package-path` to the VSIX file?

Anyway, we do need to revisit it because it appears that the marketplace web page like [here](https://marketplace.visualstudio.com/items?itemName=ms-vscode.powershell) shows the assets from the most recent release (even if it was "pre-release") meaning that page shows the "preview" tag and the "preview" icon (which only exist in the pre-release version of the extension). Is this perhaps something that could be fixed upstream? I.e. code the marketplace webpage to display information from the most recent non-pre-release upload? The "version" and "last updated" on the side also are from the pre-release upload, not the stable one.

**Comment by TylerLeonhardt** [comment]
> No, I check it from the sources that exist next to it in the pipeline (from the ADO checkout step). But to change it "right before the publish" as you suggest would entail editing the VSIX, no? Since vsce takes a --package-path to the VSIX file?

In this case, maybe set it to false before packing the VSIX and then set it back to true... or just use an Azure DevOps pipeline variable that you could read later.

**Comment by isidorn** [comment]
I acknowledge this bug on the Marketplace side.
For this to be fixed either Marketplace has to be aware of pre-release extensions or to introduce SemVer support. I do not think either will happen this year, but hopefully some time in 2024.

My suggestion - consider just removing the "preview" tag in both cases.

**Comment by andschwa** [comment]
All right, all right. I'll find another way to pass the pre-release info along from build to package to publish, and will temporarily stop changing the icon to the PowerShell Preview icon (but it's so cute).
