### ISSUE TITLE
Using a launch configuration with interactive arguments does not work correctly in Powershell preview extension

### ISSUE THREAD

**Issue by Hetshu** [PowerShell/vscode-powershell#3770]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

Using a launch configuration like
```json
{
            "name": "Current File w/Args",
            "type": "PowerShell",
            "request": "launch",
            "script": "${file}",
            "args": [
                "${command:SpecifyScriptArgs}"
            ],
            "cwd": "${file}"
},
``` 
and starting the debugger in a powershell script tab with F5 and adding the following arguments in the following popup  
![image](https://user-images.githubusercontent.com/50502257/150013337-b4f0b337-0f91-4b97-aa19-e16d18042f6c.png)

results in the following terminal output
![image](https://user-images.githubusercontent.com/50502257/150013439-7da40277-9d6f-452b-969d-99711c1ea135.png)
if running this with Powershell Preview extension.

This prevents the powershell script to parse the supplied parameters correctly.

### Erroneous  behavior:
![image](https://user-images.githubusercontent.com/50502257/150014854-cb4c7b95-f1bd-466b-acfe-d8c944e564e2.png)

### Expected behavior: (screenshot from working non preview powershell extension)
![image](https://user-images.githubusercontent.com/50502257/150014602-515c796b-4f67-49a9-961f-93810efc7349.png)

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2022.1.0
```

### Steps to Reproduce

see above in the summary

**Comment by andschwa** [comment]
Thanks for getting this filed @Hetshu!

**Comment by andschwa** [comment]
So I dug into this a bit and...my conclusion is that we can't support multiple arguments via `specifyScriptArgs` any more because of an upstream [VS Code](https://github.com/PowerShell/vscode-powershell/issues/1315) change in [2018](https://github.com/PowerShell/vscode-powershell/pull/1317). The command can _only_ return a string, which means that when specified in `launch.json` as `"args": ["{command:specifyScriptArgs"]` we only ever get a single-element array, e.g. `["every, thing; you specified, here"]`. This "bug" manifested because we're now correctly escaping arguments given in the args array, so no matter what you input in the prompt box, a single string element is given to the debugger. This is the given API from VS Code. @SeeminglyScience @JustinGrote @SydneyhSmith @StevenBucher98 I propose we deprecate `specifyScriptArgs` as this behavior is confusing and not supported by the editor itself. We _could_ have `specifyScriptArg` (note, not plural) but is there any real value in that?

**Comment by andschwa** [comment]
After reviewing the existing examples, while we think we should document that the expect usage is `["an", "array", "of", "string", "args"]` (which is the schema for `launch.json` and is what e.g. the Python extension documents) we're going to revert the change made last November to "helpfully" add quotes around arguments with spaces in them. This will allow a `["string space separated string with multiple args"]` to work because we'll be passing the user's raw arguments, but we're also going to change the documentation because that's not the _right_ way to do it (but will enable `specifyScriptArgs` to keep working).

**Comment by andschwa** [comment]
Fixed via https://github.com/PowerShell/PowerShellEditorServices/pull/1702.
