### ISSUE TITLE
Using F8 causes the code editor to lose cursor/selection focus so F8 cannot be used again to run the same code

### ISSUE THREAD

**Issue by ALIENQuake** [PowerShell/vscode-powershell#3887]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/master/SECURITY.md).

### Summary

Hi,

Using F8 causes the code editor to lose cursor/selection focus so F8 cannot be used again to run the same code.

### PowerShell Version

```console
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22579
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.65.2
c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
x64
```

### Extension Version

```console
ms-vscode.powershell-preview@2022.3.0
```

### Steps to Reproduce

1. Select code
2. Press F8
3. Press F8 again, no code is executed

**Comment by andschwa** [comment]
I believe this is by design: it moves the focus to the terminal because it's executed code in the terminal (which may require user input). So I think is more of a feature request to add the ability to configure if the focus should change or not. In fact, if the integrated console is _not_ the current terminal, it looks like we already have some logic to respect VS Code's own setting `focusConsoleOnExecute`:

https://github.com/PowerShell/vscode-powershell/blob/db40d973ace14f4b1286341e992e7a385b88419e/src/features/Console.ts#L204-L245

**Comment by SydneyhSmith** [comment]
thanks @ALIENQuake does the setting `"powershell.integratedConsole.focusConsoleOnExecute": false,` resolve this for you?
