### ISSUE TITLE
Enable the use of the spacebar to enable/disable PSScriptAnalyzer rules in dropdown

### ISSUE THREAD

**Issue by adbertram** [PowerShell/vscode-powershell#402]
**Please fill in these details so that we can help you!**

### System Details

- Operating system name and version: MacOS Sierra
- VS Code version: 1.8
- PowerShell extension version: 0.8.0
- Output from `$PSVersionTable`: PSv6 alpha 13

When invoking PowerShell: ScriptAnalyzer Rules from the settings menu, it would be nice to be able to enable/disable each rule by arrowing up and down and hitting spacebar to change the status.

**Comment by daviwil** [comment]
This is also something that VS Code controls as part of the showQuickPick API.  They prioritize any keys other than <kbd>Enter</kbd> as input because typing allows you to filter the selections.  You might be able to file an issue at their repo to ask about it but my assumption is that they'll want to keep it as-is.
