### ISSUE TITLE
RFC: Rename of the extension's Integrated Console

### ISSUE THREAD

**Issue by andschwa** [PowerShell/vscode-powershell#4053]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I am proposing that we rename the PowerShell Extension's "Integrated Console" (often abbreviated PSIC) to...something else, because VS Code already uses the term "integrated" twice, once for the "[Integrated Terminals](https://code.visualstudio.com/docs/editor/integrated-terminal)" and again for their "[Shell Integration](https://code.visualstudio.com/docs/editor/integrated-terminal#_shell-integration)" feature. So if we have to talk about the latter, it goes something like this: "VS Code's Shell Integration doesn't work in the (PowerShell Extension's) Integrated Console despite it being a (VS Code) Integrated Terminal."

### Proposed Design

Maybe just "Extension Terminal" or "The Extension's Terminal." We need to workshop this. Suggestions solicited!

**Comment by andschwa** [comment]
Made an issue @SydneyhSmith!

**Comment by panekj** [comment]
`PSEditorServices console`?

**Comment by dragonwolf83** [comment]
Some ideas off top of my head

- PowerShell Editor
- PowerShell Editor Services
- PowerShell Extension

Do we need to have Console in the name, it is implied since it is in a Terminal dropdown? With it included it is longer:

- PowerShell Editor Console 
- PowerShell Editor Services Console
- PowerShell Extension Console

Would it make sense to have PowerShell name be dynamic based on if its pwsh version or powershell? For example, pwsh editor when its pwsh. Or does that make it more confusing for people?

**Comment by JustinGrote** [comment]
`PowerShell Extension Console` or just `PowerShell Extension` is the best I've seen, it clearly communicates to the user the purpose, they don't need to know the details about PSES. I am leaning towards the latter because `Console` is already implicit as its in the terminal area.

**Comment by andschwa** [comment]
Wow, it's so simple...I really like `PowerShell Extension` as the label on the terminal too. And then in documentation we can refer to it as the `PowerShell Extension Terminal`

**Comment by SeeminglyScience** [comment]
How about "The right one" so when troubleshooting we can say "are you sure you're using the right one?"

jk I also like `PowerShell Extension`
