### ISSUE TITLE
Powershell terminal completion doesnt work with hints

### ISSUE THREAD

**Issue by quasarea** [PowerShell/vscode-powershell#4084]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

For a month I keep getting mismatches between hints and completion in the powershell terminal.

I start typing, I get the hint, I try to complete it, and end up with something totally different as a result. I tried all kinds of key combinations, but nothing worked.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
x64
```

### Extension Version

```console
ms-vscode.powershell@2022.6.3
```

### Steps to Reproduce

start typing, 
get prediction
try to complete it

### Visuals

![mstsc_Jbo227EoxC](https://user-images.githubusercontent.com/10334982/179486303-b0ea974d-189b-4bd9-a0e6-383678cbae77.gif)

**Comment by SeeminglyScience** [comment]
Predictions and tab completion are different systems. I believe the default key to accept a prediction is the left arrow, but you can set it to whatever you'd like by putting this in your `$profile`:

```powershell
Set-PSReadLineKeyHandler -Chord 'ctrl+.' -Function AcceptSuggestion
```

Side note, this is a PSReadLine feature. We just ship with a more recent version than what is provided inbox.

**Comment by quasarea** [comment]
oh, it is the right arrow for me, thanks, I was going mental. Is there documentation about this and other keys to managing suggestions?

The command you provided when executed in the terminal did not change the key to ctrl+. combination, even after reloading, so maybe it's not working yet. A bit odd that it's not configurable/synced with vscode suggestion keys

**Comment by SeeminglyScience** [comment]
> oh, it is both the up arrow or the right arrow for me, thanks, I was going mental. Is there documentation about this and other keys to managing suggestions?

This kind of goes over it a little [`Set-PSReadLineOption.md#-predictionsource`](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.2/PSReadLine/Set-PSReadLineOption.md#-predictionsource). There's probably something better but I'm not 100% on that.

> The command you provided when executed in the terminal did not change the key to ctrl+. combination, even after reloading, so maybe it's not working yet.

So configuring keys between VSCode and PSReadLine is a little tricky because VSCode decides what it will  actually pass to the underlying terminal. `ctrl + .` was a bad example because VSCode already handles it, but you can set `terminal.integrated.sendKeybindingsToShell` and `terminal.integrated.commandsToSkipShell` in settings to configure it.

> A bit odd that it's not configurable/synced with vscode suggestion keys

Well so they're different concepts for the most part. The predictions are typically based on history (the default) with some optional plugins you can install for completion based predictions or ML based predictions. But they are not actually implicitly tied to the same system as completion results, so tying them to the same keys wouldn't really work too well.

Also PSReadLine is just a module that ships with PowerShell. You can update it in 5.1 and get the same behavior outside of VSCode. Or use the latest version of PowerShell 7 and get it by default. It's not really a VSCode thing, we just happen to depend on a newer version of PSRL so we include it by default.
