### ISSUE TITLE
CTRL+scroll to resize terminal

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/vscode-powershell#4289]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

I'd like to be able to CTRL+scroll to resize text in the integrated terminal for vscode-powershell in Visual Studio Code.

Probably related to, or even up to, VSCode to implement. Related issue:

* https://github.com/microsoft/vscode/issues/76381

I'm creating this feature request in case vscode-powershell can do something in their extension.

### Proposed Design

I'd like to have two different options here:

* Terminal text size linked to editor text size, like PowerShell ISE.
  * CTRL+scroll either terminal or editor resizes both.
* Terminal text resizes independent from editor.

**Comment by andschwa** [comment]
To my best understanding, there's nothing we can do on the extension side here as we create and use the terminal via VS Code APIs, specifically `vscode.Terminal`, so that issue you linked is the best bet.

https://github.com/PowerShell/vscode-powershell/blob/104c0a80ba4e669a200a719d58477ed65afa5c09/src/process.ts#L102-L113
