### ISSUE TITLE
Support VS Code 'Set Log Level'

### ISSUE THREAD

**Issue by juvtib** [PowerShell/vscode-powershell#4441]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.

### Summary

VS Code version 1.76 has a "Developer: Set Log Level..." command. I tried using the command while I had a PowerShell project loaded. But I did not see an explicit option for the PowerShell extension. I'm not sure if the extension outputs to a generic log or if the PowerShell extension should be represented on this list. 

![Screen capture of VS Code log menu. There is no menu item for the PowerShell extension.](https://user-images.githubusercontent.com/51273929/222677600-a76c44a9-88e5-404d-a117-1bbc3258985d.png)

'Set Log Level' seems like a useful command. Please take a look at it and see if the PowerShell extension can support this VS Code command. 

## References 

* [Set Log Level | Visual Studio Code February 2023](https://code.visualstudio.com/updates/v1_76#_configure-default-log-level)
* [Logs | Troubleshooting Guide](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md#logs)

**Comment by JustinGrote** [comment]
Thanks for the Issue Submit!

So this is a fairly new API that logging has to be explicitly written for:
https://code.visualstudio.com/updates/v1_73#_log-output-channel

The PowerShell extension has its own logger implementation and would need to be updated for this new API. 
https://vscode.dev/github/powershell/vscode-powershell/blob/019a9f8cf8509eaffff994af82b804b39e19d883/src/logging.ts#L49 

And then wired up so that `writeAtLevel` and `writeLine` and related code paths submit properly to the output channel api, then the existing log level setting would need to be retired.

**Comment by juvtib** [comment]
Thanks for taking a look at it. 

For reference, here is that logging line without Visual Studio Code for the Web. 
https://github.com/PowerShell/vscode-powershell/blob/019a9f8cf8509eaffff994af82b804b39e19d883/src/logging.ts#L49

**Comment by JustinGrote** [comment]
Working on this in https://github.com/PowerShell/vscode-powershell/pull/5065 but there's some upstream vscode bugs I need addressed.
