### ISSUE TITLE
Debugger not showing value of variables

### ISSUE THREAD

**Issue by weinand** [PowerShell/vscode-powershell#452]
_From @EHBrant on January 19, 2017 13:27_

- VSCode Version: Code - Insiders 1.9.0-insider (215a0af33046d3940e665d46ecaeac9623f2f769, 2017-01-19T07:12:16.209Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.8.0|

---

Steps to Reproduce:

Hello,
I am new to VS Code and want to use it to write/debug PowerShell scripts.  I normally use PowerGUI IDE for PowerShell, but want to move over to VS Code.

A simple but very useful feature in PowerGUI is the ability to see the value and type of any variables once they have been populated. Therefore if you write and execute some simple code like the following

$A = 10
$B = 1,2,3,4

once executed you can hover over the variable in question with your mouse and it will tell you the TYPE and current value/s of the variable.

I do not see this in VS Code and when using the debugger the variables pane (top left) is blank e.g. it also does not list any variables or their values.

It this because the PowerShell extension simply does not support this? 

Being able to see the current value (if any) of any variables in your script (once executed once) is a must have I would say otherwise it makes it very difficult indeed to debug a script.

Also if I set a break-point and start the debugger, the only option I get is to 'stop' the debugger and when I do I receive the following error: Debug adapter process has terminated unexpectedly
again I do not see the value of any variables.

Please advise
Thanks in advance
ErnestBrant@outlook.com

_Copied from original issue: Microsoft/vscode#18783_

**Comment by weinand** [comment]
This is the PowerShell extension. Moving.

**Comment by daviwil** [comment]
Hi Ernest, sounds like you might have hit a bug because all of this should be working.  First of all I'd recommend upgrading to the 0.9.0 version of the PowerShell extension which just got released yesterday.  Next, capture verbose logs by [following these instructions](https://github.com/PowerShell/vscode-powershell#reporting-problems) and post them here or send them to me directly at `daviwil at microsoft.com`.

**Comment by EHBrant** [comment]
OK Thanks will do


________________________________

**Comment by wathnai** [comment]
Hi guys,

Same error here Vs Code version 1.13.1 and Powershell 1.4.1. i tried to reinstall but unsuccessful.

**Comment by rkeithhill** [comment]
I can't repro this:
![image](https://user-images.githubusercontent.com/5177512/27847689-87cbd7c0-60fc-11e7-84e3-d144352b4e14.png)
@wathnai can you provide some details on how to repro this?  Along with the version of the PowerShell extension you're using as well as the VSCode version.  Thanks!

**Comment by rkeithhill** [comment]
@wathnai Looking through your debug logs I don't see anywhere that you have started the debugger.  You won't see the value of variables unless you press F5 to start the debugger.  Make sure the file you're editing has a `.ps1` extension (save it to disk to give it a .ps1 extension).  Set a breakpoint on one of the lines in the script (press F9 to toggle breakpoints).  Then press F5 to start the debugger.

**Comment by wathnai** [comment]
Hi Keith,


My apologizes, i realize i did not save the script so that the reason that the variables don't appear.


Thanks for your support.


Regards


________________________________
De: Keith Hill <notifications@github.com>
Enviado: miércoles, 5 de julio de 2017 5:13
Para: PowerShell/vscode-powershell
Cc: wathnai; Mention
Asunto: Re: [PowerShell/vscode-powershell] Debugger not showing value of variables (#452)


@wathnai<https://github.com/wathnai> Looking through your debug logs I don't see anywhere that you have started the debugger. You won't see the value of variables unless you press F5 to start the debugger. Make sure the file you're editing has a .ps1 extension (save it to disk to give it a .ps1 extension). Set a breakpoint on one of the lines in the script (press F9 to toggle breakpoints). Then press F5 to start the debugger.

**Comment by daviwil** [comment]
No problem wathnai!
