### ISSUE TITLE
$PROFILE modified after extension is installed

### ISSUE THREAD

**Issue by brunoborges** [PowerShell/vscode-powershell#4612]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [ ] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

I have been developing this PS function to enable it on my profile. Following a VS Code recommendation, I installed the PowerShell Extension, only to realize a lot later that `$PROFILE` had been modified.

The PowerShell extension changes the behavior and settings of my VS Code without warning. I really want to continue using the same PowerShell in VS Code as I use in the Windows Terminal.

### PowerShell Version

```console
PS C:\Users\brborges> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.3
PSEdition                      Core
GitCommitId                    7.4.0-preview.3
OS                             Microsoft Windows 10.0.25352
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\brborges>
```

### Visual Studio Code Version

```console
PS C:\Users\brborges> .\code --version
1.78.2
b3e4e68a0bc097f0ae7907b217c1119af9e03435
x64
```

### Extension Version

```console
PS C:\Users\brborges> .\code --list-extensions --show-versions | Select-String powershell

ms-vscode.powershell@2023.6.0
```

### Steps to Reproduce

From the Windows Terminal:

        PS C:\Users\brborges> $PROFILE
        C:\Users\brborges\OneDrive - Microsoft\Documents\PowerShell\Microsoft.PowerShell_profile.ps1

From the PowerShell Terminal inside VS Code (with the PS extension installed): 

        PS D:\projects\JDKMon> $PROFILE
        C:\Users\brborges\OneDrive - Microsoft\Documents\PowerShell\Microsoft.VSCode_profile.ps1

From the PowerShell Terminal inside VS Code (**without** the PS extension):

        PS C:\Users\brborges> $PROFILE
        C:\Users\brborges\OneDrive - Microsoft\Documents\PowerShell\Microsoft.PowerShell_profile.ps1

**Comment by andschwa** [comment]
The `$PROFILE` variable is actually more complex than it looks, try this:

```
$PROFILE | Get-Member -Type NoteProperty
```

In the Extension Terminal on macOS I get the following _profiles_:

```
> $PROFILE | Get-Member -Type NoteProperty   

   TypeName: System.String

Name                   MemberType   Definition
----                   ----------   ----------
AllUsersAllHosts       NoteProperty string AllUsersAllHosts=/usr/local/microsoft/powershell/7/profile.ps1
AllUsersCurrentHost    NoteProperty string AllUsersCurrentHost=/usr/local/microsoft/powershell/7/Microsoft.VSCode_profile.ps1
CurrentUserAllHosts    NoteProperty string CurrentUserAllHosts=/Users/andschwa/.config/powershell/profile.ps1
CurrentUserCurrentHost NoteProperty string CurrentUserCurrentHost=/Users/andschwa/.config/powershell/Microsoft.VSCode_profile.ps1
```

In a _regular_ `pwsh` terminal in VS Code (but _not_ the Extension Terminal), I get:

```
> $PROFILE | Get-Member -Type NoteProperty

   TypeName: System.String

Name                   MemberType   Definition
----                   ----------   ----------
AllUsersAllHosts       NoteProperty string AllUsersAllHosts=/usr/local/microsoft/powershell/7/profile.ps1
AllUsersCurrentHost    NoteProperty string AllUsersCurrentHost=/usr/local/microsoft/powershell/7/Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts    NoteProperty string CurrentUserAllHosts=/Users/andschwa/.config/powershell/profile.ps1
CurrentUserCurrentHost NoteProperty string CurrentUserCurrentHost=/Users/andschwa/.config/powershell/Microsoft.PowerShell_profile.p…
```

Note how there are _four_ profiles! Read this [about Profiles](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3) documentation that I'm going to attempt to shortly summarize. There are unique profile paths for each combination of: `CurrentUser`, `AllUsers`, `CurrentHost` and `AllHosts`. So inspecting the output above you'll see that the paths are different specifically for the combinations with `CurrentHost`, and _that's_ because the current host in this instance is the _Extension Terminal_ (instead of the default PowerShell host). This is _by design_ of PowerShell, and allows profiles to be configured differently depending on the host being run.

What I usually do is put Extension Terminal specific profile code in its profile file, `Microsoft.PowerShell_profile.ps1`, and I put profile code that I want shared among _all hosts_ (e.g. the Extension Terminal and other `pwsh` terminals) in `CurrentUserAllHosts`, which for me is `/Users/andschwa/.config/powershell/profile.ps1`.

You can access this by opening it as a property off that `$PROFILE` variable you found: `code $PROFILE.CurrentUserAllHosts`.

**Comment by andschwa** [comment]
Yup, it's a _very_ PowerShell thing! That said, `.bashrc` is _also_ [ridiculously complicated](https://blog.flowblok.id.au/2013-02/shell-startup-scripts.html).
