### ISSUE TITLE
Powershell extension has not finished starting up yet. Please try again...

### ISSUE THREAD

**Issue by TESTER-sec** [PowerShell/vscode-powershell#4699]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [_open and closed_ issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/main/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.
- [X] If this is a security issue, I have read the [security issue reporting guidance](https://github.com/PowerShell/vscode-powershell/blob/main/SECURITY.md).

### Summary

When launching the PowerShell: Command Explorer, a notice appears every single time in the lower right corner and remains there until the user manually closes it...

"Powershell extension has not finished starting up yet. Please try again..."

This is a very long-standing issue that you people have never fixed. It has been reported countless times over the years. So maybe one of you should take us users who take the time to report this recurring stuff ad nauseum seriously and definitely solve this issue permanently once and for all? Hmmm?

If someone does not like my tone, well I'm not going to apologize for it. The team responsible for VSCode PowerShell extension has a very long tradition of dismissing user reports and not fixing stuff. What credibility it once had has long since been wasted due to the long list of things never fixed.

<img width="960" alt="Untitled" src="https://github.com/PowerShell/vscode-powershell/assets/97270395/0b2ca896-ee4a-4786-b36e-db6ebc9b5726">

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visual Studio Code Version

```console
Version: 1.81.1 (system setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

### Extension Version

```console
v2023.6.0
```

### Steps to Reproduce

1. Launch VSCode
2. Launch the PowerShell: Command Explorer

**Comment by andyleejordan** [comment]
There does not appear to be a bug here. It looks like the intended message is showing up when the Command Explorer button is used to activate the extension. Since it can take several seconds for the PowerShell process to initialize (mostly due to PowerShell startup time and users' profile activation, neither of which we have any control over) the message you see is displayed to inform the user why the Command Explorer is blank for a little bit. It can just be dismissed as you found with the X button. Your extension did start up correctly and the commands were populated, as indicated by your screenshot.

> This is a very long-standing issue that you people have never fixed. It has been reported countless times over the years. ~~So maybe one of you should take us users who take the time to report this recurring stuff ad nauseum seriously and definitely solve this issue permanently once and for all? Hmmm?~~

This is simply not the case (I struck through the unnecessary CoC violation here and am just responding to the first part). In fact, no prior issues have been reported about the (by design) display of this message, so this is not a long-standing issue. And as I explained above, there is no bug either. I think you are confused because there are a myriad of issues reporting bugs with "startup" nearly all of which are distinct and caused by unique issues, and we do our best to diagnose and fix each one.

Thanks! Marking this as resolved now. Please take the time to review the linked Code of Conduct before any further participation in Microsoft open source projects. Appreciate it!

**Comment by mgabbard-lbce** [comment]
What does "Please try again" mean?

**Comment by allenhuffman** [comment]
I just installed PowerShell for Mac to try it out (using brew) and I am seeing this message as well. If I dismiss it, it comes right back when I try to click on the "PowerShell" (looks like a DOS prompt icon) on the left. ("PowerShell: Command Explorer")

**Comment by modusCell** [comment]
Power-shell extension is not working "PowerShell extension has not finished starting up yet. Please try again in a few moments."

M3 Silicon Mac
macOS Sonoma 14.2.1 (23C71)
VScode Version: 1.85.1 (Universal)
Extension: v2024.0.0

<img width="495" alt="Screenshot 2024-01-12 at 3 36 44 pm" src="https://github.com/PowerShell/vscode-powershell/assets/1199239/30af4bdd-a519-4516-8c17-9df7ca33c370">

**Comment by mgabbard-lbce** [comment]
I don't know how I was put on the CC for this message, but please remove me.

**Comment by mgabbard-lbce** [comment]
Oh, ok thanks.

**Comment by AScriver** [comment]
I've been running into this issue for the past week as well. Honestly not sure what was causing it, but setting the extension to use Powershell [Core](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows) (pwsh) instead of Desktop seems to have cleared it up on my end.

```
{
    "powershell.powerShellDefaultVersion": "pwsh",
    "powershell.powerShellAdditionalExePaths": {
        "pwsh": "\"C:\\Program Files\\PowerShell\\7\\pwsh.exe\""
    },
}
```
