### ISSUE TITLE
Intellisense Broken

### ISSUE THREAD

**Issue by Lee303** [PowerShell/vscode-powershell#50]
With 2 fresh installations on 2 seperate Windows 7 installations, Intellisense appears to be broken, with no suggestions offered for Cmdlets or variable names.

Both were installed via the built in extension installer

**Comment by daviwil** [comment]
Hi Lee, currently this extension is supported only on machines that have Windows Management Framework 5.0 installed (which contains PowerShell v5).  Since this is a Windows 7 machine, can you confirm what version of PowerShell you're running by grabbing the results of the `$PSVersionTable` variable?  We intend to support both [PowerShell v3 and v4](https://github.com/PowerShell/PowerShellEditorServices/issues/73) in the future.

Also it might be helpful if you send the log file from the language service, you can find that here:

`c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell\bin\EditorServices.log`

E-mail that to my GitHub username @microsoft.com and I'll take a look.

**Comment by Lee303** [comment]
Hi,

Apologies, I must have missed the PS 5 requirement! I'll close this now.

Thank you for your response :)

**Comment by daviwil** [comment]
Give PS5 a try and if it doesn't work, feel free to reopen the bug!
