### ISSUE TITLE
Integrated console sometimes does not have a scrollbar at startup

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#536]
Sometimes the integrated console does not have a scrollbar.  I have not uncovered the cause of this issue yet, but you can get the scrollbar back for your current session by resizing the width of the VS Code window slightly.

**Comment by ViperTG** [comment]
I can reproduce this issue using VS Code 1.10.2 and PowerShell VSCode extension 0.11.0.
It only happens when I have the explorer pane on the left open and I "hot exit" a script without saving it, then when i open VSCode again and let the console open and then run my unsaved script then it outputs in the integrated console but I cannot scrool up or down in it. Changing the size of the console window makes the scrollbar appear again.
If i save the script before exiting VSCode it does not happen.
If i don't have the left explorer (possibly the others as well) pane open when closing VSCode it does not happen.

**Comment by daviwil** [comment]
Apparently this is a VS Code issue: https://github.com/Microsoft/vscode/issues/20505.  I'll keep this issue open until the VS Code bug is resolved.

**Comment by anon01924** [comment]
I can reproduce.

**Comment by daviwil** [comment]
@anon01924 this should be fixed in VS Code 1.15.0, can you try it and let me know?

**Comment by anon01924** [comment]
fixed

**Comment by daviwil** [comment]
Thanks a lot!  Closing for now, will reopen if anyone else sees the issue again.
