### ISSUE TITLE
output, console, terminal confusion (when debugging)

### ISSUE THREAD

**Issue by bughit** [PowerShell/vscode-powershell#552]
vscode 1.10.2
vscode-powershell 0.10.0
win7 x64
powershell 3

It looks like the integrated terminal now receives all output and also functions as debug eval console.  Is there a reason to still show the output and debug console tabs?  This seems to promote confusion, you can still try to eval in the console but the eval output goes to the terminal.

**Comment by daviwil** [comment]
This is a UI feature of VS Code itself, unfortunately there's no way for me to hide those elements.  If you feel strongly that this causes major user confusion you could certainly file a bug at the [Microsoft/vscode](https://github.com/Microsoft/vscode/issues) repo.

**Comment by reddwarf666** [comment]
I was also confused by the Terminal receiving the output. Plus the Debug window receives nothing anymore and cannot evaluate variables and the likes.

This 0.10.0 version is confusing and I went back to 0.9.0

If it may be unclear what I want/expect so let me try to explain my expectations:
When I debug I want output of the code to appear in the Debug window and statements I type/paste in/on the Debug line (the 1 row line with the ">" sign) to evaluate with the inclusion of variables in scope.

**Comment by daviwil** [comment]
Why do you prefer the Debug Console to the integrated console?  You can evaluate statements where the debugger is stopped in the integrated console in same way that you did before with the Debug Console.  It's a much better experience overall.

If you've ever used the PowerShell ISE before, just treat the integrated console like you would the ISE's console.

**Comment by reddwarf666** [comment]
Because I am used to it, it makes sense to have debug output to go into the debug window and the Terminal window is not working right, at least not as I am used to the debug window.
On OSX with VSCode the Terminal window it generating weird characters and is (for me at least) a bad experience that makes me long for the Debug window. Well, at 0.10.0 it does, just tried again in 0.9.0 and using the arrow keys works fine there but in 0.10.0 it gave me odd escape characters.

Let me ask you a question: why is the Debug window still there? If it is not logical and and obsolete, why is it still there? What is the intention if not being used for debugging?

And truly, the experience of having the Terminal window take over the output, the escape characters messing up my commands made 0.10.0 a bad experience that cost me 1/2 a day because I thought I messed up some configuration somewhere or that some installation part was broken. It was a bad experience. So bad that I was super happy I found out I could go back to 0.9.0 and could produce work again. I have yet to see the positive and productiveness of this decision. But that could be me of course.
