### ISSUE TITLE
Feature Request: Restart PowerShell integrated console on debug

### ISSUE THREAD

**Issue by Glober777** [PowerShell/vscode-powershell#564]
First of all, let me thank you for such an upgrade. I find the integrated console very useful. Especially I like the fact that it doesn't close after the debugged script has finished executing so I can research the state that was left after it interactively.

On the other hand, I was wondering if there's a clean way of getting the integrated console automatically restarted when I'm starting the debug session (preferably configurable through launch.json, i.e. by referencing a task or via a separate attribute)? What I currently do, is I'm deleting the integrated console, which brings up a prompt suggesting me to restart it, but there were a few times when I forgot to do that and got burned by that.

Thanks!

**Comment by daviwil** [comment]
Thanks a lot @Glober777!  I've got plans to add an option similar to what you're suggesting: https://github.com/PowerShell/vscode-powershell/issues/367.  One thing I didn't consider is keeping the new session's console open after debugging completes so that you can poke around a bit.

I'm closing this issue in favor of the other one, please let me know there if you can think of anything else that might be helpful to have!
