### ISSUE TITLE
Session crash when a breakpoint is hit in the console while not in debug mode

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#620]
Repro steps

1. Open a .ps1 file and set breakpoints using `Set-PSBreakpoint -Script <script> -Line <##>`
2. Run the script from the console by invoking with its script name
3. PowerShell hits the breakpoint, session crashes and prompts to restart

**Comment by Jrouzies** [comment]
Hello, I confirm, same issue.

I posted this in wrong Git (on vcode directly) if it can help :

**ello !

The new version with PowerShell is a lot better, still I cannot debug my script by running it through Terminal because PowerShell App will crash.

VSCode Version: 1.10.2
OS Version: Windows Server 2012 R2
Steps to Reproduce:

Have Powershell module for VSCode installed
Open Powershell script that use Args
Press F5 to debug once (do whatever, stop debug)
Put debug point in the script
Now I want to run my script with args :
-so I type in the Powershell terminal the command with args (with a debug point in the script)
-As soon as I hit enter to run the command, "Powershell" application crash
You can see on picture bellow 👍

![image](https://cloud.githubusercontent.com/assets/26656800/24349718/30c75446-12e0-11e7-99d7-a9b02051a517.png)

Crash detail :

Problem Event Name:	PowerShell
NameOfExe:	powershell.exe
FileVersionOfSystemManagementAutomation:	6.3.9600.17400
InnermostExceptionType:	System.InvalidOperationException
OutermostExceptionType:	System.InvalidOperationException
DeepestPowerShellFrame:	unknown
DeepestFrame:	rotocol.MessageProtocol.ProtocolEndpoint.SendEvent
ThreadName:	unknown
OS Version:	6.3.9600.2.0.0.16.7
Locale ID:	2057

This is really blocking to debug, because using F5 and then typing args is loss of time (plus not mandatory args are not used).

Thanks !**
