### ISSUE TITLE
region/endregion tags do not fold like they do in the PowerShell ISE

### ISSUE THREAD

**Issue by planetscripton** [PowerShell/vscode-powershell#635]
### System Details

- Operating system name and version: MacOS 10.12.3
- VS Code version: 1.10.2
- PowerShell extension version: 0.11
- Output from `$PSVersionTable`: 
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.14
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
Copy / paste the below commands into the PowerShell Integrated Terminal, and paste the output here

.10.2
8076a19fdcab7e1fc1707952d652f0bb6c6db331
PS /Users/dan/Documents/projects/test> $pseditor.EditorServicesVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
0      11     0      0

AngularDoc.angulardoc-vscode@2.0.2
PeterJausovec.vscode-docker@0.0.13
Zignd.html-css-class-completion@1.0.3
abusaidm.html-snippets@0.1.0
aeschli.vscode-css-formatter@0.0.2
ajhyndman.jslint@1.2.1
bajdzis.vscode-database@1.2.0
christian-kohler.npm-intellisense@1.3.0
christian-kohler.path-intellisense@1.2.0
dollyn.line-counter@0.2.0
donjayamanne.jquerysnippets@0.0.1
eg2.tslint@0.11.0
fabianlauer.vs-code-xml-format@0.1.5
humy2833.ftp-simple@0.4.15
infinity1207.angular2-switcher@0.1.4
johnpapa.Angular2@2.1.2
lukasz-wronski.ftp-sync@0.3.2
miramac.vscode-exec-node@0.4.1
mohsen1.prettify-json@0.0.3
ms-mssql.mssql@0.3.0
ms-vscode.PowerShell@0.11.0
ms-vscode.csharp@1.8.0
ms-vscode.typescript-javascript-grammar@0.0.18
msjsdiag.debugger-for-chrome@2.7.1
natewallace.angular2-inline@0.0.17
naumovs.node-modules-resolve@1.0.2
octref.vscode-json-transform@0.1.2
qinjia.view-in-browser@0.0.5
seanmcbreen.MDTools@1.0.0
tht13.html-preview-vscode@0.1.1
web-dave.vsc-angular-cli@1.0.0
wmaurer.join-lines@0.2.2
zerocrunch.commentator@1.0.3



```

### Issue Description

I am experiencing a problem with...

In Powershell ISE, when you use the tag #region and #endregion, the editor automatically places a + next to the region tag to allow you to collapse that section. In VSCode this doesn't seem to be a feature.

I use this feature constantly to organize my functions scripts etc.

### Attached Logs

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems)
about capturing and sending logs.

**Comment by dotps1** [comment]
https://github.com/Microsoft/vscode/issues/3422

**Comment by daviwil** [comment]
Yep, @dotps1 is correct, we are waiting for the VS Code team to implement proper folding based on language syntax.  I'm going to keep the bug open this time so that new users can find it easily.

**Comment by gtatelive** [comment]
@daviwil  do you have any insight on when the VSCode team might address this?

**Comment by BatmanAMA** [comment]
This seems to work as expected if the #region and #endregion tags are not indented, however in most cases auto-format kills this. I'm not sure if that helps at all, but I figured it's worth pointing out. Currently on version 1.0.0 of this extension and version 1.12.1 of vs code.

**Comment by daviwil** [comment]
Ahhh yep, code formatting "fixes" it ;)  Now that the extension is at 1.0 I'm going to start investigating how to get this issue fixed in VS Code.

**Comment by dan185818** [comment]
I don't see the behavior working correctly, with VS Code version 1.12.2 and the extension at 1.0.0.  I have a script that uses nested regions (One for folding all functions, then inside that, one for functions I've gotten from the Internet, one region for "database" functions, one for "log parsing" functions, and one for "Data Processing" functions.  This makes it so that I can fold all the functions, or most of the functions and just get to what I'm interested in.

The folding works perfectly in the ISE, but in VS Code, the only one that folds is the "Internet functions" part, which is the first "subregion".

All my #region and #endregion comments are not indented at all.

Since this is my first post, please let me know what will help best? Do you want the script? Screenshots? Is this the right place? VSCode looks like it could be really cool, and this extension is pretty awesome, so I want to start using it, but I use regions extensively, and this would be really nice.

**Comment by daviwil** [comment]
@dan185818 this is an ongoing limitation of VS Code, there is still no fix on the radar yet.

**Comment by tylerl0706** [comment]
VSCode added region support and this is fixed! Please open a new issue if you see any problems.
