### ISSUE TITLE
~\Documents\... should not offer completing to C:\Users\andre\Documents\...

### ISSUE THREAD

**Issue by AndrewGaspar** [PowerShell/vscode-powershell#67]
Tab completion on ~ relative paths replaces the ~ with the absolute user path. This is kind of useless since I rarely want to specify my own user path, but rather the current user path in my scripts. I know that PowerShell's REPL likes to over-eagerly replace ~ with the literal path,but that's acceptable since that is disposable code. It is a little more frustrating in an editor where you're writing scripts with more permanence.

This might be more relevant to https://github.com/PowerShell/PowerShellEditorServices. Not sure where the break down on these kinds of things falls.

![image](https://cloud.githubusercontent.com/assets/2292643/12075260/352b3b9c-b12f-11e5-8ac6-f1a9be8d4ff8.png)

**Comment by rkeithhill** [comment]
I've noticed ISE doing this as well for both `~` and `$home` and I don't like it.  As you say, it takes a portable construct like `~` and `$home` and replaces it with a non-portable path.  BTW the same thing happens for variable that contains a path like `$env:windir`, `$env:USERPROFILE`, `$env:LOCALAPPDATA`, etc.  

It would be nice to have this fixed to retain the variables in the path.  The completion would have to use double quotes around paths with spaces (instead of single quotes).

**Comment by daviwil** [comment]
Hmmm, this may require an extra layer of logic on top of the current completion results since I'm taking them verbatim from the PowerShell API.  I agree with you both though, in the context of writing code, the tilde should not be resolved to the full path.

Andrew, feel free to file issues like this against the PowerShellEditorServices repo in the future.  Your guess is correct, most of this behavior comes from that library rather than the VS Code extension itself :)  Thanks for another great bug report!

**Comment by daviwil** [comment]
Just filed this bug to track it for PowerShell Editor Services:

https://github.com/PowerShell/PowerShellEditorServices/issues/100

**Comment by BatmanAMA** [comment]
It may not be worth pointing out that it looks like following [this style guide rule](https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/07b47f97085efeb5b33af1b5556e4718683a2293/Style-Guide/Naming-Conventions.md#avoid-the-use-of--to-represent-the-home-folder) avoids this issue (admittedly, it doesn't provide any completion, but that seems preferable in this situation to me.)

**Comment by SydneyhSmith** [comment]
Marking this as an external PowerShell issue
