### ISSUE TITLE
Ran debug on a script and some other command executed instead

### ISSUE THREAD

**Issue by mjbvz** [PowerShell/vscode-powershell#687]
_From @ssaari on April 18, 2017 19:46_

- VSCode Version:  1.10.2
- OS Version: Microsoft Windows Server 2012 R2 Standard

Steps to Reproduce:

1.  Right clicked a PowerShell script in Windows Explorer
2.  Chose Open With Code.  No other open scripts in the editor.  I edited a file path in the script and did not click anywhere else.
3.  Clicked the "Start Debugging" green arrow
4.  The script was not executed.  It kicked off a command that I now see in the Terminal window.  It looked like something I had typed in a regular PowerShell console weeks ago.  No idea how that was stored or cached or why the script did not run.  This was seriously bad as it kicked off an unwanted ETL process.

_Copied from original issue: Microsoft/vscode#24969_

**Comment by mjbvz** [comment]
@ssaari From your description, this sounds like an issue with the powershell extension. Can you check if you have a `.vscode/launch.json` file in the directory where the script is stored? What happens if you run the script in powershell directly?

**Comment by ssaari** [comment]
@mjbvz Matt, you nailed it.  Thank you!  I'm my own worst enemy.  I had forgotten that I had added a script and argument keys to the launch.json file weeks ago.  Boy would it be nice to be have a warning if the script in launch.json is not the active editor file.  Is there a wish list?

**Comment by rkeithhill** [comment]
> it be nice to be have a warning if the script in launch.json is not the active editor file. Is there a wish list?

I quite often have a dedicated script that I want to run when debugging (debugHarness.ps1 or simply "Invoke-Pester").  A warning popping up every time would get old quick.  It might be nice if VSCode made it more obvious which debug configuration you are currently debugging with because that drop down list in the Debug view is quite narrow.  

Perhaps VSCode could display the Debug configuration name in the title bar during a debug session.  That would be more helpful than this:
![image](https://cloud.githubusercontent.com/assets/5177512/25188678/24c72c3c-24e4-11e7-8403-427ac1453ddc.png)

**Comment by daviwil** [comment]
Agreed, I think a message or confirmation prompt would be hard to get right without being annoying.

**Comment by mjbvz** [comment]
Ok, I've created https://github.com/Microsoft/vscode/issues/25039 to track adding debug config name to the titlebar in vscode

Sorry for moving this over to the powershell extension repo too soon. Closing since the issue seems to have been resolved

**Comment by daviwil** [comment]
@mjbvz no problem!  It made sense to move it here since it's specifically about functionality in the PowerShell extension :)
