### ISSUE TITLE
Add ability to support multiple PS sessions

### ISSUE THREAD

**Issue by ebekker** [PowerShell/vscode-powershell#73]
Similar to the way that ISE supports multiple session tabs, it would be useful to allow multiple isolated sessions in vscode.  The visual metaphor may not work the same as the vscode UI frame may not allow the tabs-within-tabs concept, but perhaps something like a drop down that identifies a session ID associated with the current script view, and an option to "create new" so that the code can be executed under different sessions.

**Comment by daviwil** [comment]
Hi Eugene,

Unfortunately we're limited by VS Code's general model in this case.  Their concept of a session is an open window, so if you wanted multiple PowerShell sessions you'd need to open more than one window on different "workspace" folders.  I don't think they'll allow us to add extra UI to select sessions since they're trying to keep things pretty streamlined.

Can you tell me more about how multiple session support would benefit your workflow?  I certainly understand the general utility of it, but I'm curious whether there's something you were trying to do but couldn't.

**Comment by ebekker** [comment]
Hi Dave,

So I was thinking about switching to vscode for all of my PS-related editing, but one of the things that I rely on with ISE is that I can have multiple sessions open to track a few different "trains of thought" for example different things that I'm working on that are distinct.

Another example would be when I'm working on developing and testing a module, I might be editing the module and related artifacts in one session and pop open a new, clean session, import the module and do some testing to make sure that the module is self-contained and nothing was in missed in scope.

I was just playing around with VSCode a bit and I wonder if there is some "artificial" structure that could be imposed by the file system -- such as grouping your PS scripts into subdirs and flagging each dir as it's own session when debugging/executing?  Maybe you could create a little meta file like `.psrun` or something that gives a hint to the editor about how to run.

Although, I guess those details can be tracked within the editor itself, for example it has to track where debug breakpoitns are set, so it seems there's the capacity for this already there?

**Comment by JustinGrote** [comment]
This is a long time after the initial context of this question, but today you can run multiple separate editors in multiple separate projects with different versions of PowerShell. It is extremely unlikely that a "runspace per editor" type setup would be feasible to implement in the current pipelined scenario, and this is the recommended workaround, in case anyone is comng here wondering the status :).

**Comment by andschwa** [comment]
Thanks Justin, going to mark this as resolved too.
