### ISSUE TITLE
Integrated Console input not added to history if there is a parse failure

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#785]
If you type a command into the Integrated Console and it returns an error due to parsing the input text, the input line is not added to the user's command history.

**Comment by FireInWinter** [comment]
I've run into the same thing.  I notice the schedule for this has been bumped a few times and was wondering if we have an idea of when this will be addressed.  I have 1.4.1 installed, so I'm hoping this will be addressed soon as having a really long line and hitting enter at the wrong time makes it so you have to copy from the lines above it instead of just hitting up arrow.

**Comment by SydneyhSmith** [comment]
Closing as this should be resolved
