### ISSUE TITLE
[Question] Is there a way to use Register-ArgumentCompleter in an editor?

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/vscode-powershell#831]
If so, how to declare them ?

**Comment by LaurentDardenne** [comment]
_>>Have you tried it?_
Yes, into the integrated console. It works.

In the editor, the completion work with a ValidateSet  attribute :
![image](https://user-images.githubusercontent.com/4894452/26886232-1fc846e8-4ba5-11e7-9319-7eee822b378e.png)
But not with this :
![image](https://user-images.githubusercontent.com/4894452/26886189-12a27fe2-4ba5-11e7-9d3f-d3664af067b4.png)

This possibility is it supported ?

**Comment by daviwil** [comment]
Interesting, I didn't know they weren't showing up in the editor's completions.  I'll take a look, thanks for pointing it out!

**Comment by mattmcnabb** [comment]
@LaurentDardenne I don't believe this will work the way you expect - you'd have to execute Register-ArgumentCompleter first in order for intellisense to pick up the completion values.

![image](https://user-images.githubusercontent.com/6998507/26907614-ca652068-4bc2-11e7-84af-467bf7e0d9c7.png)

**Comment by LaurentDardenne** [comment]
@mattmcnabb I agree.
But for the moment I don't know the code source of vscode-powershell...

**Comment by TylerLeonhardt** [comment]
Since we don't want to execute PowerShell script without you knowing, @mattmcnabb is right here - you absolutely need to execute the `Register-ArgumentCompleter` in order for it to show up in intellisense.

To do that, all you need to do is select the full `Register-ArgumentCompleter` code and hit F8 to run it. Once you do that, the completions will show up.

I don't think this is an issue in the PowerShell extension and is actually by design. Since this is an old issue, I'll close it. If you feel differently, feel free to let me know.
