### ISSUE TITLE
Symbol navigation should show progress indicator for long requests

### ISSUE THREAD

**Issue by daviwil** [PowerShell/vscode-powershell#879]
If you use "Go to Definition" or "Find References" in a project with hundreds of PowerShell scripts it can take a long time (~10 seconds) for results to come back.  Until we get proper symbol indexing working we should at least show a progress indicator so that the user knows that the action was initiated.

This will require inserting a middleware handler into the LanguageClient so that we can intercept the definition and references requests and show a progress indicator until the response comes back.

/cc @jakeoshins

**Comment by fflaten** [comment]
Anyone who can test with latest preview version (v2023.2.0)? Hopefully a lot faster so this can be closed.

**Comment by andschwa** [comment]
@SeeminglyScience can you benchmark the preview?

**Comment by andschwa** [comment]
Ok so @SeeminglyScience I clone [dbatools](https://github.com/dataplat/dbatools) which looked like a pretty dang big project. Interestingly, with `powershell.analyzeOpenDocumentsOnly` set to `false`, the stable extension was only showing opened documents' symbols on `Cmd-T`.

The preview extension on the first run took a couple seconds to populate, in which time Code's own pop-up had a progress indicator bar, and then had all the symbols. Subsequent runs are still not instantaneous (since we are iterating over the symbols and doing a little bit of processing each time: https://github.com/PowerShell/PowerShellEditorServices/blob/422e2cda25e8794f1912a494bf749e99b4125130/src/PowerShellEditorServices/Services/Workspace/Handlers/WorkspaceSymbolsHandler.cs#L35-L94) but it's also like less than a second, including while typing to filter, it's updating on my macMini in like a quarter second I'd say. So, in my opinion, pretty dang fast, though it'd be interesting to optimize it further.

I tried go-to definition on `Get-DbatoolsConfigValue` (which has 127 references according to the code lens) and it was instant, as was the code lens itself.

Interestingly I uncovered that if you're on say `$PSBoundParameters.IncludeLocal` it fails to find the definition of `IncludeLocal`. Perhaps there are a few prefixes we should strip from variable names to make this guessing game work a bit better.

@potatoqualitee I would be very interested to hear your feedback on working with symbols in the latest preview!

For now, I'm going to consider this done.
