### ISSUE TITLE
Launch & Debug a Docker powershell container ?

### ISSUE THREAD

**Issue by tsugliani** [PowerShell/vscode-powershell#892]
### Ability to debug a Powershell script/session in a docker container possible ?

A little background about my use case:

I need to work with multiple versions of powershell because of some other incompatibility issues, and for that purpose I use docker containers, but I don't know if there is a nice way to troubleshoot powershell scripts from within Visual Studio Code & debugger capability today ?

Basically my setup is as following:
- Visual Studio Code & `vscode-powershell` extension on macOS
- Running the powershell scripts through docker with a similar docker image as `microsoft/powershell:$version`
- Expecting to use debug capability from Visual Studio Code

I've found an article explaining the process for a sample dotnet application:
 https://wannabeegeek.com/2016/12/17/debugging-asp-net-core-apps-running-in-docker-containers-using-vs-code/
It seems some of the stuff happens in the `launch.json` file, but didn't see any example of how to setup this with powershell and my environment is pretty different than the whole dotnet stack depicted in the previous article.

Any insight/links would be greatly appreciated !

Thanks in advance,

**Comment by rkeithhill** [comment]
Debugging a remote script requires that the remote computer (container) has PSRemoting enabled.  Since you are running in a container, I assume you'll need to map the container's port 5985 to a localhost port (say 15985).  Debugging with VSCode is done via the Debug Interactive Session configuration.   Once you've started that session, you use Enter-PSSession localhost -port 15985 to open a remote sessions.  Then use pesedit to open a script in the container and from there you can set breakpoints.  See this blog post for more info: https://blogs.technet.microsoft.com/heyscriptingguy/2017/02/13/debugging-powershell-script-in-visual-studio-code-part-2/

I have not tried to use PSRemoting to connect to a PowerShell session running in a container.  If you can get over that hurdle, you should be to debug with VSCode.

**Comment by tsugliani** [comment]
@rkeithhill Thank you, I'll give it a try !

**Comment by Fexception** [comment]
@Tsugliani, were you able to get this to work? If So, could you shed some light on how you did it? I'm experiencing the same issue.

Thanks in advance!

**Comment by SydneyhSmith** [comment]
Closing this issue as inactive, will re-open if there is more activity
