### ISSUE TITLE
No code-complete in terminal

### ISSUE THREAD

**Issue by The-IT-Guy** [PowerShell/vscode-powershell#905]
Is it possible to use code-complete in the PowerShell integrated terminal?
Especially while debugging it would be really great to be able to write some small commands using code-complete like in ISE.
Instead, I have to write these commands in a new ps1 file and execute the file (or just a selection from the file). Is there a better way to do this?

Regards,
Fabian

**Comment by daviwil** [comment]
By "code complete" do you mean tab completion or the IntelliSense UI popup that the ISE has in the console?  The former works, the later probably will not happen because the VS Code team would have to enable it.  The best you might get is PSReadline's completion menu that gets rendered in the console once we get PSReadline hooked up there.

**Comment by The-IT-Guy** [comment]
Hi David,
thanks for your reply. I'm talking about the IntelliSense popup menu in ISE. Sad that won't work anytime soon 😞 
Do you have any info on when PSReadline is going to be supported?

- Fabian

**Comment by daviwil** [comment]
Should be within the next release or two, I'm working on it now.  Subscribe to issue https://github.com/PowerShell/vscode-powershell/issues/535 to be notified when that gets done.
