### ISSUE TITLE
Intellisense :: Import-DscResource not showing up

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/vscode-powershell#92]
# Issue 
I'm using Visual Studio Code 0.10.6 on Mac OS X El Capitan. Inside a `configuration` block, the `Import-DscResource` keyword is missing in Intellisense.

<img width="528" alt="screen shot 2016-02-08 at 10 22 52 am" src="https://cloud.githubusercontent.com/assets/466713/12893427/4b1d57a0-ce4e-11e5-891d-a7b63772e9fd.png">

# Expected Result

I'd expect that, inside a DSC Configuration block, that the `Import-DscResource` keyword would show up in Intellisense, along with its named parameters (`-Name` and `-Module`).

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by daviwil** [comment]
Hey Trevor, this is due to the fact that the PowerShell language service isn't running for you on OS X.  Here's what I see when running the extension on Windows:

![image](https://cloud.githubusercontent.com/assets/79405/12896952/87d691ce-ce59-11e5-82e7-bd6058192f40.png)

If you still see the issue when running the extension on Windows, please feel free to reopen the issue!

**Comment by pcgeek86** [comment]
@daviwil Gotcha, so this isn't intended to work on Mac OS X. Gotcha. :) Is there a way to connect VS Code on Mac OS X to the language service on my Windows VM, as long as it's running? I've got an up-to-date Windows 10 client running under VMware Fusion.

ps. Us peons can't reopen issues if they're closed by the Ivory Tower. :)

**Comment by daviwil** [comment]
I didn't realize that people weren't able to reopen issues if I close them.  I guess they do that to minimize abuse.  Sorry about that!  I'll respond to the rest via email :)

**Comment by samsu198** [comment]
I am facing the same problem, I am executing from windows client 10 to azure but not happening via power shell, could you anyone help here...       

 Import-DscResource -ModuleName xActiveDirectory, xStorage, xNetworking, PSDesiredStateConfiguration, xPendingReboot
    
Error is 👎 

18:23:17 - C\CreateADPDC.ps1:15 char:5
18:23:17 - +     Import-DscResource -ModuleName xActiveDirectory, xStorage, xNetwo ...
18:23:17 - +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:23:17 - Could not find the module 'xActiveDirectory'.

**Comment by tylerl0706** [comment]
@samsu198 I think you'll have better luck asking this question on Stack Overflow or on the [PowerShell chat groups](https://github.com/PowerShell/PowerShell/blob/master/README.md#chat-room).

This issue was opened against the VSCode extension about intellisense and don't think your having the same problem.
