### ISSUE TITLE
Question: ps1 file and compatibility to version 2 of Power Shell

### ISSUE THREAD

**Issue by atiedemann** [PowerShell/vscode-powershell#943]
Hi all together,

this is only a question to vscode powershell.
Is this possible that I can define that a file must be compatible with PSVersion 2?

I know that this is possible with ISE and extension (ISESteroids) of Tobias Weltner @TobiasPSP but is this possible with vscode powershell?

Thanks
Arne

**Comment by mattmcnabb** [comment]
@atiedemann Are you familiar with the "#requires" statement in PowerShell? This is how you can prevent a script from running unless it meets certain prerequisites. To learn more, run:

```powershell
Get-Help about_requires
```

ISESteroids does have some great magic in there, though, that really helps us with version compatibility and analyzes our code to make sure we haven't violated our stated PowerShell version requirements. I don't believe that's really possible with the VSCode PowerShell extension at the moment, but we do have the PSScriptAnalyzer that can do similar things. In fact, it already has some rules that scan for common version compatibility issues, and it may gain more in the future.

**Comment by rjmholt** [comment]
Looks like we missed this issue.

Because [PowerShell 2 is deprecated](https://blogs.msdn.microsoft.com/powershell/2017/08/24/windows-powershell-2-0-deprecation/), neither the VSCode extension nor PSScriptAnalyzer support it directly.

PSScriptAnalyzer has the [**UseCompatibleCmdlets**](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/UseCompatibleCmdlets.md) rule for targeting different PowerShell versions to the one you are currently on, but as far as I know this doesn't currently support v2.

More work is being done in PSScriptAnalyzer to support cross-targeted PowerShell scripts as well, so the general experience here should improve soon.
